### import csv and check shape

In [48]:
import pandas as pd
import os

In [49]:
billing = pd.read_csv("data/billing.csv")
visits = pd.read_csv("data/visits.csv")
patient = pd.read_csv("data/patients.csv")

print("patient shape :",patient.shape)
print("billing shape :",billing.shape)
print("visits shape :",visits.shape)

patient shape : (5000, 7)
billing shape : (25000, 7)
visits shape : (25000, 8)

In [50]:

billing_data= billing.to_dict(orient="records")
billing_data

[{'bill_id': 1,
  'visit_id': 1,
  'billed_amount': 23550.0,
  'approved_amount': 21429.62,
  'claim_status': 'Paid',
  'payment_days': 8.0,
  'billing_date': '2025-11-03'},
 {'bill_id': 2,
  'visit_id': 2,
  'billed_amount': 88539.01,
  'approved_amount': 19725.49,
  'claim_status': 'Pending',
  'payment_days': nan,
  'billing_date': '2025-12-16'},
 {'bill_id': 3,
  'visit_id': 3,
  'billed_amount': 25949.3,
  'approved_amount': 1580.95,
  'claim_status': 'Rejected',
  'payment_days': nan,
  'billing_date': '2025-11-20'},
 {'bill_id': 4,
  'visit_id': 4,
  'billed_amount': 8349.57,
  'approved_amount': nan,
  'claim_status': 'Pending',
  'payment_days': nan,
  'billing_date': '2025-08-16'},
 {'bill_id': 5,
  'visit_id': 5,
  'billed_amount': 88539.01,
  'approved_amount': 86803.45,
  'claim_status': 'Paid',
  'payment_days': 30.0,
  'billing_date': '2025-08-23'},
 {'bill_id': 6,
  'visit_id': 6,
  'billed_amount': 15260.62,
  'approved_amount': 15170.82,
  'claim_status': 'Paid',
  'payment_days': 53.0,
  'billing_date': '2025-10-12'},
 {'bill_id': 7,
  'visit_id': 7,
  'billed_amount': 7359.98,
  'approved_amount': 6682.34,
  'claim_status': 'Paid',
  'payment_days': 27.0,
  'billing_date': '2026-01-07'},
 {'bill_id': 8,
  'visit_id': 8,
  'billed_amount': 9612.77,
  'approved_amount': nan,
  'claim_status': 'Rejected',
  'payment_days': nan,
  'billing_date': '2026-01-19'},
 {'bill_id': 9,
  'visit_id': 9,
  'billed_amount': 37201.86,
  'approved_amount': 35682.85,
  'claim_status': 'Paid',
  'payment_days': 54.0,
  'billing_date': '2026-01-20'},
 {'bill_id': 10,
  'visit_id': 10,
  'billed_amount': 77351.57,
  'approved_amount': 4276.21,
  'claim_status': 'Rejected',
  'payment_days': nan,
  'billing_date': '2026-01-20'},
 {'bill_id': 11,
  'visit_id': 11,
  'billed_amount': 75636.36,
  'approved_amount': 20515.56,
  'claim_status': 'Pending',
  'payment_days': nan,
  'billing_date': '2025-11-18'},
 {'bill_id': 12,
  'visit_id': 12,
  'billed_amount': 27143.29,
  'approved_amount': 26404.71,
  'claim_status': 'Paid',
  'payment_days': 26.0,
  'billing_date': '2025-07-08'},
 {'bill_id': 13,
  'visit_id': 13,
  'billed_amount': 88539.01,
  'approved_amount': nan,
  'claim_status': 'Pending',
  'payment_days': nan,
  'billing_date': '2026-01-11'},
 {'bill_id': 14,
  'visit_id': 14,
  'billed_amount': 88539.01,
  'approved_amount': 82492.35,
  'claim_status': 'Paid',
  'payment_days': 10.0,
  'billing_date': '2025-04-22'},
 {'bill_id': 15,
  'visit_id': 15,
  'billed_amount': 15270.1,
  'approved_amount': 13684.78,
  'claim_status': 'Paid',
  'payment_days': 43.0,
  'billing_date': '2025-10-03'},
 {'bill_id': 16,
  'visit_id': 16,
  'billed_amount': 52792.35,
  'approved_amount': 52220.55,
  'claim_status': 'Paid',
  'payment_days': 26.0,
  'billing_date': '2025-05-18'},
 {'bill_id': 17,
  'visit_id': 17,
  'billed_amount': 16983.11,
  'approved_amount': nan,
  'claim_status': 'Rejected',
  'payment_days': nan,
  'billing_date': '2025-07-13'},
 {'bill_id': 18,
  'visit_id': 18,
  'billed_amount': 56745.53,
  'approved_amount': nan,
  'claim_status': 'Rejected',
  'payment_days': nan,
  'billing_date': '2025-09-16'},
 {'bill_id': 19,
  'visit_id': 19,
  'billed_amount': 88539.01,
  'approved_amount': nan,
  'claim_status': 'Rejected',
  'payment_days': nan,
  'billing_date': '2025-11-13'},
 {'bill_id': 20,
  'visit_id': 20,
  'billed_amount': 35961.09,
  'approved_amount': 4197.42,
  'claim_status': 'Rejected',
  'payment_days': nan,
  'billing_date': '2026-01-09'},
 {'bill_id': 21,
  'visit_id': 21,
  'billed_amount': 88539.01,
  'approved_amount': 4852.22,
  'claim_status': 'Rejected',
  'payment_days': nan,
  'billing_date': '2025-03-29'},
 {'bill_id': 22,
  'visit_id': 22,
  'billed_amount': 22128.13,
  'approved_amount': 20304.98,
  'claim_status': 'Paid',
  'payment_days': 35.0,
  'billing_date': '2025-07-29'},
 {'bill_id': 23,
  'visit_id': 23,
  'billed_amount': 88539.01,
  'approved_amount': nan,
  'claim_status': 'Pending',
  'payment_days': nan,
  'billing_date': '2025-09-24'},
 {'bill_id': 24,
  'visit_id': 24,
  'billed_amount': 88539.01,
  'approved_amount': 3845.92,
  'claim_status': 'Rejected',
  'payment_days': nan,
  'billing_date': '2025-08-31'},
 {'bill_id': 25,
  'visit_id': 25,
  'billed_amount': 26042.55,
  'approved_amount': 22346.83,
  'claim_status': 'Paid',
  'payment_days': 20.0,
  'billing_date': '2025-10-23'},
 {'bill_id': 26,
  'visit_id': 26,
  'billed_amount': 36895.37,
  'approved_amount': 36266.54,
  'claim_status': 'Paid',
  'payment_days': 33.0,
  'billing_date': '2025-03-17'},
 {'bill_id': 27,
  'visit_id': 27,
  'billed_amount': 88539.01,
  'approved_amount': nan,
  'claim_status': 'Pending',
  'payment_days': nan,
  'billing_date': '2025-08-08'},
 {'bill_id': 28,
  'visit_id': 28,
  'billed_amount': 35535.64,
  'approved_amount': 32660.21,
  'claim_status': 'Paid',
  'payment_days': 26.0,
  'billing_date': '2025-07-05'},
 {'bill_id': 29,
  'visit_id': 29,
  'billed_amount': 8684.68,
  'approved_amount': 7537.64,
  'claim_status': 'Paid',
  'payment_days': 10.0,
  'billing_date': '2025-11-01'},
 {'bill_id': 30,
  'visit_id': 30,
  'billed_amount': 13732.33,
  'approved_amount': 12507.77,
  'claim_status': 'Paid',
  'payment_days': 25.0,
  'billing_date': '2025-07-03'},
 {'bill_id': 31,
  'visit_id': 31,
  'billed_amount': 84216.42,
  'approved_amount': 37359.34,
  'claim_status': 'Pending',
  'payment_days': nan,
  'billing_date': '2025-10-25'},
 {'bill_id': 32,
  'visit_id': 32,
  'billed_amount': 68049.65,
  'approved_amount': nan,
  'claim_status': 'Rejected',
  'payment_days': nan,
  'billing_date': '2025-04-04'},
 {'bill_id': 33,
  'visit_id': 33,
  'billed_amount': 13428.57,
  'approved_amount': 13122.58,
  'claim_status': 'Paid',
  'payment_days': 6.0,
  'billing_date': '2025-04-23'},
 {'bill_id': 34,
  'visit_id': 34,
  'billed_amount': 39442.34,
  'approved_amount': nan,
  'claim_status': 'Rejected',
  'payment_days': nan,
  'billing_date': '2026-01-12'},
 {'bill_id': 35,
  'visit_id': 35,
  'billed_amount': 13854.4,
  'approved_amount': 13477.47,
  'claim_status': 'Paid',
  'payment_days': 16.0,
  'billing_date': '2025-06-02'},
 {'bill_id': 36,
  'visit_id': 36,
  'billed_amount': 9673.38,
  'approved_amount': 8591.38,
  'claim_status': 'Paid',
  'payment_days': 35.0,
  'billing_date': '2025-10-25'},
 {'bill_id': 37,
  'visit_id': 37,
  'billed_amount': 11234.87,
  'approved_amount': 9892.48,
  'claim_status': 'Paid',
  'payment_days': 1.0,
  'billing_date': '2025-09-03'},
 {'bill_id': 38,
  'visit_id': 38,
  'billed_amount': 88539.01,
  'approved_amount': nan,
  'claim_status': 'Pending',
  'payment_days': 41.0,
  'billing_date': '2025-10-18'},
 {'bill_id': 39,
  'visit_id': 39,
  'billed_amount': 88539.01,
  'approved_amount': 77695.0,
  'claim_status': 'Paid',
  'payment_days': 34.0,
  'billing_date': '2025-08-15'},
 {'bill_id': 40,
  'visit_id': 40,
  'billed_amount': 20939.44,
  'approved_amount': 5096.46,
  'claim_status': 'Pending',
  'payment_days': nan,
  'billing_date': '2025-06-05'},
 {'bill_id': 41,
  'visit_id': 41,
  'billed_amount': 88539.01,
  'approved_amount': 86398.27,
  'claim_status': 'Paid',
  'payment_days': 42.0,
  'billing_date': '2025-09-16'},
 {'bill_id': 42,
  'visit_id': 42,
  'billed_amount': 64560.47,
  'approved_amount': 64200.54,
  'claim_status': 'Paid',
  'payment_days': 21.0,
  'billing_date': '2025-04-21'},
 {'bill_id': 43,
  'visit_id': 43,
  'billed_amount': 43137.01,
  'approved_amount': 39102.4,
  'claim_status': 'Paid',
  'payment_days': 49.0,
  'billing_date': '2025-11-26'},
 {'bill_id': 44,
  'visit_id': 44,
  'billed_amount': 88539.01,
  'approved_amount': 81942.35,
  'claim_status': 'Paid',
  'payment_days': 20.0,
  'billing_date': '2026-01-20'},
 {'bill_id': 45,
  'visit_id': 45,
  'billed_amount': 88539.01,
  'approved_amount': 82220.37,
  'claim_status': 'Paid',
  'payment_days': 19.0,
  'billing_date': '2025-05-05'},
 {'bill_id': 46,
  'visit_id': 46,
  'billed_amount': 88539.01,
  'approved_amount': nan,
  'claim_status': 'Pending',
  'payment_days': nan,
  'billing_date': '2025-09-19'},
 {'bill_id': 47,
  'visit_id': 47,
  'billed_amount': 19653.25,
  'approved_amount': nan,
  'claim_status': 'Pending',
  'payment_days': 46.0,
  'billing_date': '2025-12-05'},
 {'bill_id': 48,
  'visit_id': 48,
  'billed_amount': 88539.01,
  'approved_amount': 12255.31,
  'claim_status': 'Pending',
  'payment_days': nan,
  'billing_date': '2025-12-24'},
 {'bill_id': 49,
  'visit_id': 49,
  'billed_amount': 43710.5,
  'approved_amount': 40189.95,
  'claim_status': 'Paid',
  'payment_days': 6.0,
  'billing_date': '2025-09-16'},
 {'bill_id': 50,
  'visit_id': 50,
  'billed_amount': 16615.07,
  'approved_amount': 16474.11,
  'claim_status': 'Paid',
  'payment_days': 47.0,
  'billing_date': '2025-11-15'},
 {'bill_id': 51,
  'visit_id': 51,
  'billed_amount': 4491.6,
  'approved_amount': nan,
  'claim_status': 'Pending',
  'payment_days': nan,
  'billing_date': '2025-07-25'},
 {'bill_id': 52,
  'visit_id': 52,
  'billed_amount': 39407.74,
  'approved_amount': nan,
  'claim_status': 'Pending',
  'payment_days': nan,
  'billing_date': '2025-08-25'},
 {'bill_id': 53,
  'visit_id': 53,
  'billed_amount': 29059.39,
  'approved_amount': 24914.19,
  'claim_status': 'Paid',
  'payment_days': 2.0,
  'billing_date': '2026-01-02'},
 {'bill_id': 54,
  'visit_id': 54,
  'billed_amount': 16769.43,
  'approved_amount': 4251.49,
  'claim_status': 'Pending',
  'payment_days': nan,
  'billing_date': '2025-04-25'},
 {'bill_id': 55,
  'visit_id': 55,
  'billed_amount': 15352.55,
  'approved_amount': 13650.58,
  'claim_status': 'Paid',
  'payment_days': 43.0,
  'billing_date': '2026-01-20'},
 {'bill_id': 56,
  'visit_id': 56,
  'billed_amount': 58191.91,
  'approved_amount': 55124.07,
  'claim_status': 'Paid',
  'payment_days': 49.0,
  'billing_date': '2025-11-30'},
 {'bill_id': 57,
  'visit_id': 57,
  'billed_amount': 15144.38,
  'approved_amount': 14966.95,
  'claim_status': 'Paid',
  'payment_days': 14.0,
  'billing_date': '2026-01-20'},
 {'bill_id': 58,
  'visit_id': 58,
  'billed_amount': 6447.02,
  'approved_amount': 5680.51,
  'claim_status': 'Paid',
  'payment_days': 8.0,
  'billing_date': '2025-07-01'},
 {'bill_id': 59,
  'visit_id': 59,
  'billed_amount': 28166.31,
  'approved_amount': 26809.72,
  'claim_status': 'Paid',
  'payment_days': 39.0,
  'billing_date': '2025-11-08'},
 {'bill_id': 60,
  'visit_id': 60,
  'billed_amount': 4791.75,
  'approved_amount': 4766.2,
  'claim_status': 'Paid',
  'payment_days': 47.0,
  'billing_date': '2025-04-16'},
 {'bill_id': 61,
  'visit_id': 61,
  'billed_amount': 38304.24,
  'approved_amount': 33428.53,
  'claim_status': 'Paid',
  'payment_days': 5.0,
  'billing_date': '2026-01-04'},
 {'bill_id': 62,
  'visit_id': 62,
  'billed_amount': 11212.33,
  'approved_amount': 11001.05,
  'claim_status': 'Paid',
  'payment_days': 9.0,
  'billing_date': '2025-10-23'},
 {'bill_id': 63,
  'visit_id': 63,
  'billed_amount': 61707.55,
  'approved_amount': 56836.95,
  'claim_status': 'Paid',
  'payment_days': 16.0,
  'billing_date': '2025-10-14'},
 {'bill_id': 64,
  'visit_id': 64,
  'billed_amount': 4403.76,
  'approved_amount': nan,
  'claim_status': 'Pending',
  'payment_days': nan,
  'billing_date': '2025-11-03'},
 {'bill_id': 65,
  'visit_id': 65,
  'billed_amount': 88539.01,
  'approved_amount': nan,
  'claim_status': 'Rejected',
  'payment_days': nan,
  'billing_date': '2026-01-05'},
 {'bill_id': 66,
  'visit_id': 66,
  'billed_amount': 43641.75,
  'approved_amount': 1464.39,
  'claim_status': 'Pending',
  'payment_days': nan,
  'billing_date': '2025-09-27'},
 {'bill_id': 67,
  'visit_id': 67,
  'billed_amount': 16959.12,
  'approved_amount': 16322.5,
  'claim_status': 'Paid',
  'payment_days': 29.0,
  'billing_date': '2026-01-20'},
 {'bill_id': 68,
  'visit_id': 68,
  'billed_amount': 10170.19,
  'approved_amount': 9038.76,
  'claim_status': 'Paid',
  'payment_days': 31.0,
  'billing_date': '2025-09-14'},
 {'bill_id': 69,
  'visit_id': 69,
  'billed_amount': 3814.08,
  'approved_amount': 3712.85,
  'claim_status': 'Paid',
  'payment_days': 11.0,
  'billing_date': '2025-12-26'},
 {'bill_id': 70,
  'visit_id': 70,
  'billed_amount': 16835.18,
  'approved_amount': nan,
  'claim_status': 'Rejected',
  'payment_days': nan,
  'billing_date': '2025-11-10'},
 {'bill_id': 71,
  'visit_id': 71,
  'billed_amount': 10445.22,
  'approved_amount': 10197.07,
  'claim_status': 'Paid',
  'payment_days': 18.0,
  'billing_date': '2025-12-01'},
 {'bill_id': 72,
  'visit_id': 72,
  'billed_amount': 19472.2,
  'approved_amount': 19168.21,
  'claim_status': 'Paid',
  'payment_days': 47.0,
  'billing_date': '2025-10-14'},
 {'bill_id': 73,
  'visit_id': 73,
  'billed_amount': 54044.91,
  'approved_amount': 49182.24,
  'claim_status': 'Paid',
  'payment_days': 54.0,
  'billing_date': '2025-11-01'},
 {'bill_id': 74,
  'visit_id': 74,
  'billed_amount': 9893.38,
  'approved_amount': 8926.67,
  'claim_status': 'Paid',
  'payment_days': 28.0,
  'billing_date': '2025-10-25'},
 {'bill_id': 75,
  'visit_id': 75,
  'billed_amount': 14128.44,
  'approved_amount': 626.47,
  'claim_status': 'Pending',
  'payment_days': nan,
  'billing_date': '2025-10-31'},
 {'bill_id': 76,
  'visit_id': 76,
  'billed_amount': 12037.92,
  'approved_amount': 11348.25,
  'claim_status': 'Paid',
  'payment_days': 44.0,
  'billing_date': '2025-07-31'},
 {'bill_id': 77,
  'visit_id': 77,
  'billed_amount': 88539.01,
  'approved_amount': 39819.39,
  'claim_status': 'Pending',
  'payment_days': 49.0,
  'billing_date': '2025-12-20'},
 {'bill_id': 78,
  'visit_id': 78,
  'billed_amount': 500.0,
  'approved_amount': 475.01,
  'claim_status': 'Paid',
  'payment_days': 53.0,
  'billing_date': '2025-06-15'},
 {'bill_id': 79,
  'visit_id': 79,
  'billed_amount': 13063.27,
  'approved_amount': 434.45,
  'claim_status': 'Rejected',
  'payment_days': nan,
  'billing_date': '2025-08-06'},
 {'bill_id': 80,
  'visit_id': 80,
  'billed_amount': 20769.99,
  'approved_amount': 17878.76,
  'claim_status': 'Paid',
  'payment_days': 28.0,
  'billing_date': '2025-08-16'},
 {'bill_id': 81,
  'visit_id': 81,
  'billed_amount': 5479.72,
  'approved_amount': 89.14,
  'claim_status': 'Rejected',
  'payment_days': nan,
  'billing_date': '2025-06-30'},
 {'bill_id': 82,
  'visit_id': 82,
  'billed_amount': 5757.61,
  'approved_amount': nan,
  'claim_status': 'Pending',
  'payment_days': nan,
  'billing_date': '2026-01-20'},
 {'bill_id': 83,
  'visit_id': 83,
  'billed_amount': 67337.51,
  'approved_amount': 58390.05,
  'claim_status': 'Paid',
  'payment_days': 9.0,
  'billing_date': '2025-07-12'},
 {'bill_id': 84,
  'visit_id': 84,
  'billed_amount': 14461.37,
  'approved_amount': nan,
  'claim_status': 'Pending',
  'payment_days': nan,
  'billing_date': '2025-10-25'},
 {'bill_id': 85,
  'visit_id': 85,
  'billed_amount': 43217.65,
  'approved_amount': 37815.17,
  'claim_status': 'Paid',
  'payment_days': 35.0,
  'billing_date': '2025-07-01'},
 {'bill_id': 86,
  'visit_id': 86,
  'billed_amount': 9830.13,
  'approved_amount': nan,
  'claim_status': 'Rejected',
  'payment_days': nan,
  'billing_date': '2025-08-17'},
 {'bill_id': 87,
  'visit_id': 87,
  'billed_amount': 15400.51,
  'approved_amount': nan,
  'claim_status': 'Rejected',
  'payment_days': nan,
  'billing_date': '2026-01-01'},
 {'bill_id': 88,
  'visit_id': 88,
  'billed_amount': 35466.63,
  'approved_amount': 3783.34,
  'claim_status': 'Rejected',
  'payment_days': nan,
  'billing_date': '2026-01-18'},
 {'bill_id': 89,
  'visit_id': 89,
  'billed_amount': 21261.9,
  'approved_amount': 18366.53,
  'claim_status': 'Paid',
  'payment_days': 49.0,
  'billing_date': '2025-12-15'},
 {'bill_id': 90,
  'visit_id': 90,
  'billed_amount': 42446.51,
  'approved_amount': 36685.95,
  'claim_status': 'Paid',
  'payment_days': 53.0,
  'billing_date': '2025-11-24'},
 {'bill_id': 91,
  'visit_id': 91,
  'billed_amount': 35434.73,
  'approved_amount': 35351.15,
  'claim_status': 'Paid',
  'payment_days': 53.0,
  'billing_date': '2025-12-31'},
 {'bill_id': 92,
  'visit_id': 92,
  'billed_amount': 31885.97,
  'approved_amount': 28177.99,
  'claim_status': 'Paid',
  'payment_days': 17.0,
  'billing_date': '2026-01-20'},
 {'bill_id': 93,
  'visit_id': 93,
  'billed_amount': 8827.05,
  'approved_amount': nan,
  'claim_status': 'Rejected',
  'payment_days': nan,
  'billing_date': '2026-01-20'},
 {'bill_id': 94,
  'visit_id': 94,
  'billed_amount': 4084.47,
  'approved_amount': 3911.1,
  'claim_status': 'Paid',
  'payment_days': 26.0,
  'billing_date': '2026-01-20'},
 {'bill_id': 95,
  'visit_id': 95,
  'billed_amount': 14240.18,
  'approved_amount': 13148.95,
  'claim_status': 'Paid',
  'payment_days': 12.0,
  'billing_date': '2025-09-04'},
 {'bill_id': 96,
  'visit_id': 96,
  'billed_amount': 30000.11,
  'approved_amount': 27621.55,
  'claim_status': 'Paid',
  'payment_days': 1.0,
  'billing_date': '2025-09-23'},
 {'bill_id': 97,
  'visit_id': 97,
  'billed_amount': 88539.01,
  'approved_amount': 75334.89,
  'claim_status': 'Paid',
  'payment_days': 4.0,
  'billing_date': '2025-09-27'},
 {'bill_id': 98,
  'visit_id': 98,
  'billed_amount': 40143.82,
  'approved_amount': nan,
  'claim_status': 'Pending',
  'payment_days': nan,
  'billing_date': '2025-09-12'},
 {'bill_id': 99,
  'visit_id': 99,
  'billed_amount': 37359.58,
  'approved_amount': 33508.58,
  'claim_status': 'Paid',
  'payment_days': 29.0,
  'billing_date': '2025-11-18'},
 {'bill_id': 100,
  'visit_id': 100,
  'billed_amount': 46234.53,
  'approved_amount': nan,
  'claim_status': 'Pending',
  'payment_days': 36.0,
  'billing_date': '2025-10-19'},
 {'bill_id': 101,
  'visit_id': 101,
  'billed_amount': 88539.01,
  'approved_amount': 87495.97,
  'claim_status': 'Paid',
  'payment_days': 6.0,
  'billing_date': '2025-07-18'},
 {'bill_id': 102,
  'visit_id': 102,
  'billed_amount': 6908.05,
  'approved_amount': 6121.56,
  'claim_status': 'Paid',
  'payment_days': 10.0,
  'billing_date': '2025-09-23'},
 {'bill_id': 103,
  'visit_id': 103,
  'billed_amount': 13691.76,
  'approved_amount': 359.23,
  'claim_status': 'Rejected',
  'payment_days': nan,
  'billing_date': '2025-10-14'},
 {'bill_id': 104,
  'visit_id': 104,
  'billed_amount': 26404.54,
  'approved_amount': 26121.9,
  'claim_status': 'Paid',
  'payment_days': 36.0,
  'billing_date': '2026-01-18'},
 {'bill_id': 105,
  'visit_id': 105,
  'billed_amount': 10744.76,
  'approved_amount': 9967.18,
  'claim_status': 'Paid',
  'payment_days': 42.0,
  'billing_date': '2025-07-22'},
 {'bill_id': 106,
  'visit_id': 106,
  'billed_amount': 10318.61,
  'approved_amount': nan,
  'claim_status': 'Rejected',
  'payment_days': nan,
  'billing_date': '2025-11-20'},
 {'bill_id': 107,
  'visit_id': 107,
  'billed_amount': 6526.8,
  'approved_amount': 5990.88,
  'claim_status': 'Paid',
  'payment_days': 25.0,
  'billing_date': '2025-10-12'},
 {'bill_id': 108,
  'visit_id': 108,
  'billed_amount': 88539.01,
  'approved_amount': nan,
  'claim_status': 'Pending',
  'payment_days': nan,
  'billing_date': '2025-05-27'},
 {'bill_id': 109,
  'visit_id': 109,
  'billed_amount': 42445.99,
  'approved_amount': 40173.54,
  'claim_status': 'Paid',
  'payment_days': 10.0,
  'billing_date': '2025-11-30'},
 {'bill_id': 110,
  'visit_id': 110,
  'billed_amount': 4109.6,
  'approved_amount': 3561.57,
  'claim_status': 'Paid',
  'payment_days': 24.0,
  'billing_date': '2025-09-24'},
 {'bill_id': 111,
  'visit_id': 111,
  'billed_amount': 1461.78,
  'approved_amount': 1444.76,
  'claim_status': 'Paid',
  'payment_days': 50.0,
  'billing_date': '2026-01-11'},
 {'bill_id': 112,
  'visit_id': 112,
  'billed_amount': 19810.18,
  'approved_amount': 17249.76,
  'claim_status': 'Paid',
  'payment_days': 8.0,
  'billing_date': '2025-08-12'},
 {'bill_id': 113,
  'visit_id': 113,
  'billed_amount': 11112.39,
  'approved_amount': 11070.35,
  'claim_status': 'Paid',
  'payment_days': 45.0,

In [51]:
len(billing_data)

25000

In [52]:
visits_data= visits.to_dict(orient="records")
visits_data

[{'visit_id': 1,
  'patient_id': 1,
  'visit_date': '10/16/2025',
  'department': 'Cardiology',
  'visit_type': 'OPD',
  'length_of_stay_hours': 23.15,
  'risk_score': 'Low',
  'doctor_id': 186},
 {'visit_id': 2,
  'patient_id': 1,
  'visit_date': '12/9/2025',
  'department': 'ICU',
  'visit_type': 'ICU',
  'length_of_stay_hours': 39.98,
  'risk_score': 'High',
  'doctor_id': 149},
 {'visit_id': 3,
  'patient_id': 1,
  'visit_date': '10/29/2025',
  'department': 'ER',
  'visit_type': 'ER',
  'length_of_stay_hours': 20.97,
  'risk_score': 'Medium',
  'doctor_id': 122},
 {'visit_id': 4,
  'patient_id': 1,
  'visit_date': '7/31/2025',
  'department': 'ER',
  'visit_type': 'ER',
  'length_of_stay_hours': 8.32,
  'risk_score': 'Medium',
  'doctor_id': 193},
 {'visit_id': 5,
  'patient_id': 1,
  'visit_date': '8/2/2025',
  'department': 'ICU',
  'visit_type': 'ICU',
  'length_of_stay_hours': 41.43,
  'risk_score': 'High',
  'doctor_id': 141},
 {'visit_id': 6,
  'patient_id': 1,
  'visit_date': '9/19/2025',
  'department': 'ER',
  'visit_type': 'ER',
  'length_of_stay_hours': 11.72,
  'risk_score': 'Medium',
  'doctor_id': 109},
 {'visit_id': 7,
  'patient_id': 2,
  'visit_date': '1/2/2026',
  'department': 'ER',
  'visit_type': 'ICU',
  'length_of_stay_hours': 4.46,
  'risk_score': 'Medium',
  'doctor_id': 131},
 {'visit_id': 8,
  'patient_id': 2,
  'visit_date': '1/1/2026',
  'department': 'General',
  'visit_type': 'OPD',
  'length_of_stay_hours': 9.63,
  'risk_score': 'Low',
  'doctor_id': 105},
 {'visit_id': 9,
  'patient_id': 2,
  'visit_date': '1/10/2026',
  'department': 'Orthopedics',
  'visit_type': 'OPD',
  'length_of_stay_hours': 29.05,
  'risk_score': 'Low',
  'doctor_id': 142},
 {'visit_id': 10,
  'patient_id': 2,
  'visit_date': '1/19/2026',
  'department': 'Neurology',
  'visit_type': 'OPD',
  'length_of_stay_hours': 41.34,
  'risk_score': 'Low',
  'doctor_id': 195},
 {'visit_id': 11,
  'patient_id': 3,
  'visit_date': '11/6/2025',
  'department': 'Neurology',
  'visit_type': 'ICU',
  'length_of_stay_hours': 35.86,
  'risk_score': 'High',
  'doctor_id': 111},
 {'visit_id': 12,
  'patient_id': 3,
  'visit_date': '6/21/2025',
  'department': 'Orthopedics',
  'visit_type': 'OPD',
  'length_of_stay_hours': 23.16,
  'risk_score': 'Medium',
  'doctor_id': 180},
 {'visit_id': 13,
  'patient_id': 3,
  'visit_date': '12/13/2025',
  'department': 'ICU',
  'visit_type': 'ICU',
  'length_of_stay_hours': 76.46,
  'risk_score': 'High',
  'doctor_id': 153},
 {'visit_id': 14,
  'patient_id': 3,
  'visit_date': '4/8/2025',
  'department': 'ICU',
  'visit_type': 'ICU',
  'length_of_stay_hours': 73.59,
  'risk_score': 'High',
  'doctor_id': 197},
 {'visit_id': 15,
  'patient_id': 4,
  'visit_date': '9/11/2025',
  'department': 'ER',
  'visit_type': 'OPD',
  'length_of_stay_hours': 11.8,
  'risk_score': 'Low',
  'doctor_id': 102},
 {'visit_id': 16,
  'patient_id': 4,
  'visit_date': '4/25/2025',
  'department': 'Neurology',
  'visit_type': 'ICU',
  'length_of_stay_hours': 34.39,
  'risk_score': 'High',
  'doctor_id': 178},
 {'visit_id': 17,
  'patient_id': 4,
  'visit_date': '6/17/2025',
  'department': 'General',
  'visit_type': 'ER',
  'length_of_stay_hours': 20.16,
  'risk_score': 'Medium',
  'doctor_id': 122},
 {'visit_id': 18,
  'patient_id': 4,
  'visit_date': '8/24/2025',
  'department': 'Cardiology',
  'visit_type': 'OPD',
  'length_of_stay_hours': 37.91,
  'risk_score': 'Medium',
  'doctor_id': 153},
 {'visit_id': 19,
  'patient_id': 4,
  'visit_date': '11/12/2025',
  'department': 'ICU',
  'visit_type': 'ICU',
  'length_of_stay_hours': 65.1,
  'risk_score': 'High',
  'doctor_id': 175},
 {'visit_id': 20,
  'patient_id': 4,
  'visit_date': '12/12/2025',
  'department': 'Neurology',
  'visit_type': 'OPD',
  'length_of_stay_hours': 28.95,
  'risk_score': 'Medium',
  'doctor_id': 184},
 {'visit_id': 21,
  'patient_id': 4,
  'visit_date': '3/24/2025',
  'department': 'ICU',
  'visit_type': 'ICU',
  'length_of_stay_hours': 52.76,
  'risk_score': 'High',
  'doctor_id': 139},
 {'visit_id': 22,
  'patient_id': 5,
  'visit_date': '7/5/2025',
  'department': 'ER',
  'visit_type': 'ER',
  'length_of_stay_hours': 17.88,
  'risk_score': 'Medium',
  'doctor_id': 186},
 {'visit_id': 23,
  'patient_id': 5,
  'visit_date': '8/26/2025',
  'department': 'ICU',
  'visit_type': 'ICU',
  'length_of_stay_hours': 66.89,
  'risk_score': 'High',
  'doctor_id': 147},
 {'visit_id': 24,
  'patient_id': 5,
  'visit_date': '8/26/2025',
  'department': 'ICU',
  'visit_type': 'ICU',
  'length_of_stay_hours': 72.31,
  'risk_score': 'High',
  'doctor_id': 128},
 {'visit_id': 25,
  'patient_id': 6,
  'visit_date': '10/10/2025',
  'department': 'Orthopedics',
  'visit_type': 'ER',
  'length_of_stay_hours': 16.88,
  'risk_score': 'Medium',
  'doctor_id': 187},
 {'visit_id': 26,
  'patient_id': 6,
  'visit_date': '2/20/2025',
  'department': 'Orthopedics',
  'visit_type': 'OPD',
  'length_of_stay_hours': 30.2,
  'risk_score': 'Low',
  'doctor_id': 110},
 {'visit_id': 27,
  'patient_id': 6,
  'visit_date': '7/16/2025',
  'department': 'ICU',
  'visit_type': 'ICU',
  'length_of_stay_hours': 64.51,
  'risk_score': 'High',
  'doctor_id': 198},
 {'visit_id': 28,
  'patient_id': 6,
  'visit_date': '7/2/2025',
  'department': 'Cardiology',
  'visit_type': 'OPD',
  'length_of_stay_hours': 21.23,
  'risk_score': 'Medium',
  'doctor_id': 110},
 {'visit_id': 29,
  'patient_id': 7,
  'visit_date': '10/4/2025',
  'department': 'ER',
  'visit_type': 'OPD',
  'length_of_stay_hours': 6.82,
  'risk_score': 'Low',
  'doctor_id': 144},
 {'visit_id': 30,
  'patient_id': 7,
  'visit_date': '6/18/2025',
  'department': 'General',
  'visit_type': 'OPD',
  'length_of_stay_hours': 13.16,
  'risk_score': 'Low',
  'doctor_id': 190},
 {'visit_id': 31,
  'patient_id': 7,
  'visit_date': '10/5/2025',
  'department': 'Cardiology',
  'visit_type': 'ER',
  'length_of_stay_hours': 35.63,
  'risk_score': 'Medium',
  'doctor_id': 145},
 {'visit_id': 32,
  'patient_id': 7,
  'visit_date': '3/10/2025',
  'department': 'Cardiology',
  'visit_type': 'OPD',
  'length_of_stay_hours': 50.98,
  'risk_score': 'Medium',
  'doctor_id': 181},
 {'visit_id': 33,
  'patient_id': 7,
  'visit_date': '3/31/2025',
  'department': 'ER',
  'visit_type': 'OPD',
  'length_of_stay_hours': 11.56,
  'risk_score': 'Low',
  'doctor_id': 161},
 {'visit_id': 34,
  'patient_id': 7,
  'visit_date': '12/27/2025',
  'department': 'Orthopedics',
  'visit_type': 'ER',
  'length_of_stay_hours': 30.18,
  'risk_score': 'Medium',
  'doctor_id': 146},
 {'visit_id': 35,
  'patient_id': 8,
  'visit_date': '5/26/2025',
  'department': 'ER',
  'visit_type': 'OPD',
  'length_of_stay_hours': 12.06,
  'risk_score': 'Low',
  'doctor_id': 180},
 {'visit_id': 36,
  'patient_id': 8,
  'visit_date': '10/23/2025',
  'department': 'General',
  'visit_type': 'OPD',
  'length_of_stay_hours': 10.95,
  'risk_score': 'Low',
  'doctor_id': 101},
 {'visit_id': 37,
  'patient_id': 8,
  'visit_date': '8/24/2025',
  'department': 'General',
  'visit_type': 'OPD',
  'length_of_stay_hours': 11.05,
  'risk_score': 'Low',
  'doctor_id': 126},
 {'visit_id': 38,
  'patient_id': 9,
  'visit_date': '10/17/2025',
  'department': 'ICU',
  'visit_type': 'ICU',
  'length_of_stay_hours': 73.67,
  'risk_score': 'High',
  'doctor_id': 192},
 {'visit_id': 39,
  'patient_id': 9,
  'visit_date': '8/14/2025',
  'department': 'ICU',
  'visit_type': 'ICU',
  'length_of_stay_hours': 69.01,
  'risk_score': 'High',
  'doctor_id': 122},
 {'visit_id': 40,
  'patient_id': 9,
  'visit_date': '5/29/2025',
  'department': 'ER',
  'visit_type': 'ER',
  'length_of_stay_hours': 18.53,
  'risk_score': 'Medium',
  'doctor_id': 170},
 {'visit_id': 41,
  'patient_id': 9,
  'visit_date': '8/27/2025',
  'department': 'ICU',
  'visit_type': 'OPD',
  'length_of_stay_hours': 78.42,
  'risk_score': 'High',
  'doctor_id': 156},
 {'visit_id': 42,
  'patient_id': 9,
  'visit_date': '4/3/2025',
  'department': 'Cardiology',
  'visit_type': 'ER',
  'length_of_stay_hours': 29.46,
  'risk_score': 'High',
  'doctor_id': 194},
 {'visit_id': 43,
  'patient_id': 9,
  'visit_date': '11/14/2025',
  'department': 'Cardiology',
  'visit_type': 'ER',
  'length_of_stay_hours': 26.24,
  'risk_score': 'High',
  'doctor_id': 171},
 {'visit_id': 44,
  'patient_id': 9,
  'visit_date': '1/6/2026',
  'department': 'ICU',
  'visit_type': 'ICU',
  'length_of_stay_hours': 75.09,
  'risk_score': 'High',
  'doctor_id': 175},
 {'visit_id': 45,
  'patient_id': 9,
  'visit_date': '4/12/2025',
  'department': 'ICU',
  'visit_type': 'ICU',
  'length_of_stay_hours': 43.25,
  'risk_score': 'High',
  'doctor_id': 135},
 {'visit_id': 46,
  'patient_id': 9,
  'visit_date': '9/8/2025',
  'department': 'ICU',
  'visit_type': 'ICU',
  'length_of_stay_hours': 78.42,
  'risk_score': 'High',
  'doctor_id': 158},
 {'visit_id': 47,
  'patient_id': 9,
  'visit_date': '11/16/2025',
  'department': 'ER',
  'visit_type': 'OPD',
  'length_of_stay_hours': 16.32,
  'risk_score': 'Medium',
  'doctor_id': 121},
 {'visit_id': 48,
  'patient_id': 10,
  'visit_date': '12/19/2025',
  'department': 'ICU',
  'visit_type': 'ICU',
  'length_of_stay_hours': 52.44,
  'risk_score': 'High',
  'doctor_id': 146},
 {'visit_id': 49,
  'patient_id': 10,
  'visit_date': '9/6/2025',
  'department': 'Orthopedics',
  'visit_type': 'OPD',
  'length_of_stay_hours': 35.55,
  'risk_score': 'Low',
  'doctor_id': 102},
 {'visit_id': 50,
  'patient_id': 10,
  'visit_date': '10/18/2025',
  'department': 'General',
  'visit_type': 'OPD',
  'length_of_stay_hours': 20.65,
  'risk_score': 'Low',
  'doctor_id': 149},
 {'visit_id': 51,
  'patient_id': 10,
  'visit_date': '7/10/2025',
  'department': 'General',
  'visit_type': 'OPD',
  'length_of_stay_hours': 5.94,
  'risk_score': 'Low',
  'doctor_id': 138},
 {'visit_id': 52,
  'patient_id': 10,
  'visit_date': '8/8/2025',
  'department': 'Cardiology',
  'visit_type': 'OPD',
  'length_of_stay_hours': 24.27,
  'risk_score': 'Medium',
  'doctor_id': 164},
 {'visit_id': 53,
  'patient_id': 10,
  'visit_date': '12/18/2025',
  'department': 'Orthopedics',
  'visit_type': 'OPD',
  'length_of_stay_hours': 22.84,
  'risk_score': 'Low',
  'doctor_id': 157},
 {'visit_id': 54,
  'patient_id': 11,
  'visit_date': '4/4/2025',
  'department': 'Cardiology',
  'visit_type': 'OPD',
  'length_of_stay_hours': 9.51,
  'risk_score': 'Low',
  'doctor_id': 170},
 {'visit_id': 55,
  'patient_id': 11,
  'visit_date': '1/16/2026',
  'department': 'General',
  'visit_type': 'ER',
  'length_of_stay_hours': 18.73,
  'risk_score': 'Low',
  'doctor_id': 130},
 {'visit_id': 56,
  'patient_id': 11,
  'visit_date': '11/1/2025',
  'department': 'Cardiology',
  'visit_type': 'OPD',
  'length_of_stay_hours': 32.95,
  'risk_score': 'Low',
  'doctor_id': 180},
 {'visit_id': 57,
  'patient_id': 11,
  'visit_date': '1/16/2026',
  'department': 'Orthopedics',
  'visit_type': 'OPD',
  'length_of_stay_hours': 10.5,
  'risk_score': 'Low',
  'doctor_id': 154},
 {'visit_id': 58,
  'patient_id': 11,
  'visit_date': '6/19/2025',
  'department': 'ER',
  'visit_type': 'ER',
  'length_of_stay_hours': 4.96,
  'risk_score': 'Low',
  'doctor_id': 112},
 {'visit_id': 59,
  'patient_id': 11,
  'visit_date': '10/15/2025',
  'department': 'Orthopedics',
  'visit_type': 'OPD',
  'length_of_stay_hours': 15.93,
  'risk_score': 'Low',
  'doctor_id': 161},
 {'visit_id': 60,
  'patient_id': 11,
  'visit_date': '3/18/2025',
  'department': 'General',
  'visit_type': 'ER',
  'length_of_stay_hours': 4.35,
  'risk_score': 'Low',
  'doctor_id': 100},
 {'visit_id': 61,
  'patient_id': 11,
  'visit_date': '12/29/2025',
  'department': 'Neurology',
  'visit_type': 'OPD',
  'length_of_stay_hours': 25.39,
  'risk_score': 'Low',
  'doctor_id': 136},
 {'visit_id': 62,
  'patient_id': 11,
  'visit_date': '10/20/2025',
  'department': 'ER',
  'visit_type': 'OPD',
  'length_of_stay_hours': 11.06,
  'risk_score': 'Low',
  'doctor_id': 148},
 {'visit_id': 63,
  'patient_id': 12,
  'visit_date': '10/11/2025',
  'department': 'Cardiology',
  'visit_type': 'OPD',
  'length_of_stay_hours': 45.76,
  'risk_score': 'Low',
  'doctor_id': 146},
 {'visit_id': 64,
  'patient_id': 12,
  'visit_date': '10/27/2025',
  'department': 'General',
  'visit_type': 'OPD',
  'length_of_stay_hours': 3.98,
  'risk_score': 'Low',
  'doctor_id': 107},
 {'visit_id': 65,
  'patient_id': 12,
  'visit_date': '1/1/2026',
  'department': 'ICU',
  'visit_type': 'ICU',
  'length_of_stay_hours': 59.6,
  'risk_score': 'High',
  'doctor_id': 112},
 {'visit_id': 66,
  'patient_id': 12,
  'visit_date': '9/4/2025',
  'department': 'Neurology',
  'visit_type': 'OPD',
  'length_of_stay_hours': 28.26,
  'risk_score': 'Low',
  'doctor_id': 118},
 {'visit_id': 67,
  'patient_id': 12,
  'visit_date': '1/20/2026',
  'department': 'General',
  'visit_type': 'ER',
  'length_of_stay_hours': 19.09,
  'risk_score': 'Low',
  'doctor_id': 115},
 {'visit_id': 68,
  'patient_id': 12,
  'visit_date': '9/10/2025',
  'department': 'General',
  'visit_type': 'ER',
  'length_of_stay_hours': 10.43,
  'risk_score': 'Low',
  'doctor_id': 182},
 {'visit_id': 69,
  'patient_id': 12,
  'visit_date': '12/6/2025',
  'department': 'General',
  'visit_type': 'OPD',
  'length_of_stay_hours': 3.9,
  'risk_score': 'Low',
  'doctor_id': 128},
 {'visit_id': 70,
  'patient_id': 12,
  'visit_date': '11/3/2025',
  'department': 'General',
  'visit_type': 'OPD',
  'length_of_stay_hours': 18.98,
  'risk_score': 'Low',
  'doctor_id': 195},
 {'visit_id': 71,
  'patient_id': 13,
  'visit_date': '11/8/2025',
  'department': 'ER',
  'visit_type': 'OPD',
  'length_of_stay_hours': 8.43,
  'risk_score': 'Low',
  'doctor_id': 124},
 {'visit_id': 72,
  'patient_id': 13,
  'visit_date': '10/11/2025',
  'department': 'Cardiology',
  'visit_type': 'OPD',
  'length_of_stay_hours': 7.99,
  'risk_score': 'Low',
  'doctor_id': 149},
 {'visit_id': 73,
  'patient_id': 13,
  'visit_date': '10/27/2025',
  'department': 'Orthopedics',
  'visit_type': 'OPD',
  'length_of_stay_hours': 37.07,
  'risk_score': 'Low',
  'doctor_id': 174},
 {'visit_id': 74,
  'patient_id': 14,
  'visit_date': '10/4/2025',
  'department': 'General',
  'visit_type': 'OPD',
  'length_of_stay_hours': 9.74,
  'risk_score': 'Low',
  'doctor_id': 109},
 {'visit_id': 75,
  'patient_id': 14,
  'visit_date': '10/22/2025',
  'department': 'ER',
  'visit_type': 'OPD',
  'length_of_stay_hours': 11.43,
  'risk_score': 'Low',
  'doctor_id': 176},
 {'visit_id': 76,
  'patient_id': 14,
  'visit_date': '7/7/2025',
  'department': 'ER',
  'visit_type': 'ER',
  'length_of_stay_hours': 9.85,
  'risk_score': 'Low',
  'doctor_id': 185},
 {'visit_id': 77,
  'patient_id': 14,
  'visit_date': '12/12/2025',
  'department': 'ICU',
  'visit_type': 'ICU',
  'length_of_stay_hours': 34.09,
  'risk_score': 'High',
  'doctor_id': 156},
 {'visit_id': 78,
  'patient_id': 14,
  'visit_date': '6/5/2025',
  'department': 'General',
  'visit_type': 'OPD',
  'length_of_stay_hours': 0.5,
  'risk_score': 'Low',
  'doctor_id': 185},
 {'visit_id': 79,
  'patient_id': 15,
  'visit_date': '7/19/2025',
  'department': 'ER',
  'visit_type': 'OPD',
  'length_of_stay_hours': 9.83,
  'risk_score': 'Low',
  'doctor_id': 162},
 {'visit_id': 80,
  'patient_id': 15,
  'visit_date': '8/3/2025',
  'department': 'General',
  'visit_type': 'OPD',
  'length_of_stay_hours': 20.77,
  'risk_score': 'Low',
  'doctor_id': 167},
 {'visit_id': 81,
  'patient_id': 15,
  'visit_date': '6/3/2025',
  'department': 'ER',
  'visit_type': 'ER',
  'length_of_stay_hours': 4.68,
  'risk_score': 'Low',
  'doctor_id': 198},
 {'visit_id': 82,
  'patient_id': 15,
  'visit_date': '1/16/2026',
  'department': 'General',
  'visit_type': 'OPD',
  'length_of_stay_hours': 7.75,
  'risk_score': 'Low',
  'doctor_id': 197},
 {'visit_id': 83,
  'patient_id': 15,
  'visit_date': '6/16/2025',
  'department': 'Cardiology',
  'visit_type': 'ER',
  'length_of_stay_hours': 40.13,
  'risk_score': 'Medium',
  'doctor_id': 175},
 {'visit_id': 84,
  'patient_id': 15,
  'visit_date': '9/28/2025',
  'department': 'General',
  'visit_type': 'OPD',
  'length_of_stay_hours': 19.7,
  'risk_score': 'Low',
  'doctor_id': 198},
 {'visit_id': 85,
  'patient_id': 15,
  'visit_date': '6/23/2025',
  'department': 'Neurology',
  'visit_type': 'OPD',
  'length_of_stay_hours': 25.24,
  'risk_score': 'Low',
  'doctor_id': 130},
 {'visit_id': 86,
  'patient_id': 15,
  'visit_date': '8/11/2025',
  'department': 'General',
  'visit_type': 'OPD',
  'length_of_stay_hours': 13.36,
  'risk_score': 'Low',
  'doctor_id': 133},
 {'visit_id': 87,
  'patient_id': 16,
  'visit_date': '12/19/2025',
  'department': 'ER',
  'visit_type': 'OPD',
  'length_of_stay_hours': 11.19,
  'risk_score': 'Low',
  'doctor_id': 187},
 {'visit_id': 88,
  'patient_id': 16,
  'visit_date': '1/17/2026',
  'department': 'Orthopedics',
  'visit_type': 'OPD',
  'length_of_stay_hours': 20.6,
  'risk_score': 'Low',
  'doctor_id': 175},
 {'visit_id': 89,
  'patient_id': 16,
  'visit_date': '12/10/2025',
  'department': 'Cardiology',
  'visit_type': 'OPD',
  'length_of_stay_hours': 13.84,
  'risk_score': 'Medium',
  'doctor_id': 145},
 {'visit_id': 90,
  'patient_id': 16,
  'visit_date': '11/16/2025',
  'department': 'Orthopedics',
  'visit_type': 'OPD',
  'length_of_stay_hours': 28.2,
  'risk_score': 'Low',
  'doctor_id': 132},
 {'visit_id': 91,
  'patient_id': 16,
  'visit_date': '12/15/2025',
  'department': 'Cardiology',
  'visit_type': 'OPD',
  'length_of_stay_hours': 17.49,
  'risk_score': 'Medium',
  'doctor_id': 116},
 {'visit_id': 92,
  'patient_id': 17,
  'visit_date': '1/20/2026',
  'department': 'Orthopedics',
  'visit_type': 'OPD',
  'length_of_stay_hours': 19.23,
  'risk_score': 'Low',
  'doctor_id': 189},
 {'visit_id': 93,
  'patient_id': 17,
  'visit_date': '1/4/2026',
  'department': 'General',
  'visit_type': 'ICU',
  'length_of_stay_hours': 11.34,
  'risk_score': 'Low',
  'doctor_id': 195},
 {'visit_id': 94,
  'patient_id': 17,
  'visit_date': '1/2/2026',
  'department': 'General',
  'visit_type': 'OPD',
  'length_of_stay_hours': 4.27,
  'risk_score': 'Low',
  'doctor_id': 143},
 {'visit_id': 95,
  'patient_id': 18,
  'visit_date': '8/11/2025',
  'department': 'General',
  'visit_type': 'ER',
  'length_of_stay_hours': 18.08,
  'risk_score': 'Low',
  'doctor_id': 120},
 {'visit_id': 96,
  'patient_id': 18,
  'visit_date': '9/16/2025',
  'department': 'Neurology',
  'visit_type': 'OPD',
  'length_of_stay_hours': 25.58,
  'risk_score': 'Low',
  'doctor_id': 171},
 {'visit_id': 97,
  'patient_id': 18,
  'visit_date': '9/2/2025',
  'department': 'ICU',
  'visit_type': 'ICU',
  'length_of_stay_hours': 46.98,
  'risk_score': 'High',
  'doctor_id': 143},
 {'visit_id': 98,
  'patient_id': 19,
  'visit_date': '8/21/2025',
  'department': 'Orthopedics',
  'visit_type': 'OPD',
  'length_of_stay_hours': 31.53,
  'risk_score': 'Low',
  'doctor_id': 155},
 {'visit_id': 99,
  'patient_id': 19,
  'visit_date': '11/8/2025',
  'department': 'Orthopedics',
  'visit_type': 'ER',
  'length_of_stay_hours': 23.04,
  'risk_score': 'Medium',
  'doctor_id': 148},
 {'visit_id': 100,
  'patient_id': 19,
  'visit_date': '10/2/2025',
  'department': 'Orthopedics',
  'visit_type': 'ICU',
  'length_of_stay_hours': 27.02,
  'risk_score': 'High',
  'doctor_id': 123},
 {'visit_id': 101,
  'patient_id': 19,
  'visit_date': '7/13/2025',
  'department': 'ICU',
  'visit_type': 'ER',
  'length_of_stay_hours': 34.8,
  'risk_score': 'High',
  'doctor_id': 136},
 {'visit_id': 102,
  'patient_id': 19,
  'visit_date': '8/30/2025',
  'department': 'General',
  'visit_type': 'OPD',
  'length_of_stay_hours': 9.99,
  'risk_score': 'Low',
  'doctor_id': 175},
 {'visit_id': 103,
  'patient_id': 19,
  'visit_date': '9/18/2025',
  'department': 'General',
  'visit_type': 'OPD',
  'length_of_stay_hours': 12.58,
  'risk_score': 'Low',
  'doctor_id': 162},
 {'visit_id': 104,
  'patient_id': 19,
  'visit_date': '12/20/2025',

In [53]:
len(visits_data)

25000

In [54]:

patient_data= patient.to_dict(orient="records")
patient_data

[{'patient_id': 1,
  'age': 52,
  'gender': 'M',
  'city': 'Bangalore',
  'insurance_provider': 'CareOne',
  'chronic_flag': 1,
  'registration_date': '5/6/2025'},
 {'patient_id': 2,
  'age': 15,
  'gender': 'F',
  'city': 'Mumbai',
  'insurance_provider': 'CareOne',
  'chronic_flag': 0,
  'registration_date': '12/27/2025'},
 {'patient_id': 3,
  'age': 72,
  'gender': 'F',
  'city': 'Bangalore',
  'insurance_provider': 'SecureLife',
  'chronic_flag': 1,
  'registration_date': '1/28/2025'},
 {'patient_id': 4,
  'age': 61,
  'gender': 'M',
  'city': 'Mumbai',
  'insurance_provider': 'MediCareX',
  'chronic_flag': 1,
  'registration_date': '2/8/2025'},
 {'patient_id': 5,
  'age': 21,
  'gender': 'F',
  'city': 'Mumbai',
  'insurance_provider': 'CareOne',
  'chronic_flag': 1,
  'registration_date': '6/17/2025'},
 {'patient_id': 6,
  'age': 83,
  'gender': 'F',
  'city': 'Chennai',
  'insurance_provider': 'MediCareX',
  'chronic_flag': 0,
  'registration_date': '2/5/2025'},
 {'patient_id': 7,
  'age': 87,
  'gender': 'M',
  'city': 'Delhi',
  'insurance_provider': 'CareOne',
  'chronic_flag': 0,
  'registration_date': '1/31/2025'},
 {'patient_id': 8,
  'age': 75,
  'gender': 'F',
  'city': 'Hyderabad',
  'insurance_provider': 'HealthPlus',
  'chronic_flag': 0,
  'registration_date': '4/11/2025'},
 {'patient_id': 9,
  'age': 75,
  'gender': 'M',
  'city': 'Mumbai',
  'insurance_provider': 'HealthPlus',
  'chronic_flag': 1,
  'registration_date': '3/27/2025'},
 {'patient_id': 10,
  'age': 88,
  'gender': 'M',
  'city': 'Delhi',
  'insurance_provider': 'SecureLife',
  'chronic_flag': 0,
  'registration_date': '6/1/2025'},
 {'patient_id': 11,
  'age': 24,
  'gender': 'M',
  'city': 'Pune',
  'insurance_provider': 'HealthPlus',
  'chronic_flag': 0,
  'registration_date': '3/13/2025'},
 {'patient_id': 12,
  'age': 3,
  'gender': 'M',
  'city': 'Bangalore',
  'insurance_provider': 'CareOne',
  'chronic_flag': 0,
  'registration_date': '8/13/2025'},
 {'patient_id': 13,
  'age': 22,
  'gender': 'M',
  'city': 'Pune',
  'insurance_provider': 'SecureLife',
  'chronic_flag': 0,
  'registration_date': '9/9/2025'},
 {'patient_id': 14,
  'age': 53,
  'gender': 'F',
  'city': 'Bangalore',
  'insurance_provider': 'SecureLife',
  'chronic_flag': 0,
  'registration_date': '3/14/2025'},
 {'patient_id': 15,
  'age': 2,
  'gender': 'M',
  'city': 'Chennai',
  'insurance_provider': 'HealthPlus',
  'chronic_flag': 0,
  'registration_date': '3/28/2025'},
 {'patient_id': 16,
  'age': 88,
  'gender': 'M',
  'city': 'Mumbai',
  'insurance_provider': 'MediCareX',
  'chronic_flag': 0,
  'registration_date': '11/6/2025'},
 {'patient_id': 17,
  'age': 30,
  'gender': 'M',
  'city': 'Hyderabad',
  'insurance_provider': 'HealthPlus',
  'chronic_flag': 0,
  'registration_date': '12/29/2025'},
 {'patient_id': 18,
  'age': 38,
  'gender': 'F',
  'city': 'Mumbai',
  'insurance_provider': 'HealthPlus',
  'chronic_flag': 0,
  'registration_date': '7/7/2025'},
 {'patient_id': 19,
  'age': 2,
  'gender': 'F',
  'city': 'Bangalore',
  'insurance_provider': 'SecureLife',
  'chronic_flag': 1,
  'registration_date': '6/29/2025'},
 {'patient_id': 20,
  'age': 64,
  'gender': 'F',
  'city': 'Hyderabad',
  'insurance_provider': 'HealthPlus',
  'chronic_flag': 0,
  'registration_date': '2/3/2025'},
 {'patient_id': 21,
  'age': 60,
  'gender': 'F',
  'city': 'Mumbai',
  'insurance_provider': 'CareOne',
  'chronic_flag': 0,
  'registration_date': '7/29/2025'},
 {'patient_id': 22,
  'age': 21,
  'gender': 'F',
  'city': 'Hyderabad',
  'insurance_provider': 'SecureLife',
  'chronic_flag': 0,
  'registration_date': '2/3/2025'},
 {'patient_id': 23,
  'age': 33,
  'gender': 'M',
  'city': 'Bangalore',
  'insurance_provider': 'HealthPlus',
  'chronic_flag': 0,
  'registration_date': '11/2/2025'},
 {'patient_id': 24,
  'age': 76,
  'gender': 'F',
  'city': 'Chennai',
  'insurance_provider': 'MediCareX',
  'chronic_flag': 0,
  'registration_date': '1/17/2026'},
 {'patient_id': 25,
  'age': 58,
  'gender': 'F',
  'city': 'Chennai',
  'insurance_provider': 'CareOne',
  'chronic_flag': 1,
  'registration_date': '1/29/2025'},
 {'patient_id': 26,
  'age': 22,
  'gender': 'F',
  'city': 'Mumbai',
  'insurance_provider': 'MediCareX',
  'chronic_flag': 1,
  'registration_date': '3/17/2025'},
 {'patient_id': 27,
  'age': 89,
  'gender': 'F',
  'city': 'Pune',
  'insurance_provider': 'CareOne',
  'chronic_flag': 0,
  'registration_date': '8/6/2025'},
 {'patient_id': 28,
  'age': 49,
  'gender': 'M',
  'city': 'Bangalore',
  'insurance_provider': 'MediCareX',
  'chronic_flag': 1,
  'registration_date': '6/29/2025'},
 {'patient_id': 29,
  'age': 59,
  'gender': 'M',
  'city': 'Mumbai',
  'insurance_provider': 'HealthPlus',
  'chronic_flag': 0,
  'registration_date': '10/9/2025'},
 {'patient_id': 30,
  'age': 42,
  'gender': 'M',
  'city': 'Mumbai',
  'insurance_provider': 'CareOne',
  'chronic_flag': 0,
  'registration_date': '9/29/2025'},
 {'patient_id': 31,
  'age': 60,
  'gender': 'F',
  'city': 'Chennai',
  'insurance_provider': 'SecureLife',
  'chronic_flag': 1,
  'registration_date': '5/18/2025'},
 {'patient_id': 32,
  'age': 80,
  'gender': 'M',
  'city': 'Hyderabad',
  'insurance_provider': 'SecureLife',
  'chronic_flag': 1,
  'registration_date': '4/9/2025'},
 {'patient_id': 33,
  'age': 15,
  'gender': 'M',
  'city': 'Bangalore',
  'insurance_provider': 'MediCareX',
  'chronic_flag': 1,
  'registration_date': '5/23/2025'},
 {'patient_id': 34,
  'age': 62,
  'gender': 'F',
  'city': 'Hyderabad',
  'insurance_provider': 'MediCareX',
  'chronic_flag': 0,
  'registration_date': '11/28/2025'},
 {'patient_id': 35,
  'age': 62,
  'gender': 'M',
  'city': 'Delhi',
  'insurance_provider': 'MediCareX',
  'chronic_flag': 0,
  'registration_date': '4/1/2025'},
 {'patient_id': 36,
  'age': 47,
  'gender': 'F',
  'city': 'Delhi',
  'insurance_provider': 'CareOne',
  'chronic_flag': 1,
  'registration_date': '7/6/2025'},
 {'patient_id': 37,
  'age': 62,
  'gender': 'M',
  'city': 'Bangalore',
  'insurance_provider': 'SecureLife',
  'chronic_flag': 1,
  'registration_date': '10/30/2025'},
 {'patient_id': 38,
  'age': 51,
  'gender': 'M',
  'city': 'Pune',
  'insurance_provider': 'HealthPlus',
  'chronic_flag': 0,
  'registration_date': '2/24/2025'},
 {'patient_id': 39,
  'age': 55,
  'gender': 'M',
  'city': 'Delhi',
  'insurance_provider': 'CareOne',
  'chronic_flag': 1,
  'registration_date': '11/27/2025'},
 {'patient_id': 40,
  'age': 64,
  'gender': 'F',
  'city': 'Chennai',
  'insurance_provider': 'MediCareX',
  'chronic_flag': 1,
  'registration_date': '7/13/2025'},
 {'patient_id': 41,
  'age': 3,
  'gender': 'M',
  'city': 'Pune',
  'insurance_provider': 'SecureLife',
  'chronic_flag': 0,
  'registration_date': '8/6/2025'},
 {'patient_id': 42,
  'age': 51,
  'gender': 'M',
  'city': 'Mumbai',
  'insurance_provider': 'MediCareX',
  'chronic_flag': 1,
  'registration_date': '5/15/2025'},
 {'patient_id': 43,
  'age': 7,
  'gender': 'F',
  'city': 'Delhi',
  'insurance_provider': 'HealthPlus',
  'chronic_flag': 1,
  'registration_date': '11/30/2025'},
 {'patient_id': 44,
  'age': 21,
  'gender': 'M',
  'city': 'Chennai',
  'insurance_provider': 'HealthPlus',
  'chronic_flag': 0,
  'registration_date': '8/27/2025'},
 {'patient_id': 45,
  'age': 73,
  'gender': 'F',
  'city': 'Mumbai',
  'insurance_provider': 'SecureLife',
  'chronic_flag': 1,
  'registration_date': '3/26/2025'},
 {'patient_id': 46,
  'age': 39,
  'gender': 'F',
  'city': 'Pune',
  'insurance_provider': 'CareOne',
  'chronic_flag': 0,
  'registration_date': '10/11/2025'},
 {'patient_id': 47,
  'age': 18,
  'gender': 'M',
  'city': 'Bangalore',
  'insurance_provider': 'HealthPlus',
  'chronic_flag': 0,
  'registration_date': '6/2/2025'},
 {'patient_id': 48,
  'age': 4,
  'gender': 'F',
  'city': 'Mumbai',
  'insurance_provider': 'HealthPlus',
  'chronic_flag': 1,
  'registration_date': '5/18/2025'},
 {'patient_id': 49,
  'age': 89,
  'gender': 'M',
  'city': 'Hyderabad',
  'insurance_provider': 'HealthPlus',
  'chronic_flag': 1,
  'registration_date': '5/21/2025'},
 {'patient_id': 50,
  'age': 60,
  'gender': 'F',
  'city': 'Bangalore',
  'insurance_provider': 'HealthPlus',
  'chronic_flag': 1,
  'registration_date': '12/6/2025'},
 {'patient_id': 51,
  'age': 14,
  'gender': 'M',
  'city': 'Bangalore',
  'insurance_provider': 'MediCareX',
  'chronic_flag': 1,
  'registration_date': '4/16/2025'},
 {'patient_id': 52,
  'age': 9,
  'gender': 'F',
  'city': 'Pune',
  'insurance_provider': 'MediCareX',
  'chronic_flag': 1,
  'registration_date': '11/4/2025'},
 {'patient_id': 53,
  'age': 90,
  'gender': 'M',
  'city': 'Pune',
  'insurance_provider': 'CareOne',
  'chronic_flag': 1,
  'registration_date': '6/5/2025'},
 {'patient_id': 54,
  'age': 53,
  'gender': 'F',
  'city': 'Chennai',
  'insurance_provider': 'SecureLife',
  'chronic_flag': 0,
  'registration_date': '3/13/2025'},
 {'patient_id': 55,
  'age': 2,
  'gender': 'M',
  'city': 'Chennai',
  'insurance_provider': 'SecureLife',
  'chronic_flag': 1,
  'registration_date': '8/12/2025'},
 {'patient_id': 56,
  'age': 84,
  'gender': 'M',
  'city': 'Hyderabad',
  'insurance_provider': 'SecureLife',
  'chronic_flag': 1,
  'registration_date': '1/2/2026'},
 {'patient_id': 57,
  'age': 60,
  'gender': 'M',
  'city': 'Bangalore',
  'insurance_provider': 'HealthPlus',
  'chronic_flag': 0,
  'registration_date': '3/11/2025'},
 {'patient_id': 58,
  'age': 71,
  'gender': 'M',
  'city': 'Hyderabad',
  'insurance_provider': 'MediCareX',
  'chronic_flag': 1,
  'registration_date': '12/12/2025'},
 {'patient_id': 59,
  'age': 44,
  'gender': 'F',
  'city': 'Hyderabad',
  'insurance_provider': 'MediCareX',
  'chronic_flag': 1,
  'registration_date': '2/28/2025'},
 {'patient_id': 60,
  'age': 8,
  'gender': 'M',
  'city': 'Pune',
  'insurance_provider': 'CareOne',
  'chronic_flag': 1,
  'registration_date': '9/26/2025'},
 {'patient_id': 61,
  'age': 47,
  'gender': 'F',
  'city': 'Hyderabad',
  'insurance_provider': 'SecureLife',
  'chronic_flag': 0,
  'registration_date': '8/25/2025'},
 {'patient_id': 62,
  'age': 35,
  'gender': 'F',
  'city': 'Hyderabad',
  'insurance_provider': 'MediCareX',
  'chronic_flag': 1,
  'registration_date': '7/17/2025'},
 {'patient_id': 63,
  'age': 78,
  'gender': 'F',
  'city': 'Mumbai',
  'insurance_provider': 'CareOne',
  'chronic_flag': 0,
  'registration_date': '2/27/2025'},
 {'patient_id': 64,
  'age': 81,
  'gender': 'M',
  'city': 'Chennai',
  'insurance_provider': 'SecureLife',
  'chronic_flag': 0,
  'registration_date': '7/21/2025'},
 {'patient_id': 65,
  'age': 36,
  'gender': 'M',
  'city': 'Chennai',
  'insurance_provider': 'HealthPlus',
  'chronic_flag': 1,
  'registration_date': '8/31/2025'},
 {'patient_id': 66,
  'age': 50,
  'gender': 'F',
  'city': 'Bangalore',
  'insurance_provider': 'MediCareX',
  'chronic_flag': 1,
  'registration_date': '7/2/2025'},
 {'patient_id': 67,
  'age': 4,
  'gender': 'M',
  'city': 'Chennai',
  'insurance_provider': 'MediCareX',
  'chronic_flag': 0,
  'registration_date': '9/10/2025'},
 {'patient_id': 68,
  'age': 2,
  'gender': 'M',
  'city': 'Delhi',
  'insurance_provider': 'SecureLife',
  'chronic_flag': 0,
  'registration_date': '7/31/2025'},
 {'patient_id': 69,
  'age': 6,
  'gender': 'F',
  'city': 'Bangalore',
  'insurance_provider': 'HealthPlus',
  'chronic_flag': 1,
  'registration_date': '4/14/2025'},
 {'patient_id': 70,
  'age': 54,
  'gender': 'F',
  'city': 'Mumbai',
  'insurance_provider': 'HealthPlus',
  'chronic_flag': 1,
  'registration_date': '9/19/2025'},
 {'patient_id': 71,
  'age': 4,
  'gender': 'F',
  'city': 'Chennai',
  'insurance_provider': 'MediCareX',
  'chronic_flag': 1,
  'registration_date': '7/11/2025'},
 {'patient_id': 72,
  'age': 54,
  'gender': 'M',
  'city': 'Mumbai',
  'insurance_provider': 'SecureLife',
  'chronic_flag': 1,
  'registration_date': '2/25/2025'},
 {'patient_id': 73,
  'age': 63,
  'gender': 'F',
  'city': 'Chennai',
  'insurance_provider': 'CareOne',
  'chronic_flag': 0,
  'registration_date': '4/16/2025'},
 {'patient_id': 74,
  'age': 18,
  'gender': 'M',
  'city': 'Chennai',
  'insurance_provider': 'MediCareX',
  'chronic_flag': 0,
  'registration_date': '5/28/2025'},
 {'patient_id': 75,
  'age': 90,
  'gender': 'M',
  'city': 'Mumbai',
  'insurance_provider': 'HealthPlus',
  'chronic_flag': 0,
  'registration_date': '8/1/2025'},
 {'patient_id': 76,
  'age': 44,
  'gender': 'F',
  'city': 'Hyderabad',
  'insurance_provider': 'CareOne',
  'chronic_flag': 0,
  'registration_date': '12/4/2025'},
 {'patient_id': 77,
  'age': 34,
  'gender': 'M',
  'city': 'Hyderabad',
  'insurance_provider': 'SecureLife',
  'chronic_flag': 0,
  'registration_date': '3/3/2025'},
 {'patient_id': 78,
  'age': 74,
  'gender': 'M',
  'city': 'Hyderabad',
  'insurance_provider': 'HealthPlus',
  'chronic_flag': 0,
  'registration_date': '1/10/2026'},
 {'patient_id': 79,
  'age': 62,
  'gender': 'M',
  'city': 'Delhi',
  'insurance_provider': 'CareOne',
  'chronic_flag': 1,
  'registration_date': '6/27/2025'},
 {'patient_id': 80,
  'age': 14,
  'gender': 'F',
  'city': 'Hyderabad',
  'insurance_provider': 'MediCareX',
  'chronic_flag': 0,
  'registration_date': '5/4/2025'},
 {'patient_id': 81,
  'age': 48,
  'gender': 'F',
  'city': 'Chennai',
  'insurance_provider': 'HealthPlus',
  'chronic_flag': 1,
  'registration_date': '9/5/2025'},
 {'patient_id': 82,
  'age': 15,
  'gender': 'F',
  'city': 'Pune',
  'insurance_provider': 'SecureLife',
  'chronic_flag': 1,
  'registration_date': '8/24/2025'},
 {'patient_id': 83,
  'age': 72,
  'gender': 'F',
  'city': 'Mumbai',
  'insurance_provider': 'HealthPlus',
  'chronic_flag': 1,
  'registration_date': '10/10/2025'},
 {'patient_id': 84,
  'age': 78,
  'gender': 'M',
  'city': 'Pune',
  'insurance_provider': 'MediCareX',
  'chronic_flag': 1,
  'registration_date': '3/9/2025'},
 {'patient_id': 85,
  'age': 87,
  'gender': 'M',
  'city': 'Delhi',
  'insurance_provider': 'SecureLife',
  'chronic_flag': 1,
  'registration_date': '1/6/2026'},
 {'patient_id': 86,
  'age': 62,
  'gender': 'M',
  'city': 'Pune',
  'insurance_provider': 'MediCareX',
  'chronic_flag': 0,
  'registration_date': '5/22/2025'},
 {'patient_id': 87,
  'age': 40,
  'gender': 'M',
  'city': 'Bangalore',
  'insurance_provider': 'CareOne',
  'chronic_flag': 0,
  'registration_date': '11/18/2025'},
 {'patient_id': 88,
  'age': 85,
  'gender': 'M',
  'city': 'Hyderabad',
  'insurance_provider': 'HealthPlus',
  'chronic_flag': 0,
  'registration_date': '2/13/2025'},
 {'patient_id': 89,
  'age': 80,
  'gender': 'F',
  'city': 'Delhi',
  'insurance_provider': 'MediCareX',
  'chronic_flag': 0,
  'registration_date': '5/30/2025'},
 {'patient_id': 90,
  'age': 82,
  'gender': 'M',
  'city': 'Chennai',
  'insurance_provider': 'CareOne',
  'chronic_flag': 1,
  'registration_date': '8/31/2025'},
 {'patient_id': 91,
  'age': 53,
  'gender': 'M',
  'city': 'Hyderabad',
  'insurance_provider': 'SecureLife',
  'chronic_flag': 1,
  'registration_date': '4/28/2025'},
 {'patient_id': 92,
  'age': 24,
  'gender': 'M',
  'city': 'Hyderabad',
  'insurance_provider': 'SecureLife',
  'chronic_flag': 1,
  'registration_date': '1/6/2026'},
 {'patient_id': 93,
  'age': 26,
  'gender': 'M',
  'city': 'Pune',
  'insurance_provider': 'CareOne',
  'chronic_flag': 0,
  'registration_date': '11/5/2025'},
 {'patient_id': 94,
  'age': 89,
  'gender': 'F',
  'city': 'Bangalore',
  'insurance_provider': 'CareOne',
  'chronic_flag': 1,
  'registration_date': '8/4/2025'},
 {'patient_id': 95,
  'age': 60,
  'gender': 'M',
  'city': 'Hyderabad',
  'insurance_provider': 'SecureLife',
  'chronic_flag': 0,
  'registration_date': '5/8/2025'},
 {'patient_id': 96,
  'age': 41,
  'gender': 'M',
  'city': 'Mumbai',
  'insurance_provider': 'MediCareX',
  'chronic_flag': 1,
  'registration_date': '1/2/2026'},
 {'patient_id': 97,
  'age': 29,
  'gender': 'F',
  'city': 'Mumbai',
  'insurance_provider': 'CareOne',
  'chronic_flag': 0,
  'registration_date': '8/27/2025'},
 {'patient_id': 98,
  'age': 15,
  'gender': 'M',
  'city': 'Hyderabad',
  'insurance_provider': 'MediCareX',
  'chronic_flag': 0,
  'registration_date': '10/10/2025'},
 {'patient_id': 99,
  'age': 45,
  'gender': 'M',
  'city': 'Pune',
  'insurance_provider': 'SecureLife',
  'chronic_flag': 0,
  'registration_date': '8/15/2025'},
 {'patient_id': 100,
  'age': 65,
  'gender': 'M',
  'city': 'Pune',
  'insurance_provider': 'MediCareX',
  'chronic_flag': 1,
  'registration_date': '12/4/2025'},
 {'patient_id': 101,
  'age': 89,
  'gender': 'F',
  'city': 'Chennai',
  'insurance_provider': 'MediCareX',
  'chronic_flag': 0,
  'registration_date': '4/11/2025'},
 {'patient_id': 102,
  'age': 71,
  'gender': 'F',
  'city': 'Delhi',
  'insurance_provider': 'CareOne',
  'chronic_flag': 0,
  'registration_date': '2/13/2025'},
 {'patient_id': 103,
  'age': 9,
  'gender': 'F',
  'city': 'Delhi',
  'insurance_provider': 'MediCareX',
  'chronic_flag': 1,
  'registration_date': '7/24/2025'},
 {'patient_id': 104,
  'age': 88,
  'gender': 'M',
  'city': 'Delhi',
  'insurance_provider': 'MediCareX',
  'chronic_flag': 1,
  'registration_date': '1/27/2025'},
 {'patient_id': 105,
  'age': 1,
  'gender': 'F',
  'city': 'Bangalore',
  'insurance_provider': 'MediCareX',
  'chronic_flag': 0,
  'registration_date': '5/23/2025'},
 {'patient_id': 106,
  'age': 8,
  'gender': 'M',
  'city': 'Pune',
  'insurance_provider': 'SecureLife',
  'chronic_flag': 1,
  'registration_date': '6/17/2025'},
 {'patient_id': 107,
  'age': 88,
  'gender': 'M',
  'city': 'Chennai',
  'insurance_provider': 'SecureLife',
  'chronic_flag': 0,
  'registration_date': '4/27/2025'},
 {'patient_id': 108,
  'age': 63,
  'gender': 'M',
  'city': 'Mumbai',
  'insurance_provider': 'HealthPlus',
  'chronic_flag': 0,
  'registration_date': '8/23/2025'},
 {'patient_id': 109,
  'age': 11,
  'gender': 'M',
  'city': 'Delhi',
  'insurance_provider': 'SecureLife',
  'chronic_flag': 0,
  'registration_date': '4/30/2025'},
 {'patient_id': 110,
  'age': 81,
  'gender': 'F',
  'city': 'Mumbai',
  'insurance_provider': 'SecureLife',
  'chronic_flag': 0,
  'registration_date': '8/25/2025'},
 {'patient_id': 111,
  'age': 8,
  'gender': 'F',
  'city': 'Mumbai',
  'insurance_provider': 'HealthPlus',
  'chronic_flag': 1,
  'registration_date': '10/5/2025'},
 {'patient_id': 112,
  'age': 35,
  'gender': 'F',
  'city': 'Hyderabad',
  'insurance_provider': 'HealthPlus',
  'chronic_flag': 1,
  'registration_date': '1/10/2026'},
 {'patient_id': 113,
  'age': 35,
  'gender': 'F',
  'city': 'Bangalore',
  'insurance_provider': 'CareOne',
  'chronic_flag': 0,
  'registration_date': '1/30/2025'},
 {'patient_id': 114,
  'age': 33,
  'gender': 'F',
  'city': 'Chennai',
  'insurance_provider': 'CareOne',
  'chronic_flag': 1,
  'registration_date': '3/19/2025'},
 {'patient_id': 115,
  'age': 5,
  'gender': 'M',
  'city': 'Bangalore',
  'insurance_provider': 'SecureLife',
  'chronic_flag': 1,
  'registration_date': '9/26/2025'},
 {'patient_id': 116,
  'age': 41,
  'gender': 'M',
  'city': 'Hyderabad',
  'insurance_provider': 'MediCareX',
  'chronic_flag': 0,
  'registration_date': '6/8/2025'},
 {'patient_id': 117,
  'age': 28,
  'gender': 'F',
  'city': 'Chennai',
  'insurance_provider': 'CareOne',
  'chronic_flag': 0,
  'registration_date': '12/20/2025'},
 {'patient_id': 118,
  'age': 7,
  'gender': 'M',
  'city': 'Chennai',
  'insurance_provider': 'CareOne',
  'chronic_flag': 1,
  'registration_date': '2/26/2025'},
 {'patient_id': 119,
  'age': 73,
  'gender': 'F',
  'city': 'Pune',
  'insurance_provider': 'SecureLife',
  'chronic_flag': 1,
  'registration_date': '5/21/2025'},
 {'patient_id': 120,
  'age': 72,
  'gender': 'M',
  'city': 'Bangalore',
  'insurance_provider': 'MediCareX',
  'chronic_flag': 1,
  'registration_date': '3/25/2025'},
 {'patient_id': 121,
  'age': 12,
  'gender': 'M',
  'city': 'Bangalore',
  'insurance_provider': 'HealthPlus',

In [55]:
len(patient_data)

5000

In [ ]:
DB_NAME="hospital_miops"
COLLECTION_PATIENT="patient_data"
COLLECTION_VISITS="visits_data"
COLLECTION_BILLING="billing_data_data"
CONNECTION_URL="new_url"

In [57]:
import pymongo
import pandas as pd

In [58]:
client=pymongo.MongoClient(CONNECTION_URL)
db=client[DB_NAME]
patient_collection=db[COLLECTION_PATIENT]
visits_collection=db[COLLECTION_VISITS]
billing_collection=db[COLLECTION_BILLING]

patient_rec=patient_collection.insert_many(patient_data)
visits_rec=visits_collection.insert_many(visits_data)      
billing_rec=billing_collection.insert_many(billing_data)

In [59]:
patient_df=pd.DataFrame(list(patient_collection.find()))
patient_df.head()

,_id,patient_id,age,gender,city,insurance_provider,chronic_flag,registration_date
0,6a286bfbdb5bb3abac6f50c2,14,10,F,Mumbai,MediCareX,1,2026-01-14
1,6a286bfbdb5bb3abac6f50e8,52,38,F,Bangalore,MediCareX,1,2025-05-11
2,6a286bfbdb5bb3abac6f50f3,63,25,M,Delhi,SecureLife,0,2025-12-27
3,6a286bfbdb5bb3abac6f50fc,72,72,M,Delhi,MediCareX,0,2025-06-26
4,6a286bfbdb5bb3abac6f5108,84,35,F,Mumbai,SecureLife,1,2025-11-26

In [60]:
billing_df=pd.DataFrame(list(billing_collection.find()))
billing_df.head()

,_id,bill_id,visit_id,billed_amount,approved_amount,claim_status,payment_days,billing_date
0,6a286c11db5bb3abac6fc600,28,28,38162.87,NaN,Paid,21.0,2025-09-30
1,6a286c11db5bb3abac6fc601,29,29,6851.33,6851.33,Paid,12.0,2025-03-23
2,6a286c11db5bb3abac6fc606,34,34,5893.50,5893.50,Paid,6.0,2025-06-20
3,6a286c11db5bb3abac6fc625,65,65,31990.78,21941.52,Pending,2.0,2025-10-02
4,6a286c11db5bb3abac6fc63c,88,88,37790.01,37790.01,Paid,16.0,2025-06-24

In [61]:
visits_df=pd.DataFrame(list(visits_collection.find()))
visits_df.head()

,_id,visit_id,patient_id,visit_date,department,visit_type,length_of_stay_hours,risk_score,doctor_id
0,6a286c04db5bb3abac6f6446,10,4442,2025-12-07,ER,ER,23.22,Low,107
1,6a286c04db5bb3abac6f6464,40,3989,2025-09-03,Neurology,ICU,0.92,Low,112
2,6a286c04db5bb3abac6f6467,43,2608,2025-09-02,ER,OPD,31.29,Low,145
3,6a286c04db5bb3abac6f6469,45,4944,2025-12-31,ER,OPD,9.69,Medium,166
4,6a286c04db5bb3abac6f6487,75,675,2025-12-07,General,ER,16.32,Low,194

In [62]:
if"_id" in patient_df.columns:
    patient_df.drop("_id",axis=1,inplace=True)
if"_id" in billing_df.columns:
    billing_df.drop("_id",axis=1,inplace=True)
if"_id" in visits_df.columns:
    visits_df.drop("_id",axis=1,inplace=True)

In [63]:
visits_df.head()

,visit_id,patient_id,visit_date,department,visit_type,length_of_stay_hours,risk_score,doctor_id
0,10,4442,2025-12-07,ER,ER,23.22,Low,107
1,40,3989,2025-09-03,Neurology,ICU,0.92,Low,112
2,43,2608,2025-09-02,ER,OPD,31.29,Low,145
3,45,4944,2025-12-31,ER,OPD,9.69,Medium,166
4,75,675,2025-12-07,General,ER,16.32,Low,194

In [64]:
# Create db folder, if it doesn't exits
import pandas as pd
import sqlite3
import os


os.makedirs("../db", exist_ok=True)

# Connect to sqlite and then create db
conn = sqlite3.connect("../db/hospital.db")
cursor = conn.cursor()
print("Database connected:", conn)

Database connected: <sqlite3.Connection object at 0x000001A9E021A2F0>

In [65]:
billing = pd.read_csv("data/billing.csv")
visits = pd.read_csv("data/visits.csv")
patient = pd.read_csv("data/patients.csv")

print("patient shape :",patient.shape)
print("billing shape :",billing.shape)
print("visits shape :",visits.shape)
# write all three dataframes into sqlite tables
patient.to_sql("patients", conn, if_exists="replace", index=False)
visits.to_sql("visits", conn, if_exists="replace", index=False)
billing.to_sql("billing", conn, if_exists="replace", index=False)

print("All three tables loaded into hospital db")

patient shape : (5000, 7)
billing shape : (25000, 7)
visits shape : (25000, 8)
All three tables loaded into hospital db

In [66]:
# Quick preview of tables
print("=== PATIENTS (first 3 rows) ===")
print(pd.read_sql("select * from patients limit 5", conn).to_string())

print("=== VISITS (first 3 rows) ===")
print(pd.read_sql("select * from visits limit 5", conn).to_string())

print("=== BILLING (first 3 rows) ===")
print(pd.read_sql("select * from billing limit 5", conn).to_string())

=== PATIENTS (first 3 rows) ===
   patient_id  age gender       city insurance_provider  chronic_flag registration_date
0           1   52      M  Bangalore            CareOne             1          5/6/2025
1           2   15      F     Mumbai            CareOne             0        12/27/2025
2           3   72      F  Bangalore         SecureLife             1         1/28/2025
3           4   61      M     Mumbai          MediCareX             1          2/8/2025
4           5   21      F     Mumbai            CareOne             1         6/17/2025
=== VISITS (first 3 rows) ===
   visit_id  patient_id  visit_date  department visit_type  length_of_stay_hours risk_score  doctor_id
0         1           1  10/16/2025  Cardiology        OPD                 23.15        Low        186
1         2           1   12/9/2025         ICU        ICU                 39.98       High        149
2         3           1  10/29/2025          ER         ER                 20.97     Medium        122
3         4           1   7/31/2025          ER         ER                  8.32     Medium        193
4         5           1    8/2/2025         ICU        ICU                 41.43       High        141
=== BILLING (first 3 rows) ===
   bill_id  visit_id  billed_amount  approved_amount claim_status  payment_days billing_date
0        1         1       23550.00         21429.62         Paid           8.0   2025-11-03
1        2         2       88539.01         19725.49      Pending           NaN   2025-12-16
2        3         3       25949.30          1580.95     Rejected           NaN   2025-11-20
3        4         4        8349.57              NaN      Pending           NaN   2025-08-16
4        5         5       88539.01         86803.45         Paid          30.0   2025-08-23

## Financial Analytics

In [67]:
#department workload analysis
query = """
SELECT department, COUNT(*) AS num_visits, 
ROUND(AVG(length_of_stay_hours),2) AS avg_stay_hours,
ROUND(MAX(length_of_stay_hours),2) AS max_stay_hours,
SUM(CASE
    WHEN risk_score = 'High'
    THEN 1
    ELSE 0
END) AS high_risk_count
FROM visits
GROUP BY department
order by num_visits DESC
"""
department_workload = pd.read_sql(query, conn)
print("Department Workload:")
print(department_workload.to_string(index=False))

Department Workload:
 department  num_visits  avg_stay_hours  max_stay_hours  high_risk_count
    General        5757           14.01           36.54               24
Orthopedics        4474           23.02           52.99               54
 Cardiology        4071           32.59           70.74              489
         ER        3896           11.95           30.78              139
        ICU        3415           56.86           78.42             2975
  Neurology        3387           27.69           66.16              635

In [68]:
#which doctor handled most critical patients
query = """
SELECT 
        doctor_id,
        COUNT(visit_id)                              AS total_visits,
        SUM(CASE WHEN risk_score = 'High' 
            THEN 1 ELSE 0 END)                       AS high_risk_cases,
        ROUND(
            100.0 * SUM(CASE WHEN risk_score = 'High' 
            THEN 1 ELSE 0 END) / COUNT(visit_id), 1) AS high_risk_pct
    FROM visits
    GROUP BY doctor_id
    ORDER BY high_risk_cases DESC
    LIMIT 10
"""
doctor_risk = pd.read_sql(query, conn)
print("Doctor Risk Analysis:")
print(doctor_risk.to_string(index=False))

Doctor Risk Analysis:
 doctor_id  total_visits  high_risk_cases  high_risk_pct
       114           260               61           23.5
       130           264               60           22.7
       187           262               57           21.8
       126           244               55           22.5
       102           271               55           20.3
       189           240               54           22.5
       158           252               53           21.0
       171           260               52           20.0
       150           252               52           20.6
       194           267               51           19.1

In [69]:
#Patient Visit Patterns distribution
query = """
  SELECT 
        visit_frequency_bucket,
        COUNT(patient_id) AS num_patients
    FROM (
        SELECT 
            patient_id,
            COUNT(visit_id) AS visit_count,
            CASE 
                WHEN COUNT(visit_id) = 1     THEN '1 visit'
                WHEN COUNT(visit_id) BETWEEN 2 AND 3 THEN '2-3 visits'
                WHEN COUNT(visit_id) BETWEEN 4 AND 5 THEN '4-5 visits'
                ELSE '6+ visits'
            END AS visit_frequency_bucket
        FROM visits
        GROUP BY patient_id
    )
    GROUP BY visit_frequency_bucket
    ORDER BY num_patients DESC

"""
visit_patterns = pd.read_sql(query, conn)
print("Visit Patterns Analysis:")
print(visit_patterns.to_string(index=False))

Visit Patterns Analysis:
visit_frequency_bucket  num_patients
             6+ visits          1816
            4-5 visits          1776
            2-3 visits          1267
               1 visit           141

In [70]:
# Risk Score Distribution
query = """
   SELECT 
        department,
        SUM(CASE WHEN risk_score = 'Low'    THEN 1 ELSE 0 END) AS low,
        SUM(CASE WHEN risk_score = 'Medium' THEN 1 ELSE 0 END) AS medium,
        SUM(CASE WHEN risk_score = 'High'   THEN 1 ELSE 0 END) AS high,
        COUNT(*) AS total
    FROM visits
    GROUP BY department
    ORDER BY high DESC

"""
risk_by_dept = pd.read_sql(query, conn)
print("Risk Score Distribution by Department:")
print(risk_by_dept.to_string(index=False))

Risk Score Distribution by Department:
 department  low  medium  high  total
        ICU   10     430  2975   3415
  Neurology  875    1877   635   3387
 Cardiology 1063    2519   489   4071
         ER 1771    1986   139   3896
Orthopedics 3426     994    54   4474
    General 4590    1143    24   5757

## Financial Analytics

In [71]:
#  Revenue and claim outcomes by insurance provider
query = """
  SELECT 
        p.insurance_provider,
        COUNT(b.bill_id)                         AS total_claims,
        ROUND(SUM(b.billed_amount), 0)           AS total_billed,
        ROUND(AVG(b.billed_amount), 0)           AS avg_billed,
        ROUND(SUM(b.approved_amount), 0)         AS total_approved,
        SUM(CASE WHEN b.claim_status = 'Paid'     
            THEN 1 ELSE 0 END)                   AS paid,
        SUM(CASE WHEN b.claim_status = 'Pending'  
            THEN 1 ELSE 0 END)                   AS pending,
        SUM(CASE WHEN b.claim_status = 'Rejected' 
            THEN 1 ELSE 0 END)                   AS rejected
    FROM billing b
    JOIN visits  v ON b.visit_id   = v.visit_id
    JOIN patients p ON v.patient_id = p.patient_id
    GROUP BY p.insurance_provider
    ORDER BY total_billed DESC

"""
insurance_billing = pd.read_sql(query, conn)
print("Risk Score Distribution by Department:")
print(insurance_billing.to_string(index=False))

Risk Score Distribution by Department:
insurance_provider  total_claims  total_billed  avg_billed  total_approved  paid  pending  rejected
        HealthPlus          6499   251723095.0     38733.0     124033289.0  3727     1557      1215
           CareOne          6326   246192121.0     38918.0     107084590.0  3160     1541      1625
        SecureLife          6197   242381528.0     39113.0     128230940.0  3723     1498       976
         MediCareX          5978   229000682.0     38307.0     100849491.0  3028     1500      1450

In [72]:
# Which insurance providers reject the most claims?
query = """
 SELECT 
        p.insurance_provider,
        COUNT(b.bill_id)                              AS total_claims,
        SUM(CASE WHEN b.claim_status = 'Rejected' 
            THEN 1 ELSE 0 END)                        AS rejected_claims,
        ROUND(
            100.0 * SUM(CASE WHEN b.claim_status = 'Rejected' 
            THEN 1 ELSE 0 END) / COUNT(b.bill_id), 1) AS rejection_rate_pct
    FROM billing b
    JOIN visits   v ON b.visit_id   = v.visit_id
    JOIN patients p ON v.patient_id = p.patient_id
    GROUP BY p.insurance_provider
    ORDER BY rejection_rate_pct DESC

"""
rejection_analysis = pd.read_sql(query, conn)
print("Claim Rejection Analysis by Insurance Provider:")
print(rejection_analysis.to_string(index=False))

Claim Rejection Analysis by Insurance Provider:
insurance_provider  total_claims  rejected_claims  rejection_rate_pct
           CareOne          6326             1625                25.7
         MediCareX          5978             1450                24.3
        HealthPlus          6499             1215                18.7
        SecureLife          6197              976                15.7

In [73]:
#How much of what we bill actually gets approved
query = """
    SELECT 
        p.insurance_provider,
        ROUND(SUM(b.billed_amount), 0)                AS total_billed,
        ROUND(SUM(b.approved_amount), 0)              AS total_approved,
        ROUND(
            100.0 * SUM(b.approved_amount) / 
            SUM(b.billed_amount), 1)                  AS realization_rate_pct
    FROM billing b
    JOIN visits   v ON b.visit_id   = v.visit_id
    JOIN patients p ON v.patient_id = p.patient_id
    WHERE b.approved_amount IS NOT NULL
    GROUP BY p.insurance_provider
    ORDER BY realization_rate_pct DESC

"""
revenue_realization = pd.read_sql(query, conn)
print("Revenue Realization Analysis by Insurance Provider:")
print(revenue_realization.to_string(index=False))

Revenue Realization Analysis by Insurance Provider:
insurance_provider  total_billed  total_approved  realization_rate_pct
        SecureLife   181215374.0     128230940.0                  70.8
        HealthPlus   180661516.0     124033289.0                  68.7
         MediCareX   157807601.0     100849491.0                  63.9
           CareOne   169349090.0     107084590.0                  63.2

## Data Quality

In [74]:
# Missing Records Check
print("=== MISSING VALUES CHECK ===\n")

for table in ['patients', 'visits', 'billing']:
    df = pd.read_sql(f"SELECT * FROM {table}", conn)
    nulls = df.isnull().sum()
    nulls = nulls[nulls > 0]
    if len(nulls) > 0:
        print(f"{table}:")
        print(nulls.to_string())
        print()
    else:
        print(f"{table}: ✓ No missing values\n")

=== MISSING VALUES CHECK ===

patients: ✓ No missing values

visits: ✓ No missing values

billing:
approved_amount    6156
payment_days       9532

In [75]:
# Duplicate Patients Check
duplicate_patients = pd.read_sql("""
    SELECT 
        patient_id,
        COUNT(*) AS occurrences
    FROM patients
    GROUP BY patient_id
    HAVING COUNT(*) > 1
""", conn)

if len(duplicate_patients) == 0:
    print("✓ No duplicate patient_ids found")
else:
    print(f"⚠ Found {len(duplicate_patients)} duplicate patient_ids")
    print(duplicate_patients)

✓ No duplicate patient_ids found

In [76]:
# Orphan Records Check
# Visits without matching patients
orphan_visits = pd.read_sql("""
    SELECT COUNT(*) AS orphan_visits
    FROM visits v
    LEFT JOIN patients p ON v.patient_id = p.patient_id
    WHERE p.patient_id IS NULL
""", conn)

# Billing without matching visits
orphan_billing = pd.read_sql("""
    SELECT COUNT(*) AS orphan_billing
    FROM billing b
    LEFT JOIN visits v ON b.visit_id = v.visit_id
    WHERE v.visit_id IS NULL
""", conn)

print("Orphan visits  (no matching patient):", 
      orphan_visits['orphan_visits'][0])
print("Orphan billing (no matching visit)  :", 
      orphan_billing['orphan_billing'][0])

Orphan visits  (no matching patient): 0
Orphan billing (no matching visit)  : 0

In [77]:
#Invalid LOS Check
invalid_los = pd.read_sql("""
    SELECT 
        COUNT(CASE WHEN length_of_stay_hours <= 0  THEN 1 END) AS zero_or_negative,
        COUNT(CASE WHEN length_of_stay_hours > 720 THEN 1 END) AS over_30_days,
        MIN(length_of_stay_hours)                              AS min_los,
        MAX(length_of_stay_hours)                             AS max_los,
        ROUND(AVG(length_of_stay_hours), 2)                   AS avg_los
    FROM visits
""", conn)

print("LOS Validation:")
print(invalid_los.to_string(index=False))

LOS Validation:
 zero_or_negative  over_30_days  min_los  max_los  avg_los
                0             0      0.5    78.42    26.03

In [78]:
# Invalid Payment Days Check
invalid_payment = pd.read_sql("""
    SELECT 
        COUNT(CASE WHEN payment_days < 0   THEN 1 END) AS negative_days,
        COUNT(CASE WHEN payment_days > 365 THEN 1 END) AS over_1_year,
        COUNT(CASE WHEN payment_days IS NULL THEN 1 END) AS nulls,
        MIN(payment_days)                               AS min_days,
        MAX(payment_days)                               AS max_days
    FROM billing
""", conn)

print("Payment Days Validation:")
print(invalid_payment.to_string(index=False))

Payment Days Validation:
 negative_days  over_1_year  nulls  min_days  max_days
             0            0   9532       1.0      55.0

In [79]:
# Join all three tables into one flat table for ML modeling.
# This is the single source of truth for Phase 2 EDA and Phase 3 Modeling.
model_table = pd.read_sql("""
    SELECT
        -- Patient features
        p.patient_id,
        p.age,
        p.gender,
        p.city,
        p.insurance_provider,
        p.chronic_flag,
        p.registration_date,

        -- Visit features
        v.visit_id,
        v.visit_date,
        v.department,
        v.visit_type,
        v.length_of_stay_hours,
        v.risk_score,
        v.doctor_id,

        -- Billing features
        b.bill_id,
        b.billed_amount,
        b.approved_amount,
        b.claim_status,
        b.payment_days,
        b.billing_date

    FROM visits v
    JOIN patients p ON v.patient_id = p.patient_id
    JOIN billing  b ON v.visit_id   = b.visit_id
    ORDER BY v.visit_date
""", conn)

print("model_table shape:", model_table.shape)
print("Columns:", model_table.columns.tolist())
model_table.head(3)

model_table shape: (25000, 20)
Columns: ['patient_id', 'age', 'gender', 'city', 'insurance_provider', 'chronic_flag', 'registration_date', 'visit_id', 'visit_date', 'department', 'visit_type', 'length_of_stay_hours', 'risk_score', 'doctor_id', 'bill_id', 'billed_amount', 'approved_amount', 'claim_status', 'payment_days', 'billing_date']

,patient_id,age,gender,city,insurance_provider,chronic_flag,registration_date,visit_id,visit_date,department,visit_type,length_of_stay_hours,risk_score,doctor_id,bill_id,billed_amount,approved_amount,claim_status,payment_days,billing_date
0,2,15,F,Mumbai,CareOne,0,12/27/2025,8,1/1/2026,General,OPD,9.63,Low,105,8,9612.77,NaN,Rejected,NaN,2026-01-19
1,12,3,M,Bangalore,CareOne,0,8/13/2025,65,1/1/2026,ICU,ICU,59.60,High,112,65,88539.01,NaN,Rejected,NaN,2026-01-05
2,129,44,M,Pune,MediCareX,1,7/20/2025,651,1/1/2026,ICU,ER,59.28,High,150,651,88539.01,NaN,Pending,NaN,2026-01-20

In [80]:
# save the table
import os
os.makedirs("../outputs", exist_ok=True)
model_table.to_csv("../outputs/model_table.csv", index=False)
print(f"model_table.csv saved --> /outputs/model_table.csv")
print(f"Shape: {model_table.shape}")
print(f"Size: {os.path.getsize('../outputs/model_table.csv')/1024:.1f} KB")

model_table.csv saved --> /outputs/model_table.csv
Shape: (25000, 20)
Size: 3049.5 KB

In [81]:
model_table= pd.read_csv("../outputs/model_table.csv")
model_table.head()

,patient_id,age,gender,city,insurance_provider,chronic_flag,registration_date,visit_id,visit_date,department,visit_type,length_of_stay_hours,risk_score,doctor_id,bill_id,billed_amount,approved_amount,claim_status,payment_days,billing_date
0,2,15,F,Mumbai,CareOne,0,12/27/2025,8,1/1/2026,General,OPD,9.63,Low,105,8,9612.77,NaN,Rejected,NaN,2026-01-19
1,12,3,M,Bangalore,CareOne,0,8/13/2025,65,1/1/2026,ICU,ICU,59.60,High,112,65,88539.01,NaN,Rejected,NaN,2026-01-05
2,129,44,M,Pune,MediCareX,1,7/20/2025,651,1/1/2026,ICU,ER,59.28,High,150,651,88539.01,NaN,Pending,NaN,2026-01-20
3,133,47,F,Delhi,CareOne,1,11/2/2025,670,1/1/2026,General,OPD,25.15,Medium,145,670,20958.52,20322.91,Paid,48.0,2026-01-15
4,139,14,F,Chennai,SecureLife,1,2/5/2025,706,1/1/2026,Cardiology,ER,42.88,Medium,148,706,74921.48,72277.09,Paid,27.0,2026-01-16

In [82]:
model_table_df= model_table.to_dict(orient="records")
model_table_df

[{'patient_id': 2,
  'age': 15,
  'gender': 'F',
  'city': 'Mumbai',
  'insurance_provider': 'CareOne',
  'chronic_flag': 0,
  'registration_date': '12/27/2025',
  'visit_id': 8,
  'visit_date': '1/1/2026',
  'department': 'General',
  'visit_type': 'OPD',
  'length_of_stay_hours': 9.63,
  'risk_score': 'Low',
  'doctor_id': 105,
  'bill_id': 8,
  'billed_amount': 9612.77,
  'approved_amount': nan,
  'claim_status': 'Rejected',
  'payment_days': nan,
  'billing_date': '2026-01-19'},
 {'patient_id': 12,
  'age': 3,
  'gender': 'M',
  'city': 'Bangalore',
  'insurance_provider': 'CareOne',
  'chronic_flag': 0,
  'registration_date': '8/13/2025',
  'visit_id': 65,
  'visit_date': '1/1/2026',
  'department': 'ICU',
  'visit_type': 'ICU',
  'length_of_stay_hours': 59.6,
  'risk_score': 'High',
  'doctor_id': 112,
  'bill_id': 65,
  'billed_amount': 88539.01,
  'approved_amount': nan,
  'claim_status': 'Rejected',
  'payment_days': nan,
  'billing_date': '2026-01-05'},
 {'patient_id': 129,
  'age': 44,
  'gender': 'M',
  'city': 'Pune',
  'insurance_provider': 'MediCareX',
  'chronic_flag': 1,
  'registration_date': '7/20/2025',
  'visit_id': 651,
  'visit_date': '1/1/2026',
  'department': 'ICU',
  'visit_type': 'ER',
  'length_of_stay_hours': 59.28,
  'risk_score': 'High',
  'doctor_id': 150,
  'bill_id': 651,
  'billed_amount': 88539.01,
  'approved_amount': nan,
  'claim_status': 'Pending',
  'payment_days': nan,
  'billing_date': '2026-01-20'},
 {'patient_id': 133,
  'age': 47,
  'gender': 'F',
  'city': 'Delhi',
  'insurance_provider': 'CareOne',
  'chronic_flag': 1,
  'registration_date': '11/2/2025',
  'visit_id': 670,
  'visit_date': '1/1/2026',
  'department': 'General',
  'visit_type': 'OPD',
  'length_of_stay_hours': 25.15,
  'risk_score': 'Medium',
  'doctor_id': 145,
  'bill_id': 670,
  'billed_amount': 20958.52,
  'approved_amount': 20322.91,
  'claim_status': 'Paid',
  'payment_days': 48.0,
  'billing_date': '2026-01-15'},
 {'patient_id': 139,
  'age': 14,
  'gender': 'F',
  'city': 'Chennai',
  'insurance_provider': 'SecureLife',
  'chronic_flag': 1,
  'registration_date': '2/5/2025',
  'visit_id': 706,
  'visit_date': '1/1/2026',
  'department': 'Cardiology',
  'visit_type': 'ER',
  'length_of_stay_hours': 42.88,
  'risk_score': 'Medium',
  'doctor_id': 148,
  'bill_id': 706,
  'billed_amount': 74921.48,
  'approved_amount': 72277.09,
  'claim_status': 'Paid',
  'payment_days': 27.0,
  'billing_date': '2026-01-16'},
 {'patient_id': 170,
  'age': 44,
  'gender': 'M',
  'city': 'Bangalore',
  'insurance_provider': 'HealthPlus',
  'chronic_flag': 1,
  'registration_date': '11/10/2025',
  'visit_id': 849,
  'visit_date': '1/1/2026',
  'department': 'Neurology',
  'visit_type': 'ER',
  'length_of_stay_hours': 18.25,
  'risk_score': 'Medium',
  'doctor_id': 185,
  'bill_id': 849,
  'billed_amount': 31867.91,
  'approved_amount': nan,
  'claim_status': 'Rejected',
  'payment_days': nan,
  'billing_date': '2026-01-03'},
 {'patient_id': 216,
  'age': 32,
  'gender': 'M',
  'city': 'Delhi',
  'insurance_provider': 'SecureLife',
  'chronic_flag': 0,
  'registration_date': '12/25/2025',
  'visit_id': 1048,
  'visit_date': '1/1/2026',
  'department': 'Cardiology',
  'visit_type': 'OPD',
  'length_of_stay_hours': 35.99,
  'risk_score': 'Medium',
  'doctor_id': 187,
  'bill_id': 1048,
  'billed_amount': 74288.71,
  'approved_amount': 73100.85,
  'claim_status': 'Paid',
  'payment_days': 53.0,
  'billing_date': '2026-01-19'},
 {'patient_id': 222,
  'age': 56,
  'gender': 'M',
  'city': 'Pune',
  'insurance_provider': 'MediCareX',
  'chronic_flag': 1,
  'registration_date': '6/28/2025',
  'visit_id': 1083,
  'visit_date': '1/1/2026',
  'department': 'General',
  'visit_type': 'ER',
  'length_of_stay_hours': 21.91,
  'risk_score': 'Medium',
  'doctor_id': 177,
  'bill_id': 1083,
  'billed_amount': 19358.98,
  'approved_amount': 1709.54,
  'claim_status': 'Pending',
  'payment_days': nan,
  'billing_date': '2026-01-20'},
 {'patient_id': 243,
  'age': 20,
  'gender': 'M',
  'city': 'Hyderabad',
  'insurance_provider': 'MediCareX',
  'chronic_flag': 1,
  'registration_date': '4/5/2025',
  'visit_id': 1197,
  'visit_date': '1/1/2026',
  'department': 'Cardiology',
  'visit_type': 'OPD',
  'length_of_stay_hours': 44.31,
  'risk_score': 'Medium',
  'doctor_id': 130,
  'bill_id': 1197,
  'billed_amount': 78869.93,
  'approved_amount': nan,
  'claim_status': 'Pending',
  'payment_days': nan,
  'billing_date': '2026-01-02'},
 {'patient_id': 335,
  'age': 37,
  'gender': 'F',
  'city': 'Pune',
  'insurance_provider': 'HealthPlus',
  'chronic_flag': 1,
  'registration_date': '11/25/2025',
  'visit_id': 1663,
  'visit_date': '1/1/2026',
  'department': 'Cardiology',
  'visit_type': 'ER',
  'length_of_stay_hours': 33.95,
  'risk_score': 'Medium',
  'doctor_id': 126,
  'bill_id': 1663,
  'billed_amount': 67258.54,
  'approved_amount': 14081.42,
  'claim_status': 'Pending',
  'payment_days': nan,
  'billing_date': '2026-01-02'},
 {'patient_id': 341,
  'age': 85,
  'gender': 'F',
  'city': 'Mumbai',
  'insurance_provider': 'MediCareX',
  'chronic_flag': 0,
  'registration_date': '12/2/2025',
  'visit_id': 1694,
  'visit_date': '1/1/2026',
  'department': 'Orthopedics',
  'visit_type': 'OPD',
  'length_of_stay_hours': 34.81,
  'risk_score': 'Low',
  'doctor_id': 172,
  'bill_id': 1694,
  'billed_amount': 49582.9,
  'approved_amount': nan,
  'claim_status': 'Rejected',
  'payment_days': nan,
  'billing_date': '2026-01-20'},
 {'patient_id': 344,
  'age': 33,
  'gender': 'F',
  'city': 'Hyderabad',
  'insurance_provider': 'SecureLife',
  'chronic_flag': 1,
  'registration_date': '8/11/2025',
  'visit_id': 1711,
  'visit_date': '1/1/2026',
  'department': 'General',
  'visit_type': 'OPD',
  'length_of_stay_hours': 19.81,
  'risk_score': 'Low',
  'doctor_id': 153,
  'bill_id': 1711,
  'billed_amount': 11896.06,
  'approved_amount': 11628.19,
  'claim_status': 'Paid',
  'payment_days': 26.0,
  'billing_date': '2026-01-12'},
 {'patient_id': 391,
  'age': 51,
  'gender': 'M',
  'city': 'Pune',
  'insurance_provider': 'HealthPlus',
  'chronic_flag': 0,
  'registration_date': '12/19/2025',
  'visit_id': 1951,
  'visit_date': '1/1/2026',
  'department': 'Orthopedics',
  'visit_type': 'OPD',
  'length_of_stay_hours': 18.67,
  'risk_score': 'Low',
  'doctor_id': 122,
  'bill_id': 1951,
  'billed_amount': 26371.08,
  'approved_amount': 3550.65,
  'claim_status': 'Rejected',
  'payment_days': nan,
  'billing_date': '2026-01-20'},
 {'patient_id': 394,
  'age': 63,
  'gender': 'F',
  'city': 'Bangalore',
  'insurance_provider': 'CareOne',
  'chronic_flag': 0,
  'registration_date': '10/29/2025',
  'visit_id': 1966,
  'visit_date': '1/1/2026',
  'department': 'Orthopedics',
  'visit_type': 'OPD',
  'length_of_stay_hours': 11.53,
  'risk_score': 'Low',
  'doctor_id': 193,
  'bill_id': 1966,
  'billed_amount': 9311.04,
  'approved_amount': 8469.39,
  'claim_status': 'Paid',
  'payment_days': 34.0,
  'billing_date': '2026-01-07'},
 {'patient_id': 401,
  'age': 52,
  'gender': 'M',
  'city': 'Mumbai',
  'insurance_provider': 'HealthPlus',
  'chronic_flag': 1,
  'registration_date': '12/27/2025',
  'visit_id': 1999,
  'visit_date': '1/1/2026',
  'department': 'General',
  'visit_type': 'OPD',
  'length_of_stay_hours': 16.36,
  'risk_score': 'Low',
  'doctor_id': 103,
  'bill_id': 1999,
  'billed_amount': 16901.68,
  'approved_amount': 16798.71,
  'claim_status': 'Paid',
  'payment_days': 41.0,
  'billing_date': '2026-01-05'},
 {'patient_id': 445,
  'age': 67,
  'gender': 'F',
  'city': 'Pune',
  'insurance_provider': 'SecureLife',
  'chronic_flag': 0,
  'registration_date': '12/27/2025',
  'visit_id': 2200,
  'visit_date': '1/1/2026',
  'department': 'ICU',
  'visit_type': 'ICU',
  'length_of_stay_hours': 78.42,
  'risk_score': 'High',
  'doctor_id': 107,
  'bill_id': 2200,
  'billed_amount': 88539.01,
  'approved_amount': nan,
  'claim_status': 'Rejected',
  'payment_days': nan,
  'billing_date': '2026-01-06'},
 {'patient_id': 445,
  'age': 67,
  'gender': 'F',
  'city': 'Pune',
  'insurance_provider': 'SecureLife',
  'chronic_flag': 0,
  'registration_date': '12/27/2025',
  'visit_id': 2203,
  'visit_date': '1/1/2026',
  'department': 'General',
  'visit_type': 'OPD',
  'length_of_stay_hours': 0.5,
  'risk_score': 'Low',
  'doctor_id': 190,
  'bill_id': 2203,
  'billed_amount': 576.41,
  'approved_amount': 494.23,
  'claim_status': 'Paid',
  'payment_days': 13.0,
  'billing_date': '2026-01-08'},
 {'patient_id': 450,
  'age': 86,
  'gender': 'M',
  'city': 'Pune',
  'insurance_provider': 'SecureLife',
  'chronic_flag': 0,
  'registration_date': '11/26/2025',
  'visit_id': 2223,
  'visit_date': '1/1/2026',
  'department': 'Orthopedics',
  'visit_type': 'OPD',
  'length_of_stay_hours': 20.03,
  'risk_score': 'Low',
  'doctor_id': 104,
  'bill_id': 2223,
  'billed_amount': 29870.56,
  'approved_amount': 2947.8,
  'claim_status': 'Pending',
  'payment_days': nan,
  'billing_date': '2026-01-20'},
 {'patient_id': 477,
  'age': 16,
  'gender': 'F',
  'city': 'Delhi',
  'insurance_provider': 'HealthPlus',
  'chronic_flag': 0,
  'registration_date': '12/17/2025',
  'visit_id': 2384,
  'visit_date': '1/1/2026',
  'department': 'General',
  'visit_type': 'ICU',
  'length_of_stay_hours': 16.78,
  'risk_score': 'Medium',
  'doctor_id': 176,
  'bill_id': 2384,
  'billed_amount': 14101.16,
  'approved_amount': 2589.34,
  'claim_status': 'Pending',
  'payment_days': 38.0,
  'billing_date': '2026-01-16'},
 {'patient_id': 525,
  'age': 24,
  'gender': 'F',
  'city': 'Hyderabad',
  'insurance_provider': 'CareOne',
  'chronic_flag': 0,
  'registration_date': '11/2/2025',
  'visit_id': 2648,
  'visit_date': '1/1/2026',
  'department': 'General',
  'visit_type': 'OPD',
  'length_of_stay_hours': 8.59,
  'risk_score': 'Low',
  'doctor_id': 176,
  'bill_id': 2648,
  'billed_amount': 6354.88,
  'approved_amount': nan,
  'claim_status': 'Pending',
  'payment_days': nan,
  'billing_date': '2026-01-13'},
 {'patient_id': 527,
  'age': 49,
  'gender': 'F',
  'city': 'Mumbai',
  'insurance_provider': 'SecureLife',
  'chronic_flag': 1,
  'registration_date': '11/4/2025',
  'visit_id': 2659,
  'visit_date': '1/1/2026',
  'department': 'ICU',
  'visit_type': 'ICU',
  'length_of_stay_hours': 37.05,
  'risk_score': 'High',
  'doctor_id': 158,
  'bill_id': 2659,
  'billed_amount': 88539.01,
  'approved_amount': 8834.63,
  'claim_status': 'Rejected',
  'payment_days': nan,
  'billing_date': '2026-01-20'},
 {'patient_id': 553,
  'age': 9,
  'gender': 'F',
  'city': 'Mumbai',
  'insurance_provider': 'HealthPlus',
  'chronic_flag': 1,
  'registration_date': '9/5/2025',
  'visit_id': 2791,
  'visit_date': '1/1/2026',
  'department': 'General',
  'visit_type': 'OPD',
  'length_of_stay_hours': 22.41,
  'risk_score': 'Low',
  'doctor_id': 130,
  'bill_id': 2791,
  'billed_amount': 22362.64,
  'approved_amount': 19089.8,
  'claim_status': 'Paid',
  'payment_days': 41.0,
  'billing_date': '2026-01-20'},
 {'patient_id': 555,
  'age': 28,
  'gender': 'F',
  'city': 'Bangalore',
  'insurance_provider': 'HealthPlus',
  'chronic_flag': 0,
  'registration_date': '5/18/2025',
  'visit_id': 2804,
  'visit_date': '1/1/2026',
  'department': 'General',
  'visit_type': 'OPD',
  'length_of_stay_hours': 12.16,
  'risk_score': 'Low',
  'doctor_id': 153,
  'bill_id': 2804,
  'billed_amount': 13094.56,
  'approved_amount': 12003.28,
  'claim_status': 'Paid',
  'payment_days': 17.0,
  'billing_date': '2026-01-20'},
 {'patient_id': 605,
  'age': 45,
  'gender': 'F',
  'city': 'Bangalore',
  'insurance_provider': 'HealthPlus',
  'chronic_flag': 1,
  'registration_date': '12/20/2025',
  'visit_id': 3070,
  'visit_date': '1/1/2026',
  'department': 'ICU',
  'visit_type': 'ICU',
  'length_of_stay_hours': 76.6,
  'risk_score': 'High',
  'doctor_id': 102,
  'bill_id': 3070,
  'billed_amount': 88539.01,
  'approved_amount': nan,
  'claim_status': 'Rejected',
  'payment_days': nan,
  'billing_date': '2026-01-12'},
 {'patient_id': 620,
  'age': 13,
  'gender': 'M',
  'city': 'Hyderabad',
  'insurance_provider': 'CareOne',
  'chronic_flag': 1,
  'registration_date': '12/22/2025',
  'visit_id': 3155,
  'visit_date': '1/1/2026',
  'department': 'ER',
  'visit_type': 'ER',
  'length_of_stay_hours': 17.3,
  'risk_score': 'Medium',
  'doctor_id': 108,
  'bill_id': 3155,
  'billed_amount': 20391.64,
  'approved_amount': 819.67,
  'claim_status': 'Rejected',
  'payment_days': nan,
  'billing_date': '2026-01-11'},
 {'patient_id': 639,
  'age': 32,
  'gender': 'M',
  'city': 'Bangalore',
  'insurance_provider': 'CareOne',
  'chronic_flag': 1,
  'registration_date': '7/16/2025',
  'visit_id': 3243,
  'visit_date': '1/1/2026',
  'department': 'Orthopedics',
  'visit_type': 'OPD',
  'length_of_stay_hours': 18.73,
  'risk_score': 'Low',
  'doctor_id': 107,
  'bill_id': 3243,
  'billed_amount': 23036.16,
  'approved_amount': 21613.64,
  'claim_status': 'Paid',
  'payment_days': 13.0,
  'billing_date': '2026-01-05'},
 {'patient_id': 655,
  'age': 15,
  'gender': 'M',
  'city': 'Pune',
  'insurance_provider': 'MediCareX',
  'chronic_flag': 0,
  'registration_date': '3/26/2025',
  'visit_id': 3334,
  'visit_date': '1/1/2026',
  'department': 'General',
  'visit_type': 'OPD',
  'length_of_stay_hours': 0.5,
  'risk_score': 'Low',
  'doctor_id': 168,
  'bill_id': 3334,
  'billed_amount': 553.3,
  'approved_amount': 476.95,
  'claim_status': 'Paid',
  'payment_days': 42.0,
  'billing_date': '2026-01-13'},
 {'patient_id': 657,
  'age': 1,
  'gender': 'M',
  'city': 'Hyderabad',
  'insurance_provider': 'SecureLife',
  'chronic_flag': 0,
  'registration_date': '12/16/2025',
  'visit_id': 3347,
  'visit_date': '1/1/2026',
  'department': 'General',
  'visit_type': 'OPD',
  'length_of_stay_hours': 12.82,
  'risk_score': 'Low',
  'doctor_id': 128,
  'bill_id': 3347,
  'billed_amount': 12455.05,
  'approved_amount': nan,
  'claim_status': 'Pending',
  'payment_days': nan,
  'billing_date': '2026-01-04'},
 {'patient_id': 706,
  'age': 11,
  'gender': 'F',
  'city': 'Pune',
  'insurance_provider': 'HealthPlus',
  'chronic_flag': 0,
  'registration_date': '10/2/2025',
  'visit_id': 3557,
  'visit_date': '1/1/2026',
  'department': 'Cardiology',
  'visit_type': 'OPD',
  'length_of_stay_hours': 34.03,
  'risk_score': 'Low',
  'doctor_id': 103,
  'bill_id': 3557,
  'billed_amount': 55006.03,
  'approved_amount': nan,
  'claim_status': 'Rejected',
  'payment_days': nan,
  'billing_date': '2026-01-03'},
 {'patient_id': 741,
  'age': 62,
  'gender': 'M',
  'city': 'Delhi',
  'insurance_provider': 'MediCareX',
  'chronic_flag': 0,
  'registration_date': '12/9/2025',
  'visit_id': 3731,
  'visit_date': '1/1/2026',
  'department': 'General',
  'visit_type': 'OPD',
  'length_of_stay_hours': 16.29,
  'risk_score': 'Low',
  'doctor_id': 175,
  'bill_id': 3731,
  'billed_amount': 11231.94,
  'approved_amount': 10985.81,
  'claim_status': 'Paid',
  'payment_days': 47.0,
  'billing_date': '2026-01-19'},
 {'patient_id': 778,
  'age': 79,
  'gender': 'F',
  'city': 'Pune',
  'insurance_provider': 'CareOne',
  'chronic_flag': 0,
  'registration_date': '9/19/2025',
  'visit_id': 3927,
  'visit_date': '1/1/2026',
  'department': 'ER',
  'visit_type': 'ER',
  'length_of_stay_hours': 1.68,
  'risk_score': 'Medium',
  'doctor_id': 160,
  'bill_id': 3927,
  'billed_amount': 1768.7,
  'approved_amount': 643.73,
  'claim_status': 'Pending',
  'payment_days': 22.0,
  'billing_date': '2026-01-05'},
 {'patient_id': 847,
  'age': 36,
  'gender': 'F',
  'city': 'Delhi',
  'insurance_provider': 'CareOne',
  'chronic_flag': 1,
  'registration_date': '9/27/2025',
  'visit_id': 4266,
  'visit_date': '1/1/2026',
  'department': 'Neurology',
  'visit_type': 'ICU',
  'length_of_stay_hours': 28.15,
  'risk_score': 'High',
  'doctor_id': 126,
  'bill_id': 4266,
  'billed_amount': 48079.64,
  'approved_amount': 43614.99,
  'claim_status': 'Paid',
  'payment_days': 18.0,
  'billing_date': '2026-01-10'},
 {'patient_id': 858,
  'age': 87,
  'gender': 'F',
  'city': 'Bangalore',
  'insurance_provider': 'CareOne',
  'chronic_flag': 1,
  'registration_date': '3/22/2025',
  'visit_id': 4332,
  'visit_date': '1/1/2026',
  'department': 'ICU',
  'visit_type': 'ICU',
  'length_of_stay_hours': 67.35,
  'risk_score': 'High',
  'doctor_id': 199,
  'bill_id': 4332,
  'billed_amount': 88539.01,
  'approved_amount': nan,
  'claim_status': 'Rejected',
  'payment_days': nan,
  'billing_date': '2026-01-11'},
 {'patient_id': 957,
  'age': 11,
  'gender': 'F',
  'city': 'Hyderabad',
  'insurance_provider': 'SecureLife',
  'chronic_flag': 1,
  'registration_date': '12/28/2025',
  'visit_id': 4785,
  'visit_date': '1/1/2026',
  'department': 'General',
  'visit_type': 'ER',
  'length_of_stay_hours': 17.85,
  'risk_score': 'Medium',
  'doctor_id': 162,
  'bill_id': 4785,
  'billed_amount': 14438.86,
  'approved_amount': 14255.83,
  'claim_status': 'Paid',
  'payment_days': 17.0,
  'billing_date': '2026-01-20'},
 {'patient_id': 965,
  'age': 23,
  'gender': 'M',
  'city': 'Delhi',
  'insurance_provider': 'SecureLife',
  'chronic_flag': 1,
  'registration_date': '11/28/2025',
  'visit_id': 4828,
  'visit_date': '1/1/2026',
  'department': 'General',
  'visit_type': 'OPD',
  'length_of_stay_hours': 5.38,
  'risk_score': 'Low',
  'doctor_id': 158,
  'bill_id': 4828,
  'billed_amount': 4039.98,
  'approved_amount': 3965.45,
  'claim_status': 'Paid',
  'payment_days': 50.0,
  'billing_date': '2026-01-15'},
 {'patient_id': 1024,
  'age': 38,
  'gender': 'F',
  'city': 'Chennai',
  'insurance_provider': 'SecureLife',
  'chronic_flag': 1,
  'registration_date': '11/15/2025',
  'visit_id': 5086,
  'visit_date': '1/1/2026',
  'department': 'ER',
  'visit_type': 'OPD',
  'length_of_stay_hours': 5.88,
  'risk_score': 'Low',
  'doctor_id': 134,
  'bill_id': 5086,
  'billed_amount': 8192.33,
  'approved_amount': 7741.78,
  'claim_status': 'Paid',
  'payment_days': 5.0,
  'billing_date': '2026-01-10'},
 {'patient_id': 1049,
  'age': 29,
  'gender': 'F',
  'city': 'Delhi',
  'insurance_provider': 'SecureLife',
  'chronic_flag': 1,
  'registration_date': '2/19/2025',
  'visit_id': 5223,
  'visit_date': '1/1/2026',
  'department': 'General',
  'visit_type': 'OPD',
  'length_of_stay_hours': 16.3,
  'risk_score': 'Low',
  'doctor_id': 105,
  'bill_id': 5223,
  'billed_amount': 14318.07,
  'approved_amount': 12981.28,
  'claim_status': 'Paid',
  'payment_days': 16.0,
  'billing_date': '2026-01-20'},
 {'patient_id': 1057,
  'age': 66,
  'gender': 'F',
  'city': 'Bangalore',
  'insurance_provider': 'CareOne',
  'chronic_flag': 0,
  'registration_date': '4/1/2025',
  'visit_id': 5252,
  'visit_date': '1/1/2026',
  'department': 'ER',
  'visit_type': 'ER',
  'length_of_stay_hours': 6.91,
  'risk_score': 'Low',
  'doctor_id': 126,
  'bill_id': 5252,
  'billed_amount': 7152.64,
  'approved_amount': 6226.76,
  'claim_status': 'Paid',
  'payment_days': 45.0,
  'billing_date': '2026-01-20'},
 {'patient_id': 1140,
  'age': 26,
  'gender': 'M',
  'city': 'Hyderabad',
  'insurance_provider': 'MediCareX',
  'chronic_flag': 1,
  'registration_date': '12/30/2025',
  'visit_id': 5645,
  'visit_date': '1/1/2026',
  'department': 'Neurology',
  'visit_type': 'OPD',
  'length_of_stay_hours': 38.06,
  'risk_score': 'Medium',
  'doctor_id': 147,
  'bill_id': 5645,
  'billed_amount': 64591.88,
  'approved_amount': nan,
  'claim_status': 'Pending',
  'payment_days': nan,
  'billing_date': '2026-01-20'},
 {'patient_id': 1140,
  'age': 26,
  'gender': 'M',
  'city': 'Hyderabad',
  'insurance_provider': 'MediCareX',
  'chronic_flag': 1,
  'registration_date': '12/30/2025',
  'visit_id': 5647,
  'visit_date': '1/1/2026',
  'department': 'ER',
  'visit_type': 'OPD',
  'length_of_stay_hours': 0.5,
  'risk_score': 'Low',
  'doctor_id': 135,
  'bill_id': 5647,
  'billed_amount': 647.36,
  'approved_amount': 563.73,
  'claim_status': 'Paid',
  'payment_days': 16.0,

In [ ]:
import pymongo
import pandas as pd
DB_NAME="hospital_miops"
COLLECTION_MODEL_TABLE="model_table_df"
CONNECTION_URL="now"

client=pymongo.MongoClient(CONNECTION_URL)
db=client[DB_NAME]
model_table_collection=db[COLLECTION_MODEL_TABLE]


model_table=model_table_collection.insert_many(model_table_df)

In [84]:
model_table_df=pd.DataFrame(list(model_table_collection.find()))
model_table_df.head()

,_id,patient_id,age,gender,city,insurance_provider,chronic_flag,registration_date,visit_id,visit_date,...,visit_type,length_of_stay_hours,risk_score,doctor_id,bill_id,billed_amount,approved_amount,claim_status,payment_days,billing_date
0,6a32926c02c411335d6fa4a0,3393,43,M,Hyderabad,HealthPlus,0,2025-07-10,1510,2025-01-20,...,ICU,31.37,Medium,135,1510,16529.35,0.00,Rejected,7.0,2025-04-24
1,6a32926c02c411335d6fa4bd,4887,31,M,Pune,HealthPlus,1,2025-10-01,9727,2025-01-20,...,ICU,3.47,Low,160,9727,15948.64,0.00,Rejected,2.0,2025-12-21
2,6a32926c02c411335d6fa4d8,493,46,M,Bangalore,MediCareX,1,2025-06-07,19504,2025-01-20,...,ICU,18.44,Low,144,19504,20313.48,20313.48,Paid,17.0,2025-05-06
3,6a32926c02c411335d6fa4de,1549,58,F,Hyderabad,SecureLife,0,2025-03-13,21687,2025-01-20,...,ICU,37.49,Medium,145,21687,25607.61,16108.89,Pending,2.0,2025-04-23
4,6a32926c02c411335d6fa4ec,434,57,F,Chennai,MediCareX,0,2026-01-03,2754,2025-01-21,...,ICU,8.49,Low,136,2754,500.00,500.00,Paid,19.0,2025-05-11

In [85]:
if"_id" in model_table_df.columns:
    model_table_df.drop("_id",axis=1,inplace=True)
    
model_table_df.head()

,patient_id,age,gender,city,insurance_provider,chronic_flag,registration_date,visit_id,visit_date,department,visit_type,length_of_stay_hours,risk_score,doctor_id,bill_id,billed_amount,approved_amount,claim_status,payment_days,billing_date
0,3393,43,M,Hyderabad,HealthPlus,0,2025-07-10,1510,2025-01-20,ICU,ICU,31.37,Medium,135,1510,16529.35,0.00,Rejected,7.0,2025-04-24
1,4887,31,M,Pune,HealthPlus,1,2025-10-01,9727,2025-01-20,ER,ICU,3.47,Low,160,9727,15948.64,0.00,Rejected,2.0,2025-12-21
2,493,46,M,Bangalore,MediCareX,1,2025-06-07,19504,2025-01-20,ICU,ICU,18.44,Low,144,19504,20313.48,20313.48,Paid,17.0,2025-05-06
3,1549,58,F,Hyderabad,SecureLife,0,2025-03-13,21687,2025-01-20,General,ICU,37.49,Medium,145,21687,25607.61,16108.89,Pending,2.0,2025-04-23
4,434,57,F,Chennai,MediCareX,0,2026-01-03,2754,2025-01-21,ICU,ICU,8.49,Low,136,2754,500.00,500.00,Paid,19.0,2025-05-11

In [86]:
conn.close()
print("Database connection closed successfully")

Database connection closed successfully