### import csv and check shape

In [18]:
import pandas as pd
import os

In [ ]:
billing = pd.read_csv("data/billing.csv")
visits = pd.read_csv("data/visits.csv")
patient = pd.read_csv("data/patients.csv")

print("patient shape :",patient.shape)
print("billing shape :",billing.shape)
print("visits shape :",visits.shape)

patient shape : (5000, 7)
billing shape : (25000, 7)
visits shape : (25000, 8)

In [54]:

billing_data= billing.to_dict(orient="records")
billing_data

[{'bill_id': 1,
  'visit_id': 1,
  'billed_amount': 23577.37,
  'approved_amount': 0.0,
  'claim_status': 'Rejected',
  'payment_days': 16.0,
  'billing_date': '2025-06-18'},
 {'bill_id': 2,
  'visit_id': 2,
  'billed_amount': 38178.81,
  'approved_amount': 38178.81,
  'claim_status': 'Paid',
  'payment_days': 18.0,
  'billing_date': '2025-10-09'},
 {'bill_id': 3,
  'visit_id': 3,
  'billed_amount': 5038.97,
  'approved_amount': 5038.97,
  'claim_status': 'Paid',
  'payment_days': nan,
  'billing_date': '2025-01-20'},
 {'bill_id': 4,
  'visit_id': 4,
  'billed_amount': 22813.34,
  'approved_amount': 22813.34,
  'claim_status': 'Paid',
  'payment_days': 16.0,
  'billing_date': '2025-12-24'},
 {'bill_id': 5,
  'visit_id': 5,
  'billed_amount': 27106.95,
  'approved_amount': 27106.95,
  'claim_status': 'Paid',
  'payment_days': 14.0,
  'billing_date': '2025-09-23'},
 {'bill_id': 6,
  'visit_id': 6,
  'billed_amount': 19453.77,
  'approved_amount': 19453.77,
  'claim_status': 'Paid',
  'payment_days': 17.0,
  'billing_date': '2026-01-12'},
 {'bill_id': 7,
  'visit_id': 7,
  'billed_amount': 6269.47,
  'approved_amount': 4437.65,
  'claim_status': 'Pending',
  'payment_days': 10.0,
  'billing_date': '2025-11-16'},
 {'bill_id': 8,
  'visit_id': 8,
  'billed_amount': 38178.73,
  'approved_amount': 38178.73,
  'claim_status': 'Paid',
  'payment_days': 6.0,
  'billing_date': '2025-06-27'},
 {'bill_id': 9,
  'visit_id': 9,
  'billed_amount': 21258.56,
  'approved_amount': 21258.56,
  'claim_status': 'Paid',
  'payment_days': 15.0,
  'billing_date': '2025-10-06'},
 {'bill_id': 10,
  'visit_id': 10,
  'billed_amount': 18161.42,
  'approved_amount': 18161.42,
  'claim_status': 'Paid',
  'payment_days': 13.0,
  'billing_date': '2025-07-16'},
 {'bill_id': 11,
  'visit_id': 11,
  'billed_amount': 67173.53,
  'approved_amount': 67173.53,
  'claim_status': 'Paid',
  'payment_days': 1.0,
  'billing_date': '2025-10-14'},
 {'bill_id': 12,
  'visit_id': 12,
  'billed_amount': 28707.29,
  'approved_amount': 28707.29,
  'claim_status': 'Paid',
  'payment_days': 17.0,
  'billing_date': '2025-04-13'},
 {'bill_id': 13,
  'visit_id': 13,
  'billed_amount': 40519.31,
  'approved_amount': 40519.31,
  'claim_status': 'Paid',
  'payment_days': 11.0,
  'billing_date': '2025-06-05'},
 {'bill_id': 14,
  'visit_id': 14,
  'billed_amount': 13584.7,
  'approved_amount': nan,
  'claim_status': 'Paid',
  'payment_days': 15.0,
  'billing_date': '2025-03-06'},
 {'bill_id': 15,
  'visit_id': 15,
  'billed_amount': 500.0,
  'approved_amount': 500.0,
  'claim_status': 'Paid',
  'payment_days': 17.0,
  'billing_date': '2025-06-23'},
 {'bill_id': 16,
  'visit_id': 16,
  'billed_amount': 35715.64,
  'approved_amount': 35715.64,
  'claim_status': 'Paid',
  'payment_days': 1.0,
  'billing_date': '2025-12-24'},
 {'bill_id': 17,
  'visit_id': 17,
  'billed_amount': 12504.15,
  'approved_amount': 12504.15,
  'claim_status': 'Paid',
  'payment_days': 13.0,
  'billing_date': '2025-11-23'},
 {'bill_id': 18,
  'visit_id': 18,
  'billed_amount': 22747.32,
  'approved_amount': 0.0,
  'claim_status': 'Rejected',
  'payment_days': 6.0,
  'billing_date': '2025-04-17'},
 {'bill_id': 19,
  'visit_id': 19,
  'billed_amount': 27057.64,
  'approved_amount': 0.0,
  'claim_status': 'Rejected',
  'payment_days': 8.0,
  'billing_date': '2025-10-20'},
 {'bill_id': 20,
  'visit_id': 20,
  'billed_amount': 22973.3,
  'approved_amount': 14714.66,
  'claim_status': 'Pending',
  'payment_days': 4.0,
  'billing_date': '2025-10-03'},
 {'bill_id': 21,
  'visit_id': 21,
  'billed_amount': 19675.19,
  'approved_amount': 0.0,
  'claim_status': 'Rejected',
  'payment_days': 21.0,
  'billing_date': '2025-04-18'},
 {'bill_id': 22,
  'visit_id': 22,
  'billed_amount': 31418.34,
  'approved_amount': 31418.34,
  'claim_status': 'Paid',
  'payment_days': nan,
  'billing_date': '2025-11-16'},
 {'bill_id': 23,
  'visit_id': 23,
  'billed_amount': 37342.68,
  'approved_amount': 37342.68,
  'claim_status': 'Paid',
  'payment_days': 19.0,
  'billing_date': '2026-01-06'},
 {'bill_id': 24,
  'visit_id': 24,
  'billed_amount': 23945.34,
  'approved_amount': 0.0,
  'claim_status': 'Rejected',
  'payment_days': 11.0,
  'billing_date': '2025-03-10'},
 {'bill_id': 25,
  'visit_id': 25,
  'billed_amount': 22471.65,
  'approved_amount': 0.0,
  'claim_status': 'Rejected',
  'payment_days': 26.0,
  'billing_date': '2025-05-04'},
 {'bill_id': 26,
  'visit_id': 26,
  'billed_amount': 28546.45,
  'approved_amount': 28546.45,
  'claim_status': 'Paid',
  'payment_days': 8.0,
  'billing_date': '2025-02-09'},
 {'bill_id': 27,
  'visit_id': 27,
  'billed_amount': 17856.85,
  'approved_amount': 0.0,
  'claim_status': 'Rejected',
  'payment_days': 19.0,
  'billing_date': '2025-03-14'},
 {'bill_id': 28,
  'visit_id': 28,
  'billed_amount': 38162.87,
  'approved_amount': nan,
  'claim_status': 'Paid',
  'payment_days': 21.0,
  'billing_date': '2025-09-30'},
 {'bill_id': 29,
  'visit_id': 29,
  'billed_amount': 6851.33,
  'approved_amount': 6851.33,
  'claim_status': 'Paid',
  'payment_days': 12.0,
  'billing_date': '2025-03-23'},
 {'bill_id': 30,
  'visit_id': 30,
  'billed_amount': 16187.46,
  'approved_amount': 16187.46,
  'claim_status': 'Paid',
  'payment_days': 17.0,
  'billing_date': '2025-10-03'},
 {'bill_id': 31,
  'visit_id': 31,
  'billed_amount': 24205.08,
  'approved_amount': 16925.68,
  'claim_status': 'Pending',
  'payment_days': 23.0,
  'billing_date': '2025-06-01'},
 {'bill_id': 32,
  'visit_id': 32,
  'billed_amount': 4515.5,
  'approved_amount': 4515.5,
  'claim_status': 'Paid',
  'payment_days': 13.0,
  'billing_date': '2026-01-15'},
 {'bill_id': 33,
  'visit_id': 33,
  'billed_amount': 10524.42,
  'approved_amount': 0.0,
  'claim_status': 'Rejected',
  'payment_days': 10.0,
  'billing_date': '2025-03-04'},
 {'bill_id': 34,
  'visit_id': 34,
  'billed_amount': 5893.5,
  'approved_amount': 5893.5,
  'claim_status': 'Paid',
  'payment_days': 6.0,
  'billing_date': '2025-06-20'},
 {'bill_id': 35,
  'visit_id': 35,
  'billed_amount': 27633.69,
  'approved_amount': 19531.97,
  'claim_status': 'Pending',
  'payment_days': 1.0,
  'billing_date': '2025-06-04'},
 {'bill_id': 36,
  'visit_id': 36,
  'billed_amount': 45946.24,
  'approved_amount': 45946.24,
  'claim_status': 'Paid',
  'payment_days': 14.0,
  'billing_date': '2025-08-31'},
 {'bill_id': 37,
  'visit_id': 37,
  'billed_amount': 27971.27,
  'approved_amount': 27971.27,
  'claim_status': 'Paid',
  'payment_days': 17.0,
  'billing_date': '2025-02-06'},
 {'bill_id': 38,
  'visit_id': 38,
  'billed_amount': 22795.89,
  'approved_amount': 16428.31,
  'claim_status': 'Pending',
  'payment_days': 6.0,
  'billing_date': '2025-03-03'},
 {'bill_id': 39,
  'visit_id': 39,
  'billed_amount': 17192.08,
  'approved_amount': 17192.08,
  'claim_status': 'Paid',
  'payment_days': 11.0,
  'billing_date': '2025-03-28'},
 {'bill_id': 40,
  'visit_id': 40,
  'billed_amount': 73969.13,
  'approved_amount': 73969.13,
  'claim_status': 'Paid',
  'payment_days': 2.0,
  'billing_date': '2025-10-31'},
 {'bill_id': 41,
  'visit_id': 41,
  'billed_amount': 12924.18,
  'approved_amount': 12924.18,
  'claim_status': 'Paid',
  'payment_days': nan,
  'billing_date': '2025-06-03'},
 {'bill_id': 42,
  'visit_id': 42,
  'billed_amount': 42479.44,
  'approved_amount': nan,
  'claim_status': 'Pending',
  'payment_days': 2.0,
  'billing_date': '2025-08-02'},
 {'bill_id': 43,
  'visit_id': 43,
  'billed_amount': 21254.64,
  'approved_amount': 21254.64,
  'claim_status': 'Paid',
  'payment_days': 24.0,
  'billing_date': '2025-06-02'},
 {'bill_id': 44,
  'visit_id': 44,
  'billed_amount': 48235.07,
  'approved_amount': 48235.07,
  'claim_status': 'Paid',
  'payment_days': 10.0,
  'billing_date': '2025-12-09'},
 {'bill_id': 45,
  'visit_id': 45,
  'billed_amount': 16183.51,
  'approved_amount': 12921.2,
  'claim_status': 'Pending',
  'payment_days': 17.0,
  'billing_date': '2025-04-05'},
 {'bill_id': 46,
  'visit_id': 46,
  'billed_amount': 32966.33,
  'approved_amount': 32966.33,
  'claim_status': 'Paid',
  'payment_days': 9.0,
  'billing_date': '2025-06-30'},
 {'bill_id': 47,
  'visit_id': 47,
  'billed_amount': 27393.16,
  'approved_amount': 0.0,
  'claim_status': 'Rejected',
  'payment_days': 8.0,
  'billing_date': '2025-08-09'},
 {'bill_id': 48,
  'visit_id': 48,
  'billed_amount': 27314.84,
  'approved_amount': 27314.84,
  'claim_status': 'Paid',
  'payment_days': 8.0,
  'billing_date': '2025-04-30'},
 {'bill_id': 49,
  'visit_id': 49,
  'billed_amount': 25679.0,
  'approved_amount': 18086.57,
  'claim_status': 'Pending',
  'payment_days': 29.0,
  'billing_date': '2025-11-11'},
 {'bill_id': 50,
  'visit_id': 50,
  'billed_amount': 26911.8,
  'approved_amount': 26911.8,
  'claim_status': 'Paid',
  'payment_days': 9.0,
  'billing_date': '2025-10-27'},
 {'bill_id': 51,
  'visit_id': 51,
  'billed_amount': 27290.81,
  'approved_amount': 18977.87,
  'claim_status': 'Pending',
  'payment_days': 25.0,
  'billing_date': '2025-08-13'},
 {'bill_id': 52,
  'visit_id': 52,
  'billed_amount': 24578.38,
  'approved_amount': 14552.77,
  'claim_status': 'Pending',
  'payment_days': 13.0,
  'billing_date': '2025-09-18'},
 {'bill_id': 53,
  'visit_id': 53,
  'billed_amount': 2465.08,
  'approved_amount': 2465.08,
  'claim_status': 'Paid',
  'payment_days': 17.0,
  'billing_date': '2026-01-13'},
 {'bill_id': 54,
  'visit_id': 54,
  'billed_amount': 20194.57,
  'approved_amount': 0.0,
  'claim_status': 'Rejected',
  'payment_days': 17.0,
  'billing_date': '2025-11-07'},
 {'bill_id': 55,
  'visit_id': 55,
  'billed_amount': 16188.62,
  'approved_amount': 16188.62,
  'claim_status': 'Paid',
  'payment_days': 22.0,
  'billing_date': '2025-09-27'},
 {'bill_id': 56,
  'visit_id': 56,
  'billed_amount': 38872.98,
  'approved_amount': nan,
  'claim_status': 'Paid',
  'payment_days': 12.0,
  'billing_date': '2025-06-08'},
 {'bill_id': 57,
  'visit_id': 57,
  'billed_amount': 25262.34,
  'approved_amount': 0.0,
  'claim_status': 'Rejected',
  'payment_days': 18.0,
  'billing_date': '2026-01-06'},
 {'bill_id': 58,
  'visit_id': 58,
  'billed_amount': 3753.73,
  'approved_amount': 2369.49,
  'claim_status': 'Pending',
  'payment_days': 12.0,
  'billing_date': '2026-01-07'},
 {'bill_id': 59,
  'visit_id': 59,
  'billed_amount': 29548.02,
  'approved_amount': 29548.02,
  'claim_status': 'Paid',
  'payment_days': 24.0,
  'billing_date': '2025-08-15'},
 {'bill_id': 60,
  'visit_id': 60,
  'billed_amount': 19675.77,
  'approved_amount': 19675.77,
  'claim_status': 'Paid',
  'payment_days': 12.0,
  'billing_date': '2025-09-06'},
 {'bill_id': 61,
  'visit_id': 61,
  'billed_amount': 13673.72,
  'approved_amount': 0.0,
  'claim_status': 'Rejected',
  'payment_days': 7.0,
  'billing_date': '2025-11-19'},
 {'bill_id': 62,
  'visit_id': 62,
  'billed_amount': 6278.88,
  'approved_amount': 6278.88,
  'claim_status': 'Paid',
  'payment_days': 11.0,
  'billing_date': '2025-11-18'},
 {'bill_id': 63,
  'visit_id': 63,
  'billed_amount': 15201.02,
  'approved_amount': 15201.02,
  'claim_status': 'Paid',
  'payment_days': 15.0,
  'billing_date': '2025-11-01'},
 {'bill_id': 64,
  'visit_id': 64,
  'billed_amount': 18861.19,
  'approved_amount': 18861.19,
  'claim_status': 'Paid',
  'payment_days': 18.0,
  'billing_date': '2025-10-08'},
 {'bill_id': 65,
  'visit_id': 65,
  'billed_amount': 31990.78,
  'approved_amount': 21941.52,
  'claim_status': 'Pending',
  'payment_days': 2.0,
  'billing_date': '2025-10-02'},
 {'bill_id': 66,
  'visit_id': 66,
  'billed_amount': 28126.25,
  'approved_amount': 28126.25,
  'claim_status': 'Paid',
  'payment_days': nan,
  'billing_date': '2025-07-15'},
 {'bill_id': 67,
  'visit_id': 67,
  'billed_amount': 13592.74,
  'approved_amount': 13592.74,
  'claim_status': 'Paid',
  'payment_days': 16.0,
  'billing_date': '2025-04-10'},
 {'bill_id': 68,
  'visit_id': 68,
  'billed_amount': 3202.97,
  'approved_amount': 2641.89,
  'claim_status': 'Pending',
  'payment_days': 12.0,
  'billing_date': '2025-08-01'},
 {'bill_id': 69,
  'visit_id': 69,
  'billed_amount': 14662.16,
  'approved_amount': 14662.16,
  'claim_status': 'Paid',
  'payment_days': 15.0,
  'billing_date': '2025-06-23'},
 {'bill_id': 70,
  'visit_id': 70,
  'billed_amount': 19288.95,
  'approved_amount': 11886.22,
  'claim_status': 'Pending',
  'payment_days': 15.0,
  'billing_date': '2025-06-24'},
 {'bill_id': 71,
  'visit_id': 71,
  'billed_amount': 6302.28,
  'approved_amount': 6302.28,
  'claim_status': 'Paid',
  'payment_days': 10.0,
  'billing_date': '2025-04-15'},
 {'bill_id': 72,
  'visit_id': 72,
  'billed_amount': 25833.24,
  'approved_amount': 25833.24,
  'claim_status': 'Paid',
  'payment_days': 13.0,
  'billing_date': '2025-02-06'},
 {'bill_id': 73,
  'visit_id': 73,
  'billed_amount': 8644.27,
  'approved_amount': 8644.27,
  'claim_status': 'Paid',
  'payment_days': 9.0,
  'billing_date': '2025-07-20'},
 {'bill_id': 74,
  'visit_id': 74,
  'billed_amount': 22838.64,
  'approved_amount': 0.0,
  'claim_status': 'Rejected',
  'payment_days': 22.0,
  'billing_date': '2025-12-13'},
 {'bill_id': 75,
  'visit_id': 75,
  'billed_amount': 3477.97,
  'approved_amount': 3477.97,
  'claim_status': 'Paid',
  'payment_days': 5.0,
  'billing_date': '2025-12-15'},
 {'bill_id': 76,
  'visit_id': 76,
  'billed_amount': 20281.3,
  'approved_amount': 20281.3,
  'claim_status': 'Paid',
  'payment_days': 8.0,
  'billing_date': '2025-04-18'},
 {'bill_id': 77,
  'visit_id': 77,
  'billed_amount': 16469.11,
  'approved_amount': 0.0,
  'claim_status': 'Rejected',
  'payment_days': 2.0,
  'billing_date': '2025-10-27'},
 {'bill_id': 78,
  'visit_id': 78,
  'billed_amount': 14754.72,
  'approved_amount': 14754.72,
  'claim_status': 'Paid',
  'payment_days': 6.0,
  'billing_date': '2025-05-14'},
 {'bill_id': 79,
  'visit_id': 79,
  'billed_amount': 15595.63,
  'approved_amount': 15595.63,
  'claim_status': 'Paid',
  'payment_days': 18.0,
  'billing_date': '2025-10-08'},
 {'bill_id': 80,
  'visit_id': 80,
  'billed_amount': 35291.26,
  'approved_amount': 35291.26,
  'claim_status': 'Paid',
  'payment_days': 14.0,
  'billing_date': '2025-04-29'},
 {'bill_id': 81,
  'visit_id': 81,
  'billed_amount': 19121.91,
  'approved_amount': 0.0,
  'claim_status': 'Rejected',
  'payment_days': 1.0,
  'billing_date': '2025-08-22'},
 {'bill_id': 82,
  'visit_id': 82,
  'billed_amount': 35287.06,
  'approved_amount': 35287.06,
  'claim_status': 'Paid',
  'payment_days': 19.0,
  'billing_date': '2025-08-02'},
 {'bill_id': 83,
  'visit_id': 83,
  'billed_amount': 17852.54,
  'approved_amount': 17852.54,
  'claim_status': 'Paid',
  'payment_days': 9.0,
  'billing_date': '2025-03-16'},
 {'bill_id': 84,
  'visit_id': 84,
  'billed_amount': 11212.48,
  'approved_amount': 11212.48,
  'claim_status': 'Paid',
  'payment_days': 7.0,
  'billing_date': '2026-01-02'},
 {'bill_id': 85,
  'visit_id': 85,
  'billed_amount': 22294.34,
  'approved_amount': 22294.34,
  'claim_status': 'Paid',
  'payment_days': 12.0,
  'billing_date': '2025-10-30'},
 {'bill_id': 86,
  'visit_id': 86,
  'billed_amount': 30899.47,
  'approved_amount': 30899.47,
  'claim_status': 'Paid',
  'payment_days': 8.0,
  'billing_date': '2025-12-24'},
 {'bill_id': 87,
  'visit_id': 87,
  'billed_amount': 19498.13,
  'approved_amount': 19498.13,
  'claim_status': 'Paid',
  'payment_days': 15.0,
  'billing_date': '2025-05-28'},
 {'bill_id': 88,
  'visit_id': 88,
  'billed_amount': 37790.01,
  'approved_amount': 37790.01,
  'claim_status': 'Paid',
  'payment_days': 16.0,
  'billing_date': '2025-06-24'},
 {'bill_id': 89,
  'visit_id': 89,
  'billed_amount': 20657.89,
  'approved_amount': 13996.82,
  'claim_status': 'Pending',
  'payment_days': 1.0,
  'billing_date': '2025-03-25'},
 {'bill_id': 90,
  'visit_id': 90,
  'billed_amount': 12767.99,
  'approved_amount': 12767.99,
  'claim_status': 'Paid',
  'payment_days': 10.0,
  'billing_date': '2025-07-01'},
 {'bill_id': 91,
  'visit_id': 91,
  'billed_amount': 27703.97,
  'approved_amount': nan,
  'claim_status': 'Paid',
  'payment_days': 14.0,
  'billing_date': '2025-06-09'},
 {'bill_id': 92,
  'visit_id': 92,
  'billed_amount': 11434.68,
  'approved_amount': 0.0,
  'claim_status': 'Rejected',
  'payment_days': 9.0,
  'billing_date': '2025-09-21'},
 {'bill_id': 93,
  'visit_id': 93,
  'billed_amount': 31323.86,
  'approved_amount': 0.0,
  'claim_status': 'Rejected',
  'payment_days': 21.0,
  'billing_date': '2026-01-17'},
 {'bill_id': 94,
  'visit_id': 94,
  'billed_amount': 2693.11,
  'approved_amount': nan,
  'claim_status': 'Pending',
  'payment_days': 14.0,
  'billing_date': '2026-01-09'},
 {'bill_id': 95,
  'visit_id': 95,
  'billed_amount': 3681.58,
  'approved_amount': 3135.24,
  'claim_status': 'Pending',
  'payment_days': 16.0,
  'billing_date': '2025-10-05'},
 {'bill_id': 96,
  'visit_id': 96,
  'billed_amount': 22328.26,
  'approved_amount': 0.0,
  'claim_status': 'Rejected',
  'payment_days': 17.0,
  'billing_date': '2026-01-03'},
 {'bill_id': 97,
  'visit_id': 97,
  'billed_amount': 10536.41,
  'approved_amount': 10536.41,
  'claim_status': 'Paid',
  'payment_days': 15.0,
  'billing_date': '2025-09-29'},
 {'bill_id': 98,
  'visit_id': 98,
  'billed_amount': 25744.31,
  'approved_amount': nan,
  'claim_status': 'Pending',
  'payment_days': 15.0,
  'billing_date': '2025-02-22'},
 {'bill_id': 99,
  'visit_id': 99,
  'billed_amount': 37780.91,
  'approved_amount': 0.0,
  'claim_status': 'Rejected',
  'payment_days': 19.0,
  'billing_date': '2025-11-25'},
 {'bill_id': 100,
  'visit_id': 100,
  'billed_amount': 48517.28,
  'approved_amount': 48517.28,
  'claim_status': 'Paid',
  'payment_days': 5.0,
  'billing_date': '2025-04-21'},
 {'bill_id': 101,
  'visit_id': 101,
  'billed_amount': 17551.46,
  'approved_amount': 17551.46,
  'claim_status': 'Paid',
  'payment_days': 21.0,
  'billing_date': '2025-09-24'},
 {'bill_id': 102,
  'visit_id': 102,
  'billed_amount': 12665.02,
  'approved_amount': 12665.02,
  'claim_status': 'Paid',
  'payment_days': 10.0,
  'billing_date': '2025-07-05'},
 {'bill_id': 103,
  'visit_id': 103,
  'billed_amount': 24050.53,
  'approved_amount': 0.0,
  'claim_status': 'Rejected',
  'payment_days': 6.0,
  'billing_date': '2025-05-29'},
 {'bill_id': 104,
  'visit_id': 104,
  'billed_amount': 36494.63,
  'approved_amount': 36494.63,
  'claim_status': 'Paid',
  'payment_days': 15.0,
  'billing_date': '2025-04-26'},
 {'bill_id': 105,
  'visit_id': 105,
  'billed_amount': 27755.16,
  'approved_amount': 27755.16,
  'claim_status': 'Paid',
  'payment_days': 18.0,
  'billing_date': '2025-08-07'},
 {'bill_id': 106,
  'visit_id': 106,
  'billed_amount': 37210.04,
  'approved_amount': 29482.68,
  'claim_status': 'Pending',
  'payment_days': 7.0,
  'billing_date': '2025-02-12'},
 {'bill_id': 107,
  'visit_id': 107,
  'billed_amount': 10425.86,
  'approved_amount': 10425.86,
  'claim_status': 'Paid',
  'payment_days': 11.0,
  'billing_date': '2025-02-13'},
 {'bill_id': 108,
  'visit_id': 108,
  'billed_amount': 36760.4,
  'approved_amount': 23524.0,
  'claim_status': 'Pending',
  'payment_days': 11.0,
  'billing_date': '2025-08-27'},
 {'bill_id': 109,
  'visit_id': 109,
  'billed_amount': 1233.62,
  'approved_amount': 911.46,
  'claim_status': 'Pending',
  'payment_days': nan,
  'billing_date': '2025-06-20'},
 {'bill_id': 110,
  'visit_id': 110,
  'billed_amount': 30151.08,
  'approved_amount': 22537.77,
  'claim_status': 'Pending',
  'payment_days': 30.0,
  'billing_date': '2025-03-16'},
 {'bill_id': 111,
  'visit_id': 111,
  'billed_amount': 26557.88,
  'approved_amount': 0.0,
  'claim_status': 'Rejected',
  'payment_days': 16.0,
  'billing_date': '2025-02-21'},
 {'bill_id': 112,
  'visit_id': 112,
  'billed_amount': 9248.4,
  'approved_amount': 9248.4,
  'claim_status': 'Paid',
  'payment_days': 18.0,
  'billing_date': '2025-11-23'},
 {'bill_id': 113,
  'visit_id': 113,
  'billed_amount': 12095.72,
  'approved_amount': 8952.02,
  'claim_status': 'Pending',

In [55]:
len(billing_data)

25000

In [56]:
visits_data= visits.to_dict(orient="records")
visits_data

[{'visit_id': 1,
  'patient_id': 756,
  'visit_date': '2025-10-18',
  'department': 'Cardiology',
  'visit_type': 'ER',
  'length_of_stay_hours': 3.48,
  'risk_score': 'Low',
  'doctor_id': 169},
 {'visit_id': 2,
  'patient_id': 4102,
  'visit_date': '2025-04-06',
  'department': 'Orthopedics',
  'visit_type': 'OPD',
  'length_of_stay_hours': 15.31,
  'risk_score': 'High',
  'doctor_id': 148},
 {'visit_id': 3,
  'patient_id': 2964,
  'visit_date': '2025-07-13',
  'department': 'ICU',
  'visit_type': 'ER',
  'length_of_stay_hours': 34.36,
  'risk_score': 'Low',
  'doctor_id': 153},
 {'visit_id': 4,
  'patient_id': 4496,
  'visit_date': '2025-11-19',
  'department': 'Cardiology',
  'visit_type': 'ER',
  'length_of_stay_hours': 37.89,
  'risk_score': 'High',
  'doctor_id': 119},
 {'visit_id': 5,
  'patient_id': 1930,
  'visit_date': '2025-03-29',
  'department': 'General',
  'visit_type': 'ICU',
  'length_of_stay_hours': 16.78,
  'risk_score': 'Medium',
  'doctor_id': 118},
 {'visit_id': 6,
  'patient_id': 1803,
  'visit_date': '2025-12-20',
  'department': 'General',
  'visit_type': 'OPD',
  'length_of_stay_hours': 0.7,
  'risk_score': 'High',
  'doctor_id': 157},
 {'visit_id': 7,
  'patient_id': 4118,
  'visit_date': '2025-11-12',
  'department': 'Cardiology',
  'visit_type': 'OPD',
  'length_of_stay_hours': 6.4,
  'risk_score': 'Low',
  'doctor_id': 121},
 {'visit_id': 8,
  'patient_id': 1868,
  'visit_date': '2025-09-18',
  'department': 'ER',
  'visit_type': 'ICU',
  'length_of_stay_hours': 26.86,
  'risk_score': 'High',
  'doctor_id': 107},
 {'visit_id': 9,
  'patient_id': 295,
  'visit_date': '2026-01-17',
  'department': 'General',
  'visit_type': 'ER',
  'length_of_stay_hours': 8.31,
  'risk_score': 'Medium',
  'doctor_id': 134},
 {'visit_id': 10,
  'patient_id': 4442,
  'visit_date': '2025-12-07',
  'department': 'ER',
  'visit_type': 'ER',
  'length_of_stay_hours': 23.22,
  'risk_score': 'Low',
  'doctor_id': 107},
 {'visit_id': 11,
  'patient_id': 4524,
  'visit_date': '2025-06-12',
  'department': 'General',
  'visit_type': 'ER',
  'length_of_stay_hours': 18.21,
  'risk_score': 'Medium',
  'doctor_id': 174},
 {'visit_id': 12,
  'patient_id': 2646,
  'visit_date': '2026-01-15',
  'department': 'Orthopedics',
  'visit_type': 'OPD',
  'length_of_stay_hours': 20.65,
  'risk_score': 'Low',
  'doctor_id': 180},
 {'visit_id': 13,
  'patient_id': 3647,
  'visit_date': '2025-08-23',
  'department': 'General',
  'visit_type': 'ER',
  'length_of_stay_hours': 37.74,
  'risk_score': 'Medium',
  'doctor_id': 140},
 {'visit_id': 14,
  'patient_id': 1660,
  'visit_date': '2025-11-19',
  'department': 'ICU',
  'visit_type': 'OPD',
  'length_of_stay_hours': 25.13,
  'risk_score': 'Low',
  'doctor_id': 169},
 {'visit_id': 15,
  'patient_id': 4431,
  'visit_date': '2025-12-05',
  'department': 'ER',
  'visit_type': 'OPD',
  'length_of_stay_hours': 3.39,
  'risk_score': 'Low',
  'doctor_id': 157},
 {'visit_id': 16,
  'patient_id': 1722,
  'visit_date': '2025-09-13',
  'department': 'ICU',
  'visit_type': 'OPD',
  'length_of_stay_hours': 6.92,
  'risk_score': 'Medium',
  'doctor_id': 145},
 {'visit_id': 17,
  'patient_id': 4778,
  'visit_date': '2025-02-22',
  'department': 'Orthopedics',
  'visit_type': 'ER',
  'length_of_stay_hours': 15.2,
  'risk_score': 'Low',
  'doctor_id': 177},
 {'visit_id': 18,
  'patient_id': 476,
  'visit_date': '2025-11-01',
  'department': 'ICU',
  'visit_type': 'ER',
  'length_of_stay_hours': 26.8,
  'risk_score': 'Low',
  'doctor_id': 147},
 {'visit_id': 19,
  'patient_id': 4178,
  'visit_date': '2025-11-27',
  'department': 'ER',
  'visit_type': 'ICU',
  'length_of_stay_hours': 29.28,
  'risk_score': 'Medium',
  'doctor_id': 149},
 {'visit_id': 20,
  'patient_id': 1374,
  'visit_date': '2025-08-15',
  'department': 'ICU',
  'visit_type': 'OPD',
  'length_of_stay_hours': 27.38,
  'risk_score': 'Low',
  'doctor_id': 164},
 {'visit_id': 21,
  'patient_id': 2160,
  'visit_date': '2025-10-28',
  'department': 'ICU',
  'visit_type': 'ER',
  'length_of_stay_hours': 1.34,
  'risk_score': 'High',
  'doctor_id': 152},
 {'visit_id': 22,
  'patient_id': 1683,
  'visit_date': '2025-10-15',
  'department': 'Cardiology',
  'visit_type': 'OPD',
  'length_of_stay_hours': 15.27,
  'risk_score': 'Low',
  'doctor_id': 102},
 {'visit_id': 23,
  'patient_id': 3924,
  'visit_date': '2025-08-12',
  'department': 'Cardiology',
  'visit_type': 'OPD',
  'length_of_stay_hours': 4.94,
  'risk_score': 'Low',
  'doctor_id': 130},
 {'visit_id': 24,
  'patient_id': 4864,
  'visit_date': '2025-08-12',
  'department': 'ER',
  'visit_type': 'OPD',
  'length_of_stay_hours': 15.15,
  'risk_score': 'Low',
  'doctor_id': 123},
 {'visit_id': 25,
  'patient_id': 939,
  'visit_date': '2025-12-09',
  'department': 'ER',
  'visit_type': 'ICU',
  'length_of_stay_hours': 33.74,
  'risk_score': 'Medium',
  'doctor_id': 103},
 {'visit_id': 26,
  'patient_id': 2734,
  'visit_date': '2025-03-06',
  'department': 'ICU',
  'visit_type': 'ICU',
  'length_of_stay_hours': 30.39,
  'risk_score': 'Medium',
  'doctor_id': 112},
 {'visit_id': 27,
  'patient_id': 1268,
  'visit_date': '2025-11-06',
  'department': 'ER',
  'visit_type': 'ICU',
  'length_of_stay_hours': 20.45,
  'risk_score': 'Low',
  'doctor_id': 166},
 {'visit_id': 28,
  'patient_id': 3171,
  'visit_date': '2025-12-21',
  'department': 'Cardiology',
  'visit_type': 'ICU',
  'length_of_stay_hours': 14.13,
  'risk_score': 'Low',
  'doctor_id': 198},
 {'visit_id': 29,
  'patient_id': 1097,
  'visit_date': '2025-02-02',
  'department': 'ER',
  'visit_type': 'ER',
  'length_of_stay_hours': 10.53,
  'risk_score': 'Medium',
  'doctor_id': 100},
 {'visit_id': 30,
  'patient_id': 3292,
  'visit_date': '2025-08-06',
  'department': 'ER',
  'visit_type': 'ICU',
  'length_of_stay_hours': 6.6,
  'risk_score': 'Low',
  'doctor_id': 104},
 {'visit_id': 31,
  'patient_id': 971,
  'visit_date': '2025-02-13',
  'department': 'General',
  'visit_type': 'ICU',
  'length_of_stay_hours': 7.89,
  'risk_score': 'Low',
  'doctor_id': 116},
 {'visit_id': 32,
  'patient_id': 1798,
  'visit_date': '2025-09-23',
  'department': 'Neurology',
  'visit_type': 'ICU',
  'length_of_stay_hours': 25.62,
  'risk_score': 'Medium',
  'doctor_id': 171},
 {'visit_id': 33,
  'patient_id': 1180,
  'visit_date': '2025-08-06',
  'department': 'ICU',
  'visit_type': 'ICU',
  'length_of_stay_hours': 10.16,
  'risk_score': 'Low',
  'doctor_id': 129},
 {'visit_id': 34,
  'patient_id': 1835,
  'visit_date': '2025-06-09',
  'department': 'ER',
  'visit_type': 'ICU',
  'length_of_stay_hours': 14.34,
  'risk_score': 'Medium',
  'doctor_id': 184},
 {'visit_id': 35,
  'patient_id': 3578,
  'visit_date': '2025-12-24',
  'department': 'Orthopedics',
  'visit_type': 'ICU',
  'length_of_stay_hours': 15.61,
  'risk_score': 'Low',
  'doctor_id': 158},
 {'visit_id': 36,
  'patient_id': 379,
  'visit_date': '2025-05-24',
  'department': 'ER',
  'visit_type': 'ER',
  'length_of_stay_hours': 31.1,
  'risk_score': 'Low',
  'doctor_id': 105},
 {'visit_id': 37,
  'patient_id': 3447,
  'visit_date': '2025-09-28',
  'department': 'Orthopedics',
  'visit_type': 'ER',
  'length_of_stay_hours': 14.31,
  'risk_score': 'Low',
  'doctor_id': 165},
 {'visit_id': 38,
  'patient_id': 3390,
  'visit_date': '2025-10-12',
  'department': 'ER',
  'visit_type': 'OPD',
  'length_of_stay_hours': 24.92,
  'risk_score': 'Low',
  'doctor_id': 124},
 {'visit_id': 39,
  'patient_id': 2772,
  'visit_date': '2025-07-20',
  'department': 'ER',
  'visit_type': 'ER',
  'length_of_stay_hours': 26.82,
  'risk_score': 'Low',
  'doctor_id': 101},
 {'visit_id': 40,
  'patient_id': 3989,
  'visit_date': '2025-09-03',
  'department': 'Neurology',
  'visit_type': 'ICU',
  'length_of_stay_hours': 0.92,
  'risk_score': 'Low',
  'doctor_id': 112},
 {'visit_id': 41,
  'patient_id': 1400,
  'visit_date': '2025-12-22',
  'department': 'Neurology',
  'visit_type': 'OPD',
  'length_of_stay_hours': 18.26,
  'risk_score': 'Low',
  'doctor_id': 141},
 {'visit_id': 42,
  'patient_id': 2698,
  'visit_date': '2025-07-13',
  'department': 'ER',
  'visit_type': 'OPD',
  'length_of_stay_hours': 6.23,
  'risk_score': 'Medium',
  'doctor_id': 187},
 {'visit_id': 43,
  'patient_id': 2608,
  'visit_date': '2025-09-02',
  'department': 'ER',
  'visit_type': 'OPD',
  'length_of_stay_hours': 31.29,
  'risk_score': 'Low',
  'doctor_id': 145},
 {'visit_id': 44,
  'patient_id': 1041,
  'visit_date': '2025-12-15',
  'department': 'Cardiology',
  'visit_type': 'ICU',
  'length_of_stay_hours': 18.97,
  'risk_score': 'Low',
  'doctor_id': 161},
 {'visit_id': 45,
  'patient_id': 4944,
  'visit_date': '2025-12-31',
  'department': 'ER',
  'visit_type': 'OPD',
  'length_of_stay_hours': 9.69,
  'risk_score': 'Medium',
  'doctor_id': 166},
 {'visit_id': 46,
  'patient_id': 2244,
  'visit_date': '2026-01-18',
  'department': 'Orthopedics',
  'visit_type': 'ER',
  'length_of_stay_hours': 14.06,
  'risk_score': 'Low',
  'doctor_id': 105},
 {'visit_id': 47,
  'patient_id': 2550,
  'visit_date': '2025-07-27',
  'department': 'ICU',
  'visit_type': 'ICU',
  'length_of_stay_hours': 13.65,
  'risk_score': 'Low',
  'doctor_id': 126},
 {'visit_id': 48,
  'patient_id': 858,
  'visit_date': '2025-02-28',
  'department': 'Orthopedics',
  'visit_type': 'OPD',
  'length_of_stay_hours': 11.46,
  'risk_score': 'Low',
  'doctor_id': 139},
 {'visit_id': 49,
  'patient_id': 3960,
  'visit_date': '2025-02-15',
  'department': 'ER',
  'visit_type': 'ICU',
  'length_of_stay_hours': 34.51,
  'risk_score': 'High',
  'doctor_id': 113},
 {'visit_id': 50,
  'patient_id': 1249,
  'visit_date': '2025-05-16',
  'department': 'ER',
  'visit_type': 'ER',
  'length_of_stay_hours': 4.98,
  'risk_score': 'Medium',
  'doctor_id': 106},
 {'visit_id': 51,
  'patient_id': 1626,
  'visit_date': '2025-08-13',
  'department': 'ICU',
  'visit_type': 'ER',
  'length_of_stay_hours': 23.25,
  'risk_score': 'Low',
  'doctor_id': 114},
 {'visit_id': 52,
  'patient_id': 2657,
  'visit_date': '2025-12-07',
  'department': 'General',
  'visit_type': 'ICU',
  'length_of_stay_hours': 2.68,
  'risk_score': 'Low',
  'doctor_id': 177},
 {'visit_id': 53,
  'patient_id': 612,
  'visit_date': '2025-02-08',
  'department': 'ICU',
  'visit_type': 'ICU',
  'length_of_stay_hours': 21.48,
  'risk_score': 'High',
  'doctor_id': 156},
 {'visit_id': 54,
  'patient_id': 3690,
  'visit_date': '2025-12-02',
  'department': 'General',
  'visit_type': 'ICU',
  'length_of_stay_hours': 20.89,
  'risk_score': 'Low',
  'doctor_id': 106},
 {'visit_id': 55,
  'patient_id': 1165,
  'visit_date': '2025-05-18',
  'department': 'ER',
  'visit_type': 'ER',
  'length_of_stay_hours': 1.84,
  'risk_score': 'Low',
  'doctor_id': 199},
 {'visit_id': 56,
  'patient_id': 2188,
  'visit_date': '2025-07-21',
  'department': 'General',
  'visit_type': 'ICU',
  'length_of_stay_hours': 29.9,
  'risk_score': 'High',
  'doctor_id': 137},
 {'visit_id': 57,
  'patient_id': 2158,
  'visit_date': '2025-08-18',
  'department': 'General',
  'visit_type': 'ICU',
  'length_of_stay_hours': 31.1,
  'risk_score': 'Low',
  'doctor_id': 137},
 {'visit_id': 58,
  'patient_id': 203,
  'visit_date': '2025-05-18',
  'department': 'General',
  'visit_type': 'ICU',
  'length_of_stay_hours': 10.62,
  'risk_score': 'High',
  'doctor_id': 154},
 {'visit_id': 59,
  'patient_id': 2443,
  'visit_date': '2025-01-31',
  'department': 'Cardiology',
  'visit_type': 'ER',
  'length_of_stay_hours': 3.05,
  'risk_score': 'High',
  'doctor_id': 127},
 {'visit_id': 60,
  'patient_id': 1104,
  'visit_date': '2025-11-29',
  'department': 'Orthopedics',
  'visit_type': 'ER',
  'length_of_stay_hours': 26.86,
  'risk_score': 'Low',
  'doctor_id': 127},
 {'visit_id': 61,
  'patient_id': 4085,
  'visit_date': '2025-10-06',
  'department': 'ER',
  'visit_type': 'OPD',
  'length_of_stay_hours': 32.99,
  'risk_score': 'Low',
  'doctor_id': 115},
 {'visit_id': 62,
  'patient_id': 2909,
  'visit_date': '2025-11-14',
  'department': 'General',
  'visit_type': 'ER',
  'length_of_stay_hours': 26.63,
  'risk_score': 'Medium',
  'doctor_id': 157},
 {'visit_id': 63,
  'patient_id': 1313,
  'visit_date': '2025-11-23',
  'department': 'ER',
  'visit_type': 'ICU',
  'length_of_stay_hours': 59.25,
  'risk_score': 'High',
  'doctor_id': 118},
 {'visit_id': 64,
  'patient_id': 3598,
  'visit_date': '2025-05-19',
  'department': 'Cardiology',
  'visit_type': 'ICU',
  'length_of_stay_hours': 24.35,
  'risk_score': 'High',
  'doctor_id': 150},
 {'visit_id': 65,
  'patient_id': 4584,
  'visit_date': '2025-05-06',
  'department': 'ER',
  'visit_type': 'OPD',
  'length_of_stay_hours': 20.63,
  'risk_score': 'Medium',
  'doctor_id': 117},
 {'visit_id': 66,
  'patient_id': 4628,
  'visit_date': '2025-03-06',
  'department': 'Orthopedics',
  'visit_type': 'ICU',
  'length_of_stay_hours': 9.59,
  'risk_score': 'High',
  'doctor_id': 147},
 {'visit_id': 67,
  'patient_id': 2493,
  'visit_date': '2025-12-14',
  'department': 'Neurology',
  'visit_type': 'OPD',
  'length_of_stay_hours': 5.36,
  'risk_score': 'Medium',
  'doctor_id': 129},
 {'visit_id': 68,
  'patient_id': 1435,
  'visit_date': '2025-06-22',
  'department': 'Cardiology',
  'visit_type': 'ER',
  'length_of_stay_hours': 19.32,
  'risk_score': 'Low',
  'doctor_id': 194},
 {'visit_id': 69,
  'patient_id': 3055,
  'visit_date': '2025-02-24',
  'department': 'ICU',
  'visit_type': 'ER',
  'length_of_stay_hours': 33.76,
  'risk_score': 'Low',
  'doctor_id': 180},
 {'visit_id': 70,
  'patient_id': 2084,
  'visit_date': '2025-10-22',
  'department': 'Neurology',
  'visit_type': 'ICU',
  'length_of_stay_hours': 17.33,
  'risk_score': 'Low',
  'doctor_id': 155},
 {'visit_id': 71,
  'patient_id': 3188,
  'visit_date': '2025-02-01',
  'department': 'General',
  'visit_type': 'OPD',
  'length_of_stay_hours': 28.69,
  'risk_score': 'Medium',
  'doctor_id': 138},
 {'visit_id': 72,
  'patient_id': 2390,
  'visit_date': '2025-08-04',
  'department': 'General',
  'visit_type': 'ICU',
  'length_of_stay_hours': 23.09,
  'risk_score': 'Medium',
  'doctor_id': 132},
 {'visit_id': 73,
  'patient_id': 3185,
  'visit_date': '2025-04-20',
  'department': 'ER',
  'visit_type': 'OPD',
  'length_of_stay_hours': 32.42,
  'risk_score': 'High',
  'doctor_id': 144},
 {'visit_id': 74,
  'patient_id': 4689,
  'visit_date': '2025-07-21',
  'department': 'ICU',
  'visit_type': 'ER',
  'length_of_stay_hours': 37.13,
  'risk_score': 'High',
  'doctor_id': 183},
 {'visit_id': 75,
  'patient_id': 675,
  'visit_date': '2025-12-07',
  'department': 'General',
  'visit_type': 'ER',
  'length_of_stay_hours': 16.32,
  'risk_score': 'Low',
  'doctor_id': 194},
 {'visit_id': 76,
  'patient_id': 4996,
  'visit_date': '2025-03-19',
  'department': 'General',
  'visit_type': 'OPD',
  'length_of_stay_hours': 35.6,
  'risk_score': 'Medium',
  'doctor_id': 156},
 {'visit_id': 77,
  'patient_id': 25,
  'visit_date': '2025-07-11',
  'department': 'Cardiology',
  'visit_type': 'OPD',
  'length_of_stay_hours': 22.9,
  'risk_score': 'Low',
  'doctor_id': 121},
 {'visit_id': 78,
  'patient_id': 631,
  'visit_date': '2025-10-09',
  'department': 'ER',
  'visit_type': 'OPD',
  'length_of_stay_hours': 2.5,
  'risk_score': 'High',
  'doctor_id': 151},
 {'visit_id': 79,
  'patient_id': 4625,
  'visit_date': '2025-10-29',
  'department': 'Cardiology',
  'visit_type': 'ICU',
  'length_of_stay_hours': 65.76,
  'risk_score': 'Medium',
  'doctor_id': 136},
 {'visit_id': 80,
  'patient_id': 811,
  'visit_date': '2025-05-16',
  'department': 'Orthopedics',
  'visit_type': 'ER',
  'length_of_stay_hours': 11.67,
  'risk_score': 'High',
  'doctor_id': 185},
 {'visit_id': 81,
  'patient_id': 3929,
  'visit_date': '2025-08-05',
  'department': 'ER',
  'visit_type': 'OPD',
  'length_of_stay_hours': 3.62,
  'risk_score': 'Low',
  'doctor_id': 190},
 {'visit_id': 82,
  'patient_id': 4840,
  'visit_date': '2025-05-30',
  'department': 'ICU',
  'visit_type': 'OPD',
  'length_of_stay_hours': 5.81,
  'risk_score': 'Low',
  'doctor_id': 188},
 {'visit_id': 83,
  'patient_id': 3989,
  'visit_date': '2025-09-07',
  'department': 'Orthopedics',
  'visit_type': 'OPD',
  'length_of_stay_hours': 6.1,
  'risk_score': 'Medium',
  'doctor_id': 194},
 {'visit_id': 84,
  'patient_id': 1053,
  'visit_date': '2025-11-18',
  'department': 'ER',
  'visit_type': 'OPD',
  'length_of_stay_hours': 19.68,
  'risk_score': 'Medium',
  'doctor_id': 168},
 {'visit_id': 85,
  'patient_id': 3319,
  'visit_date': '2025-06-16',
  'department': 'ER',
  'visit_type': 'ICU',
  'length_of_stay_hours': 10.09,
  'risk_score': 'Medium',
  'doctor_id': 130},
 {'visit_id': 86,
  'patient_id': 1649,
  'visit_date': '2025-02-03',
  'department': 'Neurology',
  'visit_type': 'ER',
  'length_of_stay_hours': 18.17,
  'risk_score': 'Low',
  'doctor_id': 181},
 {'visit_id': 87,
  'patient_id': 2850,
  'visit_date': '2025-02-04',
  'department': 'ICU',
  'visit_type': 'ICU',
  'length_of_stay_hours': 14.01,
  'risk_score': 'Low',
  'doctor_id': 182},
 {'visit_id': 88,
  'patient_id': 4794,
  'visit_date': '2025-08-04',
  'department': 'ER',
  'visit_type': 'OPD',
  'length_of_stay_hours': 27.17,
  'risk_score': 'Low',
  'doctor_id': 114},
 {'visit_id': 89,
  'patient_id': 4570,
  'visit_date': '2025-04-26',
  'department': 'General',
  'visit_type': 'ER',
  'length_of_stay_hours': 6.86,
  'risk_score': 'Low',
  'doctor_id': 157},
 {'visit_id': 90,
  'patient_id': 3766,
  'visit_date': '2025-03-24',
  'department': 'ICU',
  'visit_type': 'ICU',
  'length_of_stay_hours': 15.58,
  'risk_score': 'High',
  'doctor_id': 148},
 {'visit_id': 91,
  'patient_id': 3404,
  'visit_date': '2025-08-19',
  'department': 'General',
  'visit_type': 'OPD',
  'length_of_stay_hours': 34.87,
  'risk_score': 'Medium',
  'doctor_id': 100},
 {'visit_id': 92,
  'patient_id': 1144,
  'visit_date': '2025-06-29',
  'department': 'ER',
  'visit_type': 'ER',
  'length_of_stay_hours': 13.53,
  'risk_score': 'Medium',
  'doctor_id': 130},
 {'visit_id': 93,
  'patient_id': 2277,
  'visit_date': '2025-04-19',
  'department': 'Cardiology',
  'visit_type': 'OPD',
  'length_of_stay_hours': 11.81,
  'risk_score': 'High',
  'doctor_id': 116},
 {'visit_id': 94,
  'patient_id': 1095,
  'visit_date': '2026-01-03',
  'department': 'ER',
  'visit_type': 'OPD',
  'length_of_stay_hours': 11.6,
  'risk_score': 'Low',
  'doctor_id': 134},
 {'visit_id': 95,
  'patient_id': 4821,
  'visit_date': '2025-10-25',
  'department': 'Cardiology',
  'visit_type': 'OPD',
  'length_of_stay_hours': 21.08,
  'risk_score': 'High',
  'doctor_id': 126},
 {'visit_id': 96,
  'patient_id': 3586,
  'visit_date': '2025-08-24',
  'department': 'ICU',
  'visit_type': 'OPD',
  'length_of_stay_hours': 16.94,
  'risk_score': 'Medium',
  'doctor_id': 153},
 {'visit_id': 97,
  'patient_id': 4000,
  'visit_date': '2025-07-22',
  'department': 'ICU',
  'visit_type': 'ICU',
  'length_of_stay_hours': 11.91,
  'risk_score': 'Medium',
  'doctor_id': 102},
 {'visit_id': 98,
  'patient_id': 769,
  'visit_date': '2025-09-19',
  'department': 'General',
  'visit_type': 'ICU',
  'length_of_stay_hours': 13.75,
  'risk_score': 'Medium',
  'doctor_id': 109},
 {'visit_id': 99,
  'patient_id': 2683,
  'visit_date': '2025-04-06',
  'department': 'ER',
  'visit_type': 'ER',
  'length_of_stay_hours': 39.81,
  'risk_score': 'Low',
  'doctor_id': 135},
 {'visit_id': 100,
  'patient_id': 3307,
  'visit_date': '2025-03-22',
  'department': 'Orthopedics',
  'visit_type': 'ER',
  'length_of_stay_hours': 51.54,
  'risk_score': 'Low',
  'doctor_id': 103},
 {'visit_id': 101,
  'patient_id': 1346,
  'visit_date': '2025-05-08',
  'department': 'Neurology',
  'visit_type': 'ER',
  'length_of_stay_hours': 17.73,
  'risk_score': 'Medium',
  'doctor_id': 108},
 {'visit_id': 102,
  'patient_id': 3752,
  'visit_date': '2025-06-24',
  'department': 'General',
  'visit_type': 'ER',
  'length_of_stay_hours': 11.61,
  'risk_score': 'Medium',
  'doctor_id': 155},

In [57]:
len(visits_data)

25000

In [58]:

patient_data= patient.to_dict(orient="records")
patient_data

[{'patient_id': 1,
  'age': 53,
  'gender': 'M',
  'city': 'Hyderabad',
  'insurance_provider': 'SecureLife',
  'chronic_flag': 0,
  'registration_date': '2025-05-14'},
 {'patient_id': 2,
  'age': 42,
  'gender': 'M',
  'city': 'Pune',
  'insurance_provider': 'HealthPlus',
  'chronic_flag': 0,
  'registration_date': '2025-11-18'},
 {'patient_id': 3,
  'age': 56,
  'gender': 'F',
  'city': 'Hyderabad',
  'insurance_provider': 'HealthPlus',
  'chronic_flag': 0,
  'registration_date': '2025-05-11'},
 {'patient_id': 4,
  'age': 72,
  'gender': 'M',
  'city': 'Chennai',
  'insurance_provider': 'HealthPlus',
  'chronic_flag': 0,
  'registration_date': '2025-12-18'},
 {'patient_id': 5,
  'age': 40,
  'gender': 'F',
  'city': 'Bangalore',
  'insurance_provider': 'CareOne',
  'chronic_flag': 1,
  'registration_date': '2025-01-23'},
 {'patient_id': 6,
  'age': 40,
  'gender': 'M',
  'city': 'Pune',
  'insurance_provider': 'CareOne',
  'chronic_flag': 1,
  'registration_date': '2025-06-11'},
 {'patient_id': 7,
  'age': 73,
  'gender': 'M',
  'city': 'Bangalore',
  'insurance_provider': 'SecureLife',
  'chronic_flag': 0,
  'registration_date': '2025-03-08'},
 {'patient_id': 8,
  'age': 58,
  'gender': 'F',
  'city': 'Hyderabad',
  'insurance_provider': 'SecureLife',
  'chronic_flag': 1,
  'registration_date': '2025-11-25'},
 {'patient_id': 9,
  'age': 36,
  'gender': 'F',
  'city': 'Hyderabad',
  'insurance_provider': 'CareOne',
  'chronic_flag': 0,
  'registration_date': '2025-08-01'},
 {'patient_id': 10,
  'age': 54,
  'gender': 'M',
  'city': 'Chennai',
  'insurance_provider': 'SecureLife',
  'chronic_flag': 1,
  'registration_date': '2025-11-11'},
 {'patient_id': 11,
  'age': 36,
  'gender': 'M',
  'city': 'Pune',
  'insurance_provider': 'HealthPlus',
  'chronic_flag': 0,
  'registration_date': '2025-12-24'},
 {'patient_id': 12,
  'age': 36,
  'gender': 'M',
  'city': 'Mumbai',
  'insurance_provider': 'HealthPlus',
  'chronic_flag': 0,
  'registration_date': '2025-03-12'},
 {'patient_id': 13,
  'age': 49,
  'gender': 'F',
  'city': 'Mumbai',
  'insurance_provider': 'CareOne',
  'chronic_flag': 1,
  'registration_date': '2025-04-13'},
 {'patient_id': 14,
  'age': 10,
  'gender': 'F',
  'city': 'Mumbai',
  'insurance_provider': 'MediCareX',
  'chronic_flag': 1,
  'registration_date': '2026-01-14'},
 {'patient_id': 15,
  'age': 13,
  'gender': 'M',
  'city': 'Chennai',
  'insurance_provider': 'MediCareX',
  'chronic_flag': 0,
  'registration_date': '2025-04-13'},
 {'patient_id': 16,
  'age': 34,
  'gender': 'F',
  'city': 'Delhi',
  'insurance_provider': 'SecureLife',
  'chronic_flag': 0,
  'registration_date': '2026-01-05'},
 {'patient_id': 17,
  'age': 26,
  'gender': 'F',
  'city': 'Hyderabad',
  'insurance_provider': 'MediCareX',
  'chronic_flag': 0,
  'registration_date': '2025-06-30'},
 {'patient_id': 18,
  'age': 50,
  'gender': 'F',
  'city': 'Mumbai',
  'insurance_provider': 'HealthPlus',
  'chronic_flag': 0,
  'registration_date': '2025-11-06'},
 {'patient_id': 19,
  'age': 28,
  'gender': 'F',
  'city': 'Bangalore',
  'insurance_provider': 'CareOne',
  'chronic_flag': 1,
  'registration_date': '2025-12-15'},
 {'patient_id': 20,
  'age': 19,
  'gender': 'F',
  'city': 'Bangalore',
  'insurance_provider': 'SecureLife',
  'chronic_flag': 0,
  'registration_date': '2025-05-26'},
 {'patient_id': 21,
  'age': 71,
  'gender': 'F',
  'city': 'Pune',
  'insurance_provider': 'CareOne',
  'chronic_flag': 1,
  'registration_date': '2025-07-24'},
 {'patient_id': 22,
  'age': 40,
  'gender': 'M',
  'city': 'Bangalore',
  'insurance_provider': 'CareOne',
  'chronic_flag': 0,
  'registration_date': '2025-02-13'},
 {'patient_id': 23,
  'age': 46,
  'gender': 'M',
  'city': 'Bangalore',
  'insurance_provider': 'MediCareX',
  'chronic_flag': 1,
  'registration_date': '2025-11-21'},
 {'patient_id': 24,
  'age': 19,
  'gender': 'M',
  'city': 'Delhi',
  'insurance_provider': 'CareOne',
  'chronic_flag': 1,
  'registration_date': '2025-10-17'},
 {'patient_id': 25,
  'age': 35,
  'gender': 'F',
  'city': 'Chennai',
  'insurance_provider': 'HealthPlus',
  'chronic_flag': 0,
  'registration_date': '2026-01-04'},
 {'patient_id': 26,
  'age': 46,
  'gender': 'F',
  'city': 'Pune',
  'insurance_provider': 'SecureLife',
  'chronic_flag': 0,
  'registration_date': '2025-06-19'},
 {'patient_id': 27,
  'age': 24,
  'gender': 'F',
  'city': 'Bangalore',
  'insurance_provider': 'CareOne',
  'chronic_flag': 0,
  'registration_date': '2025-06-03'},
 {'patient_id': 28,
  'age': 51,
  'gender': 'M',
  'city': 'Chennai',
  'insurance_provider': 'HealthPlus',
  'chronic_flag': 1,
  'registration_date': '2025-12-13'},
 {'patient_id': 29,
  'age': 34,
  'gender': 'M',
  'city': 'Bangalore',
  'insurance_provider': 'SecureLife',
  'chronic_flag': 0,
  'registration_date': '2025-10-23'},
 {'patient_id': 30,
  'age': 39,
  'gender': 'M',
  'city': 'Chennai',
  'insurance_provider': 'SecureLife',
  'chronic_flag': 1,
  'registration_date': '2025-01-29'},
 {'patient_id': 31,
  'age': 34,
  'gender': 'M',
  'city': 'Mumbai',
  'insurance_provider': 'SecureLife',
  'chronic_flag': 0,
  'registration_date': '2025-02-18'},
 {'patient_id': 32,
  'age': 78,
  'gender': 'M',
  'city': 'Chennai',
  'insurance_provider': 'HealthPlus',
  'chronic_flag': 0,
  'registration_date': '2025-09-25'},
 {'patient_id': 33,
  'age': 44,
  'gender': 'M',
  'city': 'Chennai',
  'insurance_provider': 'MediCareX',
  'chronic_flag': 0,
  'registration_date': '2025-12-23'},
 {'patient_id': 34,
  'age': 25,
  'gender': 'F',
  'city': 'Chennai',
  'insurance_provider': 'MediCareX',
  'chronic_flag': 1,
  'registration_date': '2025-10-17'},
 {'patient_id': 35,
  'age': 59,
  'gender': 'F',
  'city': 'Bangalore',
  'insurance_provider': 'MediCareX',
  'chronic_flag': 1,
  'registration_date': '2025-08-12'},
 {'patient_id': 36,
  'age': 23,
  'gender': 'F',
  'city': 'Delhi',
  'insurance_provider': 'CareOne',
  'chronic_flag': 0,
  'registration_date': '2025-05-26'},
 {'patient_id': 37,
  'age': 48,
  'gender': 'M',
  'city': 'Hyderabad',
  'insurance_provider': 'SecureLife',
  'chronic_flag': 0,
  'registration_date': '2025-11-17'},
 {'patient_id': 38,
  'age': 9,
  'gender': 'M',
  'city': 'Chennai',
  'insurance_provider': 'MediCareX',
  'chronic_flag': 0,
  'registration_date': '2025-02-25'},
 {'patient_id': 39,
  'age': 21,
  'gender': 'M',
  'city': 'Bangalore',
  'insurance_provider': 'HealthPlus',
  'chronic_flag': 0,
  'registration_date': '2025-07-08'},
 {'patient_id': 40,
  'age': 48,
  'gender': 'M',
  'city': 'Chennai',
  'insurance_provider': 'MediCareX',
  'chronic_flag': 1,
  'registration_date': '2025-12-28'},
 {'patient_id': 41,
  'age': 58,
  'gender': 'F',
  'city': 'Bangalore',
  'insurance_provider': 'MediCareX',
  'chronic_flag': 1,
  'registration_date': '2025-05-24'},
 {'patient_id': 42,
  'age': 48,
  'gender': 'F',
  'city': 'Delhi',
  'insurance_provider': 'MediCareX',
  'chronic_flag': 0,
  'registration_date': '2025-03-10'},
 {'patient_id': 43,
  'age': 42,
  'gender': 'F',
  'city': 'Mumbai',
  'insurance_provider': 'CareOne',
  'chronic_flag': 1,
  'registration_date': '2025-09-16'},
 {'patient_id': 44,
  'age': 39,
  'gender': 'M',
  'city': 'Pune',
  'insurance_provider': 'HealthPlus',
  'chronic_flag': 0,
  'registration_date': '2025-08-14'},
 {'patient_id': 45,
  'age': 18,
  'gender': 'F',
  'city': 'Hyderabad',
  'insurance_provider': 'MediCareX',
  'chronic_flag': 0,
  'registration_date': '2025-04-27'},
 {'patient_id': 46,
  'age': 32,
  'gender': 'F',
  'city': 'Bangalore',
  'insurance_provider': 'CareOne',
  'chronic_flag': 0,
  'registration_date': '2025-06-11'},
 {'patient_id': 47,
  'age': 36,
  'gender': 'F',
  'city': 'Bangalore',
  'insurance_provider': 'HealthPlus',
  'chronic_flag': 1,
  'registration_date': '2025-10-28'},
 {'patient_id': 48,
  'age': 64,
  'gender': 'M',
  'city': 'Hyderabad',
  'insurance_provider': 'HealthPlus',
  'chronic_flag': 0,
  'registration_date': '2025-05-21'},
 {'patient_id': 49,
  'age': 51,
  'gender': 'M',
  'city': 'Delhi',
  'insurance_provider': 'CareOne',
  'chronic_flag': 1,
  'registration_date': '2025-05-09'},
 {'patient_id': 50,
  'age': 13,
  'gender': 'F',
  'city': 'Hyderabad',
  'insurance_provider': 'MediCareX',
  'chronic_flag': 1,
  'registration_date': '2025-01-21'},
 {'patient_id': 51,
  'age': 50,
  'gender': 'F',
  'city': 'Mumbai',
  'insurance_provider': 'CareOne',
  'chronic_flag': 1,
  'registration_date': '2025-08-24'},
 {'patient_id': 52,
  'age': 38,
  'gender': 'F',
  'city': 'Bangalore',
  'insurance_provider': 'MediCareX',
  'chronic_flag': 1,
  'registration_date': '2025-05-11'},
 {'patient_id': 53,
  'age': 32,
  'gender': 'M',
  'city': 'Chennai',
  'insurance_provider': 'HealthPlus',
  'chronic_flag': 1,
  'registration_date': '2025-02-18'},
 {'patient_id': 54,
  'age': 56,
  'gender': 'M',
  'city': 'Chennai',
  'insurance_provider': 'CareOne',
  'chronic_flag': 0,
  'registration_date': '2025-02-18'},
 {'patient_id': 55,
  'age': 63,
  'gender': 'M',
  'city': 'Bangalore',
  'insurance_provider': 'HealthPlus',
  'chronic_flag': 0,
  'registration_date': '2025-12-31'},
 {'patient_id': 56,
  'age': 61,
  'gender': 'M',
  'city': 'Delhi',
  'insurance_provider': 'HealthPlus',
  'chronic_flag': 0,
  'registration_date': '2025-11-12'},
 {'patient_id': 57,
  'age': 29,
  'gender': 'M',
  'city': 'Chennai',
  'insurance_provider': 'HealthPlus',
  'chronic_flag': 1,
  'registration_date': '2025-12-22'},
 {'patient_id': 58,
  'age': 39,
  'gender': 'F',
  'city': 'Mumbai',
  'insurance_provider': 'MediCareX',
  'chronic_flag': 1,
  'registration_date': '2025-05-22'},
 {'patient_id': 59,
  'age': 50,
  'gender': 'F',
  'city': 'Delhi',
  'insurance_provider': 'MediCareX',
  'chronic_flag': 1,
  'registration_date': '2025-09-11'},
 {'patient_id': 60,
  'age': 62,
  'gender': 'F',
  'city': 'Hyderabad',
  'insurance_provider': 'HealthPlus',
  'chronic_flag': 1,
  'registration_date': '2025-12-04'},
 {'patient_id': 61,
  'age': 36,
  'gender': 'M',
  'city': 'Hyderabad',
  'insurance_provider': 'MediCareX',
  'chronic_flag': 1,
  'registration_date': '2025-03-28'},
 {'patient_id': 62,
  'age': 41,
  'gender': 'F',
  'city': 'Hyderabad',
  'insurance_provider': 'MediCareX',
  'chronic_flag': 1,
  'registration_date': '2025-06-14'},
 {'patient_id': 63,
  'age': 25,
  'gender': 'M',
  'city': 'Delhi',
  'insurance_provider': 'SecureLife',
  'chronic_flag': 0,
  'registration_date': '2025-12-27'},
 {'patient_id': 64,
  'age': 23,
  'gender': 'F',
  'city': 'Pune',
  'insurance_provider': 'HealthPlus',
  'chronic_flag': 0,
  'registration_date': '2025-06-04'},
 {'patient_id': 65,
  'age': 59,
  'gender': 'M',
  'city': 'Hyderabad',
  'insurance_provider': 'MediCareX',
  'chronic_flag': 1,
  'registration_date': '2025-06-13'},
 {'patient_id': 66,
  'age': 69,
  'gender': 'M',
  'city': 'Pune',
  'insurance_provider': 'SecureLife',
  'chronic_flag': 0,
  'registration_date': '2026-01-06'},
 {'patient_id': 67,
  'age': 43,
  'gender': 'F',
  'city': 'Chennai',
  'insurance_provider': 'CareOne',
  'chronic_flag': 1,
  'registration_date': '2025-02-15'},
 {'patient_id': 68,
  'age': 63,
  'gender': 'M',
  'city': 'Pune',
  'insurance_provider': 'CareOne',
  'chronic_flag': 1,
  'registration_date': '2025-02-11'},
 {'patient_id': 69,
  'age': 51,
  'gender': 'M',
  'city': 'Mumbai',
  'insurance_provider': 'MediCareX',
  'chronic_flag': 1,
  'registration_date': '2025-04-12'},
 {'patient_id': 70,
  'age': 33,
  'gender': 'F',
  'city': 'Chennai',
  'insurance_provider': 'CareOne',
  'chronic_flag': 0,
  'registration_date': '2025-03-18'},
 {'patient_id': 71,
  'age': 51,
  'gender': 'M',
  'city': 'Pune',
  'insurance_provider': 'MediCareX',
  'chronic_flag': 0,
  'registration_date': '2025-07-28'},
 {'patient_id': 72,
  'age': 72,
  'gender': 'M',
  'city': 'Delhi',
  'insurance_provider': 'MediCareX',
  'chronic_flag': 0,
  'registration_date': '2025-06-26'},
 {'patient_id': 73,
  'age': 44,
  'gender': 'F',
  'city': 'Hyderabad',
  'insurance_provider': 'SecureLife',
  'chronic_flag': 0,
  'registration_date': '2026-01-04'},
 {'patient_id': 74,
  'age': 73,
  'gender': 'M',
  'city': 'Pune',
  'insurance_provider': 'HealthPlus',
  'chronic_flag': 1,
  'registration_date': '2025-11-02'},
 {'patient_id': 75,
  'age': 1,
  'gender': 'F',
  'city': 'Chennai',
  'insurance_provider': 'MediCareX',
  'chronic_flag': 0,
  'registration_date': '2025-04-13'},
 {'patient_id': 76,
  'age': 59,
  'gender': 'M',
  'city': 'Delhi',
  'insurance_provider': 'HealthPlus',
  'chronic_flag': 0,
  'registration_date': '2025-07-09'},
 {'patient_id': 77,
  'age': 46,
  'gender': 'F',
  'city': 'Pune',
  'insurance_provider': 'MediCareX',
  'chronic_flag': 1,
  'registration_date': '2025-04-11'},
 {'patient_id': 78,
  'age': 39,
  'gender': 'M',
  'city': 'Delhi',
  'insurance_provider': 'HealthPlus',
  'chronic_flag': 1,
  'registration_date': '2025-05-13'},
 {'patient_id': 79,
  'age': 46,
  'gender': 'M',
  'city': 'Delhi',
  'insurance_provider': 'SecureLife',
  'chronic_flag': 1,
  'registration_date': '2025-05-16'},
 {'patient_id': 80,
  'age': 9,
  'gender': 'M',
  'city': 'Hyderabad',
  'insurance_provider': 'MediCareX',
  'chronic_flag': 1,
  'registration_date': '2025-07-07'},
 {'patient_id': 81,
  'age': 41,
  'gender': 'F',
  'city': 'Hyderabad',
  'insurance_provider': 'SecureLife',
  'chronic_flag': 1,
  'registration_date': '2025-12-14'},
 {'patient_id': 82,
  'age': 51,
  'gender': 'F',
  'city': 'Pune',
  'insurance_provider': 'SecureLife',
  'chronic_flag': 0,
  'registration_date': '2025-03-20'},
 {'patient_id': 83,
  'age': 71,
  'gender': 'F',
  'city': 'Bangalore',
  'insurance_provider': 'SecureLife',
  'chronic_flag': 0,
  'registration_date': '2025-03-16'},
 {'patient_id': 84,
  'age': 35,
  'gender': 'F',
  'city': 'Mumbai',
  'insurance_provider': 'SecureLife',
  'chronic_flag': 1,
  'registration_date': '2025-11-26'},
 {'patient_id': 85,
  'age': 30,
  'gender': 'M',
  'city': 'Delhi',
  'insurance_provider': 'MediCareX',
  'chronic_flag': 1,
  'registration_date': '2025-02-11'},
 {'patient_id': 86,
  'age': 35,
  'gender': 'F',
  'city': 'Hyderabad',
  'insurance_provider': 'MediCareX',
  'chronic_flag': 1,
  'registration_date': '2025-08-28'},
 {'patient_id': 87,
  'age': 61,
  'gender': 'M',
  'city': 'Pune',
  'insurance_provider': 'SecureLife',
  'chronic_flag': 1,
  'registration_date': '2025-12-25'},
 {'patient_id': 88,
  'age': 50,
  'gender': 'M',
  'city': 'Pune',
  'insurance_provider': 'SecureLife',
  'chronic_flag': 1,
  'registration_date': '2025-12-27'},
 {'patient_id': 89,
  'age': 35,
  'gender': 'F',
  'city': 'Mumbai',
  'insurance_provider': 'CareOne',
  'chronic_flag': 1,
  'registration_date': '2025-10-30'},
 {'patient_id': 90,
  'age': 54,
  'gender': 'M',
  'city': 'Bangalore',
  'insurance_provider': 'CareOne',
  'chronic_flag': 1,
  'registration_date': '2026-01-01'},
 {'patient_id': 91,
  'age': 46,
  'gender': 'M',
  'city': 'Chennai',
  'insurance_provider': 'SecureLife',
  'chronic_flag': 1,
  'registration_date': '2025-10-27'},
 {'patient_id': 92,
  'age': 62,
  'gender': 'M',
  'city': 'Mumbai',
  'insurance_provider': 'SecureLife',
  'chronic_flag': 0,
  'registration_date': '2025-08-28'},
 {'patient_id': 93,
  'age': 32,
  'gender': 'F',
  'city': 'Delhi',
  'insurance_provider': 'CareOne',
  'chronic_flag': 1,
  'registration_date': '2025-12-31'},
 {'patient_id': 94,
  'age': 39,
  'gender': 'M',
  'city': 'Chennai',
  'insurance_provider': 'CareOne',
  'chronic_flag': 0,
  'registration_date': '2025-12-23'},
 {'patient_id': 95,
  'age': 37,
  'gender': 'M',
  'city': 'Mumbai',
  'insurance_provider': 'SecureLife',
  'chronic_flag': 0,
  'registration_date': '2025-05-20'},
 {'patient_id': 96,
  'age': 18,
  'gender': 'F',
  'city': 'Bangalore',
  'insurance_provider': 'MediCareX',
  'chronic_flag': 0,
  'registration_date': '2025-02-01'},
 {'patient_id': 97,
  'age': 50,
  'gender': 'M',
  'city': 'Bangalore',
  'insurance_provider': 'CareOne',
  'chronic_flag': 0,
  'registration_date': '2025-09-10'},
 {'patient_id': 98,
  'age': 49,
  'gender': 'F',
  'city': 'Pune',
  'insurance_provider': 'MediCareX',
  'chronic_flag': 1,
  'registration_date': '2025-09-30'},
 {'patient_id': 99,
  'age': 45,
  'gender': 'F',
  'city': 'Bangalore',
  'insurance_provider': 'MediCareX',
  'chronic_flag': 0,
  'registration_date': '2025-03-15'},
 {'patient_id': 100,
  'age': 40,
  'gender': 'F',
  'city': 'Bangalore',
  'insurance_provider': 'MediCareX',
  'chronic_flag': 1,
  'registration_date': '2025-02-14'},
 {'patient_id': 101,
  'age': 19,
  'gender': 'M',
  'city': 'Hyderabad',
  'insurance_provider': 'CareOne',
  'chronic_flag': 0,
  'registration_date': '2025-09-14'},
 {'patient_id': 102,
  'age': 37,
  'gender': 'F',
  'city': 'Delhi',
  'insurance_provider': 'CareOne',
  'chronic_flag': 1,
  'registration_date': '2025-04-11'},
 {'patient_id': 103,
  'age': 38,
  'gender': 'F',
  'city': 'Delhi',
  'insurance_provider': 'SecureLife',
  'chronic_flag': 0,
  'registration_date': '2025-12-12'},
 {'patient_id': 104,
  'age': 30,
  'gender': 'F',
  'city': 'Chennai',
  'insurance_provider': 'CareOne',
  'chronic_flag': 0,
  'registration_date': '2025-06-09'},
 {'patient_id': 105,
  'age': 42,
  'gender': 'F',
  'city': 'Hyderabad',
  'insurance_provider': 'SecureLife',
  'chronic_flag': 0,
  'registration_date': '2025-06-08'},
 {'patient_id': 106,
  'age': 52,
  'gender': 'F',
  'city': 'Mumbai',
  'insurance_provider': 'HealthPlus',
  'chronic_flag': 0,
  'registration_date': '2025-04-07'},
 {'patient_id': 107,
  'age': 78,
  'gender': 'M',
  'city': 'Delhi',
  'insurance_provider': 'MediCareX',
  'chronic_flag': 0,
  'registration_date': '2025-02-21'},
 {'patient_id': 108,
  'age': 48,
  'gender': 'F',
  'city': 'Delhi',
  'insurance_provider': 'SecureLife',
  'chronic_flag': 1,
  'registration_date': '2025-08-20'},
 {'patient_id': 109,
  'age': 49,
  'gender': 'M',
  'city': 'Bangalore',
  'insurance_provider': 'CareOne',
  'chronic_flag': 1,
  'registration_date': '2025-11-15'},
 {'patient_id': 110,
  'age': 43,
  'gender': 'M',
  'city': 'Chennai',
  'insurance_provider': 'CareOne',
  'chronic_flag': 1,
  'registration_date': '2025-01-23'},
 {'patient_id': 111,
  'age': 10,
  'gender': 'F',
  'city': 'Mumbai',
  'insurance_provider': 'CareOne',
  'chronic_flag': 1,
  'registration_date': '2025-10-22'},
 {'patient_id': 112,
  'age': 44,
  'gender': 'M',
  'city': 'Delhi',
  'insurance_provider': 'MediCareX',
  'chronic_flag': 1,
  'registration_date': '2025-08-31'},
 {'patient_id': 113,
  'age': 46,
  'gender': 'F',
  'city': 'Hyderabad',
  'insurance_provider': 'CareOne',
  'chronic_flag': 1,
  'registration_date': '2025-12-28'},
 {'patient_id': 114,
  'age': 89,
  'gender': 'F',
  'city': 'Pune',
  'insurance_provider': 'MediCareX',
  'chronic_flag': 1,
  'registration_date': '2025-03-26'},
 {'patient_id': 115,
  'age': 41,
  'gender': 'M',
  'city': 'Delhi',
  'insurance_provider': 'HealthPlus',
  'chronic_flag': 0,
  'registration_date': '2025-12-15'},
 {'patient_id': 116,
  'age': 50,
  'gender': 'F',
  'city': 'Bangalore',
  'insurance_provider': 'CareOne',
  'chronic_flag': 0,
  'registration_date': '2025-02-14'},
 {'patient_id': 117,
  'age': 44,
  'gender': 'F',
  'city': 'Delhi',
  'insurance_provider': 'SecureLife',
  'chronic_flag': 0,
  'registration_date': '2025-09-09'},
 {'patient_id': 118,
  'age': 23,
  'gender': 'F',
  'city': 'Mumbai',
  'insurance_provider': 'CareOne',
  'chronic_flag': 1,
  'registration_date': '2025-08-23'},
 {'patient_id': 119,
  'age': 65,
  'gender': 'F',
  'city': 'Hyderabad',
  'insurance_provider': 'CareOne',
  'chronic_flag': 0,
  'registration_date': '2025-10-23'},
 {'patient_id': 120,
  'age': 58,
  'gender': 'M',
  'city': 'Mumbai',
  'insurance_provider': 'MediCareX',
  'chronic_flag': 0,

In [59]:
len(patient_data)

5000

In [ ]:
DB_NAME="hospital_miops"
COLLECTION_PATIENT="patient_data"
COLLECTION_VISITS="visits_data"
COLLECTION_BILLING="billing_data_data"
CONNECTION_URL="myurl"

In [22]:
import pymongo
import pandas as pd

In [23]:
client=pymongo.MongoClient(CONNECTION_URL)
db=client[DB_NAME]
patient_collection=db[COLLECTION_PATIENT]
visits_collection=db[COLLECTION_VISITS]
billing_collection=db[COLLECTION_BILLING]

patient_rec=patient_collection.insert_many(patient_data)
visits_rec=visits_collection.insert_many(visits_data)      
billing_rec=billing_collection.insert_many(billing_data)

NameError: name 'patient_data' is not defined

In [24]:
patient_df=pd.DataFrame(list(patient_collection.find()))
patient_df.head()

,_id,patient_id,age,gender,city,insurance_provider,chronic_flag,registration_date
0,6a286bfbdb5bb3abac6f50b5,1,53,M,Hyderabad,SecureLife,0,2025-05-14
1,6a286bfbdb5bb3abac6f50b6,2,42,M,Pune,HealthPlus,0,2025-11-18
2,6a286bfbdb5bb3abac6f50b7,3,56,F,Hyderabad,HealthPlus,0,2025-05-11
3,6a286bfbdb5bb3abac6f50b8,4,72,M,Chennai,HealthPlus,0,2025-12-18
4,6a286bfbdb5bb3abac6f50b9,5,40,F,Bangalore,CareOne,1,2025-01-23

In [25]:
billing_df=pd.DataFrame(list(billing_collection.find()))
billing_df.head()

,_id,bill_id,visit_id,billed_amount,approved_amount,claim_status,payment_days,billing_date
0,6a286c11db5bb3abac6fc5e5,1,1,23577.37,0.00,Rejected,16.0,2025-06-18
1,6a286c11db5bb3abac6fc5e6,2,2,38178.81,38178.81,Paid,18.0,2025-10-09
2,6a286c11db5bb3abac6fc5e7,3,3,5038.97,5038.97,Paid,NaN,2025-01-20
3,6a286c11db5bb3abac6fc5e8,4,4,22813.34,22813.34,Paid,16.0,2025-12-24
4,6a286c11db5bb3abac6fc5e9,5,5,27106.95,27106.95,Paid,14.0,2025-09-23

In [26]:
visits_df=pd.DataFrame(list(visits_collection.find()))
visits_df.head()

,_id,visit_id,patient_id,visit_date,department,visit_type,length_of_stay_hours,risk_score,doctor_id
0,6a286c04db5bb3abac6f643d,1,756,2025-10-18,Cardiology,ER,3.48,Low,169
1,6a286c04db5bb3abac6f643e,2,4102,2025-04-06,Orthopedics,OPD,15.31,High,148
2,6a286c04db5bb3abac6f643f,3,2964,2025-07-13,ICU,ER,34.36,Low,153
3,6a286c04db5bb3abac6f6440,4,4496,2025-11-19,Cardiology,ER,37.89,High,119
4,6a286c04db5bb3abac6f6441,5,1930,2025-03-29,General,ICU,16.78,Medium,118

In [27]:
if"_id" in patient_df.columns:
    patient_df.drop("_id",axis=1,inplace=True)
if"_id" in billing_df.columns:
    billing_df.drop("_id",axis=1,inplace=True)
if"_id" in visits_df.columns:
    visits_df.drop("_id",axis=1,inplace=True)

In [28]:
visits_df.head()

,visit_id,patient_id,visit_date,department,visit_type,length_of_stay_hours,risk_score,doctor_id
0,1,756,2025-10-18,Cardiology,ER,3.48,Low,169
1,2,4102,2025-04-06,Orthopedics,OPD,15.31,High,148
2,3,2964,2025-07-13,ICU,ER,34.36,Low,153
3,4,4496,2025-11-19,Cardiology,ER,37.89,High,119
4,5,1930,2025-03-29,General,ICU,16.78,Medium,118

In [3]:
# Create db folder, if it doesn't exits
import pandas as pd
import sqlite3
import os


os.makedirs("../db", exist_ok=True)

# Connect to sqlite and then create db
conn = sqlite3.connect("../db/hospital.db")
cursor = conn.cursor()
print("Database connected:", conn)

Database connected: <sqlite3.Connection object at 0x00000244AC8E3880>

In [4]:
billing = pd.read_csv("data/billing.csv")
visits = pd.read_csv("data/visits.csv")
patient = pd.read_csv("data/patients.csv")

print("patient shape :",patient.shape)
print("billing shape :",billing.shape)
print("visits shape :",visits.shape)
# write all three dataframes into sqlite tables
patient.to_sql("patients", conn, if_exists="replace", index=False)
visits.to_sql("visits", conn, if_exists="replace", index=False)
billing.to_sql("billing", conn, if_exists="replace", index=False)

print("All three tables loaded into hospital db")

patient shape : (5000, 7)
billing shape : (25000, 7)
visits shape : (25000, 8)
All three tables loaded into hospital db

In [8]:
# Quick preview of tables
print("=== PATIENTS (first 3 rows) ===")
print(pd.read_sql("select * from patients limit 5", conn).to_string())

print("=== VISITS (first 3 rows) ===")
print(pd.read_sql("select * from visits limit 5", conn).to_string())

print("=== BILLING (first 3 rows) ===")
print(pd.read_sql("select * from billing limit 5", conn).to_string())

=== PATIENTS (first 3 rows) ===
   patient_id  age gender       city insurance_provider  chronic_flag registration_date
0           1   53      M  Hyderabad         SecureLife             0        2025-05-14
1           2   42      M       Pune         HealthPlus             0        2025-11-18
2           3   56      F  Hyderabad         HealthPlus             0        2025-05-11
3           4   72      M    Chennai         HealthPlus             0        2025-12-18
4           5   40      F  Bangalore            CareOne             1        2025-01-23
=== VISITS (first 3 rows) ===
   visit_id  patient_id  visit_date   department visit_type  length_of_stay_hours risk_score  doctor_id
0         1         756  2025-10-18   Cardiology         ER                  3.48        Low        169
1         2        4102  2025-04-06  Orthopedics        OPD                 15.31       High        148
2         3        2964  2025-07-13          ICU         ER                 34.36        Low        153
3         4        4496  2025-11-19   Cardiology         ER                 37.89       High        119
4         5        1930  2025-03-29      General        ICU                 16.78     Medium        118
=== BILLING (first 3 rows) ===
   bill_id  visit_id  billed_amount  approved_amount claim_status  payment_days billing_date
0        1         1       23577.37             0.00     Rejected          16.0   2025-06-18
1        2         2       38178.81         38178.81         Paid          18.0   2025-10-09
2        3         3        5038.97          5038.97         Paid           NaN   2025-01-20
3        4         4       22813.34         22813.34         Paid          16.0   2025-12-24
4        5         5       27106.95         27106.95         Paid          14.0   2025-09-23

## Financial Analytics

In [17]:
#department workload analysis
query = """
SELECT department, COUNT(*) AS num_visits, 
ROUND(AVG(length_of_stay_hours),2) AS avg_stay_hours,
ROUND(MAX(length_of_stay_hours),2) AS max_stay_hours,
SUM(CASE
    WHEN risk_score = 'High'
    THEN 1
    ELSE 0
END) AS high_risk_count
FROM visits
GROUP BY department
order by num_visits DESC
"""
department_workload = pd.read_sql(query, conn)
print("Department Workload:")
print(department_workload.to_string(index=False))

Department Workload:
 department  num_visits  avg_stay_hours  max_stay_hours  high_risk_count
    General        4228           19.43           78.42              839
         ER        4220           19.53           74.81              872
  Neurology        4165           19.72           70.12              846
Orthopedics        4164           19.66           71.60              842
 Cardiology        4159           19.60           77.42              790
        ICU        4064           19.36           72.47              845

In [18]:
#which doctor handled most critical patients
query = """
SELECT 
        doctor_id,
        COUNT(visit_id)                              AS total_visits,
        SUM(CASE WHEN risk_score = 'High' 
            THEN 1 ELSE 0 END)                       AS high_risk_cases,
        ROUND(
            100.0 * SUM(CASE WHEN risk_score = 'High' 
            THEN 1 ELSE 0 END) / COUNT(visit_id), 1) AS high_risk_pct
    FROM visits
    GROUP BY doctor_id
    ORDER BY high_risk_cases DESC
    LIMIT 10
"""
doctor_risk = pd.read_sql(query, conn)
print("Doctor Risk Analysis:")
print(doctor_risk.to_string(index=False))

Doctor Risk Analysis:
 doctor_id  total_visits  high_risk_cases  high_risk_pct
       174           264               71           26.9
       198           252               69           27.4
       169           279               68           24.4
       177           266               67           25.2
       135           261               65           24.9
       105           250               65           26.0
       188           285               64           22.5
       180           290               64           22.1
       131           266               62           23.3
       178           245               61           24.9

In [23]:
#Patient Visit Patterns distribution
query = """
  SELECT 
        visit_frequency_bucket,
        COUNT(patient_id) AS num_patients
    FROM (
        SELECT 
            patient_id,
            COUNT(visit_id) AS visit_count,
            CASE 
                WHEN COUNT(visit_id) = 1     THEN '1 visit'
                WHEN COUNT(visit_id) BETWEEN 2 AND 3 THEN '2-3 visits'
                WHEN COUNT(visit_id) BETWEEN 4 AND 5 THEN '4-5 visits'
                ELSE '6+ visits'
            END AS visit_frequency_bucket
        FROM visits
        GROUP BY patient_id
    )
    GROUP BY visit_frequency_bucket
    ORDER BY num_patients DESC

"""
visit_patterns = pd.read_sql(query, conn)
print("Visit Patterns Analysis:")
print(visit_patterns.to_string(index=False))

Visit Patterns Analysis:
visit_frequency_bucket  num_patients
             6+ visits          1937
            4-5 visits          1731
            2-3 visits          1150
               1 visit           149

In [25]:
# Risk Score Distribution
query = """
   SELECT 
        department,
        SUM(CASE WHEN risk_score = 'Low'    THEN 1 ELSE 0 END) AS low,
        SUM(CASE WHEN risk_score = 'Medium' THEN 1 ELSE 0 END) AS medium,
        SUM(CASE WHEN risk_score = 'High'   THEN 1 ELSE 0 END) AS high,
        COUNT(*) AS total
    FROM visits
    GROUP BY department
    ORDER BY high DESC

"""
risk_by_dept = pd.read_sql(query, conn)
print("Risk Score Distribution by Department:")
print(risk_by_dept.to_string(index=False))

Risk Score Distribution by Department:
 department  low  medium  high  total
         ER 2092    1256   872   4220
  Neurology 2058    1261   846   4165
        ICU 2037    1182   845   4064
Orthopedics 2078    1244   842   4164
    General 2123    1266   839   4228
 Cardiology 2082    1287   790   4159

## Financial Analytics

In [28]:
#  Revenue and claim outcomes by insurance provider
query = """
  SELECT 
        p.insurance_provider,
        COUNT(b.bill_id)                         AS total_claims,
        ROUND(SUM(b.billed_amount), 0)           AS total_billed,
        ROUND(AVG(b.billed_amount), 0)           AS avg_billed,
        ROUND(SUM(b.approved_amount), 0)         AS total_approved,
        SUM(CASE WHEN b.claim_status = 'Paid'     
            THEN 1 ELSE 0 END)                   AS paid,
        SUM(CASE WHEN b.claim_status = 'Pending'  
            THEN 1 ELSE 0 END)                   AS pending,
        SUM(CASE WHEN b.claim_status = 'Rejected' 
            THEN 1 ELSE 0 END)                   AS rejected
    FROM billing b
    JOIN visits  v ON b.visit_id   = v.visit_id
    JOIN patients p ON v.patient_id = p.patient_id
    GROUP BY p.insurance_provider
    ORDER BY total_billed DESC

"""
insurance_billing = pd.read_sql(query, conn)
print("Risk Score Distribution by Department:")
print(insurance_billing.to_string(index=False))

Risk Score Distribution by Department:
insurance_provider  total_claims  total_billed  avg_billed  total_approved  paid  pending  rejected
         MediCareX          6532   134591163.0     20605.0     100135469.0  3875     1661       996
           CareOne          6283   130707993.0     20803.0      96997758.0  3787     1562       934
        HealthPlus          6220   130180741.0     20929.0      96251775.0  3680     1609       931
        SecureLife          5965   126289040.0     21172.0      93770886.0  3598     1431       936

In [29]:
# Which insurance providers reject the most claims?
query = """
 SELECT 
        p.insurance_provider,
        COUNT(b.bill_id)                              AS total_claims,
        SUM(CASE WHEN b.claim_status = 'Rejected' 
            THEN 1 ELSE 0 END)                        AS rejected_claims,
        ROUND(
            100.0 * SUM(CASE WHEN b.claim_status = 'Rejected' 
            THEN 1 ELSE 0 END) / COUNT(b.bill_id), 1) AS rejection_rate_pct
    FROM billing b
    JOIN visits   v ON b.visit_id   = v.visit_id
    JOIN patients p ON v.patient_id = p.patient_id
    GROUP BY p.insurance_provider
    ORDER BY rejection_rate_pct DESC

"""
rejection_analysis = pd.read_sql(query, conn)
print("Claim Rejection Analysis by Insurance Provider:")
print(rejection_analysis.to_string(index=False))

Claim Rejection Analysis by Insurance Provider:
insurance_provider  total_claims  rejected_claims  rejection_rate_pct
        SecureLife          5965              936                15.7
         MediCareX          6532              996                15.2
        HealthPlus          6220              931                15.0
           CareOne          6283              934                14.9

In [30]:
#How much of what we bill actually gets approved
query = """
    SELECT 
        p.insurance_provider,
        ROUND(SUM(b.billed_amount), 0)                AS total_billed,
        ROUND(SUM(b.approved_amount), 0)              AS total_approved,
        ROUND(
            100.0 * SUM(b.approved_amount) / 
            SUM(b.billed_amount), 1)                  AS realization_rate_pct
    FROM billing b
    JOIN visits   v ON b.visit_id   = v.visit_id
    JOIN patients p ON v.patient_id = p.patient_id
    WHERE b.approved_amount IS NOT NULL
    GROUP BY p.insurance_provider
    ORDER BY realization_rate_pct DESC

"""
revenue_realization = pd.read_sql(query, conn)
print("Revenue Realization Analysis by Insurance Provider:")
print(revenue_realization.to_string(index=False))

Revenue Realization Analysis by Insurance Provider:
insurance_provider  total_billed  total_approved  realization_rate_pct
           CareOne   123701662.0      96997758.0                  78.4
        HealthPlus   122873457.0      96251775.0                  78.3
         MediCareX   128114983.0     100135469.0                  78.2
        SecureLife   120079039.0      93770886.0                  78.1

## Data Quality

In [31]:
# Missing Records Check
print("=== MISSING VALUES CHECK ===\n")

for table in ['patients', 'visits', 'billing']:
    df = pd.read_sql(f"SELECT * FROM {table}", conn)
    nulls = df.isnull().sum()
    nulls = nulls[nulls > 0]
    if len(nulls) > 0:
        print(f"{table}:")
        print(nulls.to_string())
        print()
    else:
        print(f"{table}: ✓ No missing values\n")

=== MISSING VALUES CHECK ===

patients: ✓ No missing values

visits: ✓ No missing values

billing:
approved_amount    1318
payment_days        790

In [32]:
# Duplicate Patients Check
duplicate_patients = pd.read_sql("""
    SELECT 
        patient_id,
        COUNT(*) AS occurrences
    FROM patients
    GROUP BY patient_id
    HAVING COUNT(*) > 1
""", conn)

if len(duplicate_patients) == 0:
    print("✓ No duplicate patient_ids found")
else:
    print(f"⚠ Found {len(duplicate_patients)} duplicate patient_ids")
    print(duplicate_patients)

✓ No duplicate patient_ids found

In [33]:
# Orphan Records Check
# Visits without matching patients
orphan_visits = pd.read_sql("""
    SELECT COUNT(*) AS orphan_visits
    FROM visits v
    LEFT JOIN patients p ON v.patient_id = p.patient_id
    WHERE p.patient_id IS NULL
""", conn)

# Billing without matching visits
orphan_billing = pd.read_sql("""
    SELECT COUNT(*) AS orphan_billing
    FROM billing b
    LEFT JOIN visits v ON b.visit_id = v.visit_id
    WHERE v.visit_id IS NULL
""", conn)

print("Orphan visits  (no matching patient):", 
      orphan_visits['orphan_visits'][0])
print("Orphan billing (no matching visit)  :", 
      orphan_billing['orphan_billing'][0])

Orphan visits  (no matching patient): 0
Orphan billing (no matching visit)  : 0

In [34]:
#Invalid LOS Check
invalid_los = pd.read_sql("""
    SELECT 
        COUNT(CASE WHEN length_of_stay_hours <= 0  THEN 1 END) AS zero_or_negative,
        COUNT(CASE WHEN length_of_stay_hours > 720 THEN 1 END) AS over_30_days,
        MIN(length_of_stay_hours)                              AS min_los,
        MAX(length_of_stay_hours)                             AS max_los,
        ROUND(AVG(length_of_stay_hours), 2)                   AS avg_los
    FROM visits
""", conn)

print("LOS Validation:")
print(invalid_los.to_string(index=False))

LOS Validation:
 zero_or_negative  over_30_days  min_los  max_los  avg_los
                0             0      0.5    78.42    19.55

In [35]:
# Invalid Payment Days Check
invalid_payment = pd.read_sql("""
    SELECT 
        COUNT(CASE WHEN payment_days < 0   THEN 1 END) AS negative_days,
        COUNT(CASE WHEN payment_days > 365 THEN 1 END) AS over_1_year,
        COUNT(CASE WHEN payment_days IS NULL THEN 1 END) AS nulls,
        MIN(payment_days)                               AS min_days,
        MAX(payment_days)                               AS max_days
    FROM billing
""", conn)

print("Payment Days Validation:")
print(invalid_payment.to_string(index=False))

Payment Days Validation:
 negative_days  over_1_year  nulls  min_days  max_days
             0            0    790       1.0      55.0

In [36]:
# Join all three tables into one flat table for ML modeling.
# This is the single source of truth for Phase 2 EDA and Phase 3 Modeling.
model_table = pd.read_sql("""
    SELECT
        -- Patient features
        p.patient_id,
        p.age,
        p.gender,
        p.city,
        p.insurance_provider,
        p.chronic_flag,
        p.registration_date,

        -- Visit features
        v.visit_id,
        v.visit_date,
        v.department,
        v.visit_type,
        v.length_of_stay_hours,
        v.risk_score,
        v.doctor_id,

        -- Billing features
        b.bill_id,
        b.billed_amount,
        b.approved_amount,
        b.claim_status,
        b.payment_days,
        b.billing_date

    FROM visits v
    JOIN patients p ON v.patient_id = p.patient_id
    JOIN billing  b ON v.visit_id   = b.visit_id
    ORDER BY v.visit_date
""", conn)

print("model_table shape:", model_table.shape)
print("Columns:", model_table.columns.tolist())
model_table.head(3)

model_table shape: (25000, 20)
Columns: ['patient_id', 'age', 'gender', 'city', 'insurance_provider', 'chronic_flag', 'registration_date', 'visit_id', 'visit_date', 'department', 'visit_type', 'length_of_stay_hours', 'risk_score', 'doctor_id', 'bill_id', 'billed_amount', 'approved_amount', 'claim_status', 'payment_days', 'billing_date']

,patient_id,age,gender,city,insurance_provider,chronic_flag,registration_date,visit_id,visit_date,department,visit_type,length_of_stay_hours,risk_score,doctor_id,bill_id,billed_amount,approved_amount,claim_status,payment_days,billing_date
0,3993,9,M,Hyderabad,HealthPlus,1,2025-10-18,684,2025-01-20,General,ICU,5.79,Low,137,684,36721.68,36721.68,Paid,19.0,2025-08-15
1,76,59,M,Delhi,HealthPlus,0,2025-07-09,1412,2025-01-20,General,ER,34.80,Medium,109,1412,8365.47,4189.20,Pending,26.0,2025-11-14
2,3393,43,M,Hyderabad,HealthPlus,0,2025-07-10,1510,2025-01-20,ICU,ICU,31.37,Medium,135,1510,16529.35,0.00,Rejected,7.0,2025-04-24

In [37]:
# save the table
import os
os.makedirs("../outputs", exist_ok=True)
model_table.to_csv("../outputs/model_table.csv", index=False)
print(f"model_table.csv saved --> /outputs/model_table.csv")
print(f"Shape: {model_table.shape}")
print(f"Size: {os.path.getsize('../outputs/model_table.csv')/1024:.1f} KB")

model_table.csv saved --> /outputs/model_table.csv
Shape: (25000, 20)
Size: 3126.7 KB

In [38]:
model_table= pd.read_csv("../outputs/model_table.csv")
model_table.head()

,patient_id,age,gender,city,insurance_provider,chronic_flag,registration_date,visit_id,visit_date,department,visit_type,length_of_stay_hours,risk_score,doctor_id,bill_id,billed_amount,approved_amount,claim_status,payment_days,billing_date
0,3993,9,M,Hyderabad,HealthPlus,1,2025-10-18,684,2025-01-20,General,ICU,5.79,Low,137,684,36721.68,36721.68,Paid,19.0,2025-08-15
1,76,59,M,Delhi,HealthPlus,0,2025-07-09,1412,2025-01-20,General,ER,34.80,Medium,109,1412,8365.47,4189.20,Pending,26.0,2025-11-14
2,3393,43,M,Hyderabad,HealthPlus,0,2025-07-10,1510,2025-01-20,ICU,ICU,31.37,Medium,135,1510,16529.35,0.00,Rejected,7.0,2025-04-24
3,1998,29,M,Bangalore,MediCareX,1,2025-04-22,1549,2025-01-20,Cardiology,ER,20.88,Medium,179,1549,61827.63,61827.63,Paid,1.0,2025-10-17
4,3500,38,M,Hyderabad,CareOne,1,2025-08-02,2275,2025-01-20,Orthopedics,ICU,4.97,Low,107,2275,5860.51,4897.65,Pending,28.0,2025-08-05

In [40]:
model_table_df= model_table.to_dict(orient="records")
model_table_df

[{'patient_id': 3993,
  'age': 9,
  'gender': 'M',
  'city': 'Hyderabad',
  'insurance_provider': 'HealthPlus',
  'chronic_flag': 1,
  'registration_date': '2025-10-18',
  'visit_id': 684,
  'visit_date': '2025-01-20',
  'department': 'General',
  'visit_type': 'ICU',
  'length_of_stay_hours': 5.79,
  'risk_score': 'Low',
  'doctor_id': 137,
  'bill_id': 684,
  'billed_amount': 36721.68,
  'approved_amount': 36721.68,
  'claim_status': 'Paid',
  'payment_days': 19.0,
  'billing_date': '2025-08-15'},
 {'patient_id': 76,
  'age': 59,
  'gender': 'M',
  'city': 'Delhi',
  'insurance_provider': 'HealthPlus',
  'chronic_flag': 0,
  'registration_date': '2025-07-09',
  'visit_id': 1412,
  'visit_date': '2025-01-20',
  'department': 'General',
  'visit_type': 'ER',
  'length_of_stay_hours': 34.8,
  'risk_score': 'Medium',
  'doctor_id': 109,
  'bill_id': 1412,
  'billed_amount': 8365.47,
  'approved_amount': 4189.2,
  'claim_status': 'Pending',
  'payment_days': 26.0,
  'billing_date': '2025-11-14'},
 {'patient_id': 3393,
  'age': 43,
  'gender': 'M',
  'city': 'Hyderabad',
  'insurance_provider': 'HealthPlus',
  'chronic_flag': 0,
  'registration_date': '2025-07-10',
  'visit_id': 1510,
  'visit_date': '2025-01-20',
  'department': 'ICU',
  'visit_type': 'ICU',
  'length_of_stay_hours': 31.37,
  'risk_score': 'Medium',
  'doctor_id': 135,
  'bill_id': 1510,
  'billed_amount': 16529.35,
  'approved_amount': 0.0,
  'claim_status': 'Rejected',
  'payment_days': 7.0,
  'billing_date': '2025-04-24'},
 {'patient_id': 1998,
  'age': 29,
  'gender': 'M',
  'city': 'Bangalore',
  'insurance_provider': 'MediCareX',
  'chronic_flag': 1,
  'registration_date': '2025-04-22',
  'visit_id': 1549,
  'visit_date': '2025-01-20',
  'department': 'Cardiology',
  'visit_type': 'ER',
  'length_of_stay_hours': 20.88,
  'risk_score': 'Medium',
  'doctor_id': 179,
  'bill_id': 1549,
  'billed_amount': 61827.63,
  'approved_amount': 61827.63,
  'claim_status': 'Paid',
  'payment_days': 1.0,
  'billing_date': '2025-10-17'},
 {'patient_id': 3500,
  'age': 38,
  'gender': 'M',
  'city': 'Hyderabad',
  'insurance_provider': 'CareOne',
  'chronic_flag': 1,
  'registration_date': '2025-08-02',
  'visit_id': 2275,
  'visit_date': '2025-01-20',
  'department': 'Orthopedics',
  'visit_type': 'ICU',
  'length_of_stay_hours': 4.97,
  'risk_score': 'Low',
  'doctor_id': 107,
  'bill_id': 2275,
  'billed_amount': 5860.51,
  'approved_amount': 4897.65,
  'claim_status': 'Pending',
  'payment_days': 28.0,
  'billing_date': '2025-08-05'},
 {'patient_id': 3286,
  'age': 72,
  'gender': 'F',
  'city': 'Delhi',
  'insurance_provider': 'HealthPlus',
  'chronic_flag': 1,
  'registration_date': '2025-01-21',
  'visit_id': 2287,
  'visit_date': '2025-01-20',
  'department': 'Cardiology',
  'visit_type': 'OPD',
  'length_of_stay_hours': 21.13,
  'risk_score': 'High',
  'doctor_id': 165,
  'bill_id': 2287,
  'billed_amount': 18756.25,
  'approved_amount': 0.0,
  'claim_status': 'Rejected',
  'payment_days': 12.0,
  'billing_date': '2025-12-30'},
 {'patient_id': 152,
  'age': 51,
  'gender': 'M',
  'city': 'Chennai',
  'insurance_provider': 'HealthPlus',
  'chronic_flag': 0,
  'registration_date': '2025-04-06',
  'visit_id': 3141,
  'visit_date': '2025-01-20',
  'department': 'ICU',
  'visit_type': 'OPD',
  'length_of_stay_hours': 27.36,
  'risk_score': 'Medium',
  'doctor_id': 160,
  'bill_id': 3141,
  'billed_amount': 16289.04,
  'approved_amount': 16289.04,
  'claim_status': 'Paid',
  'payment_days': 3.0,
  'billing_date': '2025-11-29'},
 {'patient_id': 532,
  'age': 15,
  'gender': 'M',
  'city': 'Mumbai',
  'insurance_provider': 'HealthPlus',
  'chronic_flag': 1,
  'registration_date': '2025-03-14',
  'visit_id': 3704,
  'visit_date': '2025-01-20',
  'department': 'Orthopedics',
  'visit_type': 'OPD',
  'length_of_stay_hours': 2.04,
  'risk_score': 'Medium',
  'doctor_id': 190,
  'bill_id': 3704,
  'billed_amount': 31393.59,
  'approved_amount': 31393.59,
  'claim_status': 'Paid',
  'payment_days': 14.0,
  'billing_date': '2025-11-28'},
 {'patient_id': 4451,
  'age': 36,
  'gender': 'M',
  'city': 'Delhi',
  'insurance_provider': 'SecureLife',
  'chronic_flag': 0,
  'registration_date': '2025-05-13',
  'visit_id': 3955,
  'visit_date': '2025-01-20',
  'department': 'Neurology',
  'visit_type': 'ER',
  'length_of_stay_hours': 15.87,
  'risk_score': 'Low',
  'doctor_id': 166,
  'bill_id': 3955,
  'billed_amount': 27956.09,
  'approved_amount': 23012.97,
  'claim_status': 'Pending',
  'payment_days': 2.0,
  'billing_date': '2025-05-01'},
 {'patient_id': 2826,
  'age': 75,
  'gender': 'F',
  'city': 'Bangalore',
  'insurance_provider': 'SecureLife',
  'chronic_flag': 1,
  'registration_date': '2026-01-08',
  'visit_id': 4288,
  'visit_date': '2025-01-20',
  'department': 'Neurology',
  'visit_type': 'OPD',
  'length_of_stay_hours': 26.92,
  'risk_score': 'Low',
  'doctor_id': 162,
  'bill_id': 4288,
  'billed_amount': 15857.69,
  'approved_amount': 12440.45,
  'claim_status': 'Pending',
  'payment_days': 21.0,
  'billing_date': '2025-09-10'},
 {'patient_id': 128,
  'age': 34,
  'gender': 'M',
  'city': 'Mumbai',
  'insurance_provider': 'CareOne',
  'chronic_flag': 1,
  'registration_date': '2025-02-24',
  'visit_id': 4866,
  'visit_date': '2025-01-20',
  'department': 'General',
  'visit_type': 'OPD',
  'length_of_stay_hours': 23.72,
  'risk_score': 'Low',
  'doctor_id': 126,
  'bill_id': 4866,
  'billed_amount': 3483.79,
  'approved_amount': 3483.79,
  'claim_status': 'Paid',
  'payment_days': 12.0,
  'billing_date': '2025-09-28'},
 {'patient_id': 3393,
  'age': 43,
  'gender': 'M',
  'city': 'Hyderabad',
  'insurance_provider': 'HealthPlus',
  'chronic_flag': 0,
  'registration_date': '2025-07-10',
  'visit_id': 4949,
  'visit_date': '2025-01-20',
  'department': 'ER',
  'visit_type': 'ICU',
  'length_of_stay_hours': 21.9,
  'risk_score': 'Medium',
  'doctor_id': 177,
  'bill_id': 4949,
  'billed_amount': 18254.46,
  'approved_amount': 18254.46,
  'claim_status': 'Paid',
  'payment_days': 17.0,
  'billing_date': '2026-01-13'},
 {'patient_id': 2072,
  'age': 67,
  'gender': 'F',
  'city': 'Mumbai',
  'insurance_provider': 'HealthPlus',
  'chronic_flag': 1,
  'registration_date': '2025-10-06',
  'visit_id': 5095,
  'visit_date': '2025-01-20',
  'department': 'ER',
  'visit_type': 'OPD',
  'length_of_stay_hours': 17.26,
  'risk_score': 'Low',
  'doctor_id': 145,
  'bill_id': 5095,
  'billed_amount': 16683.54,
  'approved_amount': 16683.54,
  'claim_status': 'Paid',
  'payment_days': 15.0,
  'billing_date': '2025-02-11'},
 {'patient_id': 586,
  'age': 49,
  'gender': 'F',
  'city': 'Pune',
  'insurance_provider': 'MediCareX',
  'chronic_flag': 1,
  'registration_date': '2025-02-25',
  'visit_id': 5128,
  'visit_date': '2025-01-20',
  'department': 'Orthopedics',
  'visit_type': 'ICU',
  'length_of_stay_hours': 18.74,
  'risk_score': 'High',
  'doctor_id': 146,
  'bill_id': 5128,
  'billed_amount': 21522.01,
  'approved_amount': 21522.01,
  'claim_status': 'Paid',
  'payment_days': 26.0,
  'billing_date': '2025-05-03'},
 {'patient_id': 665,
  'age': 32,
  'gender': 'M',
  'city': 'Hyderabad',
  'insurance_provider': 'HealthPlus',
  'chronic_flag': 0,
  'registration_date': '2025-11-24',
  'visit_id': 5204,
  'visit_date': '2025-01-20',
  'department': 'Neurology',
  'visit_type': 'ER',
  'length_of_stay_hours': 19.06,
  'risk_score': 'Low',
  'doctor_id': 183,
  'bill_id': 5204,
  'billed_amount': 28610.16,
  'approved_amount': 15749.91,
  'claim_status': 'Pending',
  'payment_days': 9.0,
  'billing_date': '2025-09-28'},
 {'patient_id': 4599,
  'age': 52,
  'gender': 'M',
  'city': 'Mumbai',
  'insurance_provider': 'CareOne',
  'chronic_flag': 0,
  'registration_date': '2025-03-25',
  'visit_id': 5557,
  'visit_date': '2025-01-20',
  'department': 'Orthopedics',
  'visit_type': 'ER',
  'length_of_stay_hours': 23.92,
  'risk_score': 'High',
  'doctor_id': 156,
  'bill_id': 5557,
  'billed_amount': 25348.28,
  'approved_amount': 0.0,
  'claim_status': 'Rejected',
  'payment_days': 1.0,
  'billing_date': '2025-08-04'},
 {'patient_id': 2027,
  'age': 77,
  'gender': 'F',
  'city': 'Chennai',
  'insurance_provider': 'MediCareX',
  'chronic_flag': 1,
  'registration_date': '2025-03-03',
  'visit_id': 5914,
  'visit_date': '2025-01-20',
  'department': 'Cardiology',
  'visit_type': 'ER',
  'length_of_stay_hours': 15.51,
  'risk_score': 'High',
  'doctor_id': 124,
  'bill_id': 5914,
  'billed_amount': 28166.5,
  'approved_amount': 22953.54,
  'claim_status': 'Pending',
  'payment_days': 5.0,
  'billing_date': '2025-03-06'},
 {'patient_id': 109,
  'age': 49,
  'gender': 'M',
  'city': 'Bangalore',
  'insurance_provider': 'CareOne',
  'chronic_flag': 1,
  'registration_date': '2025-11-15',
  'visit_id': 5959,
  'visit_date': '2025-01-20',
  'department': 'Cardiology',
  'visit_type': 'ER',
  'length_of_stay_hours': 35.18,
  'risk_score': 'Low',
  'doctor_id': 188,
  'bill_id': 5959,
  'billed_amount': 12399.88,
  'approved_amount': 0.0,
  'claim_status': 'Rejected',
  'payment_days': 19.0,
  'billing_date': '2025-10-21'},
 {'patient_id': 4068,
  'age': 50,
  'gender': 'F',
  'city': 'Chennai',
  'insurance_provider': 'CareOne',
  'chronic_flag': 1,
  'registration_date': '2025-06-27',
  'visit_id': 6263,
  'visit_date': '2025-01-20',
  'department': 'ICU',
  'visit_type': 'OPD',
  'length_of_stay_hours': 20.27,
  'risk_score': 'High',
  'doctor_id': 121,
  'bill_id': 6263,
  'billed_amount': 29260.99,
  'approved_amount': 29260.99,
  'claim_status': 'Paid',
  'payment_days': 17.0,
  'billing_date': '2025-08-10'},
 {'patient_id': 4946,
  'age': 63,
  'gender': 'F',
  'city': 'Delhi',
  'insurance_provider': 'SecureLife',
  'chronic_flag': 0,
  'registration_date': '2025-12-12',
  'visit_id': 6402,
  'visit_date': '2025-01-20',
  'department': 'General',
  'visit_type': 'OPD',
  'length_of_stay_hours': 25.62,
  'risk_score': 'Medium',
  'doctor_id': 155,
  'bill_id': 6402,
  'billed_amount': 58503.2,
  'approved_amount': 58503.2,
  'claim_status': 'Paid',
  'payment_days': 3.0,
  'billing_date': '2025-09-26'},
 {'patient_id': 3933,
  'age': 60,
  'gender': 'M',
  'city': 'Hyderabad',
  'insurance_provider': 'HealthPlus',
  'chronic_flag': 0,
  'registration_date': '2025-10-29',
  'visit_id': 6414,
  'visit_date': '2025-01-20',
  'department': 'Orthopedics',
  'visit_type': 'ER',
  'length_of_stay_hours': 17.13,
  'risk_score': 'Low',
  'doctor_id': 168,
  'bill_id': 6414,
  'billed_amount': 33789.5,
  'approved_amount': 33789.5,
  'claim_status': 'Paid',
  'payment_days': 17.0,
  'billing_date': '2025-05-03'},
 {'patient_id': 3411,
  'age': 32,
  'gender': 'M',
  'city': 'Pune',
  'insurance_provider': 'CareOne',
  'chronic_flag': 0,
  'registration_date': '2025-07-03',
  'visit_id': 6442,
  'visit_date': '2025-01-20',
  'department': 'Orthopedics',
  'visit_type': 'ER',
  'length_of_stay_hours': 15.21,
  'risk_score': 'Medium',
  'doctor_id': 133,
  'bill_id': 6442,
  'billed_amount': 3267.59,
  'approved_amount': 2016.13,
  'claim_status': 'Pending',
  'payment_days': 29.0,
  'billing_date': '2025-06-17'},
 {'patient_id': 495,
  'age': 72,
  'gender': 'F',
  'city': 'Hyderabad',
  'insurance_provider': 'MediCareX',
  'chronic_flag': 0,
  'registration_date': '2026-01-19',
  'visit_id': 6506,
  'visit_date': '2025-01-20',
  'department': 'Cardiology',
  'visit_type': 'OPD',
  'length_of_stay_hours': 13.42,
  'risk_score': 'Low',
  'doctor_id': 121,
  'bill_id': 6506,
  'billed_amount': 15048.62,
  'approved_amount': 15048.62,
  'claim_status': 'Paid',
  'payment_days': 11.0,
  'billing_date': '2025-09-20'},
 {'patient_id': 3068,
  'age': 45,
  'gender': 'M',
  'city': 'Chennai',
  'insurance_provider': 'MediCareX',
  'chronic_flag': 0,
  'registration_date': '2025-12-06',
  'visit_id': 6618,
  'visit_date': '2025-01-20',
  'department': 'General',
  'visit_type': 'ICU',
  'length_of_stay_hours': 21.1,
  'risk_score': 'Low',
  'doctor_id': 144,
  'bill_id': 6618,
  'billed_amount': 37014.63,
  'approved_amount': 37014.63,
  'claim_status': 'Paid',
  'payment_days': 19.0,
  'billing_date': '2026-01-13'},
 {'patient_id': 2673,
  'age': 49,
  'gender': 'F',
  'city': 'Hyderabad',
  'insurance_provider': 'MediCareX',
  'chronic_flag': 1,
  'registration_date': '2025-03-24',
  'visit_id': 6783,
  'visit_date': '2025-01-20',
  'department': 'Orthopedics',
  'visit_type': 'ER',
  'length_of_stay_hours': 10.8,
  'risk_score': 'Medium',
  'doctor_id': 113,
  'bill_id': 6783,
  'billed_amount': 22955.11,
  'approved_amount': 0.0,
  'claim_status': 'Rejected',
  'payment_days': 16.0,
  'billing_date': '2025-04-19'},
 {'patient_id': 4808,
  'age': 56,
  'gender': 'M',
  'city': 'Pune',
  'insurance_provider': 'MediCareX',
  'chronic_flag': 1,
  'registration_date': '2025-12-24',
  'visit_id': 7033,
  'visit_date': '2025-01-20',
  'department': 'Orthopedics',
  'visit_type': 'ER',
  'length_of_stay_hours': 1.91,
  'risk_score': 'Low',
  'doctor_id': 141,
  'bill_id': 7033,
  'billed_amount': 28009.75,
  'approved_amount': 28009.75,
  'claim_status': 'Paid',
  'payment_days': 12.0,
  'billing_date': '2025-10-17'},
 {'patient_id': 1264,
  'age': 28,
  'gender': 'M',
  'city': 'Delhi',
  'insurance_provider': 'HealthPlus',
  'chronic_flag': 0,
  'registration_date': '2026-01-14',
  'visit_id': 7308,
  'visit_date': '2025-01-20',
  'department': 'ER',
  'visit_type': 'ICU',
  'length_of_stay_hours': 44.32,
  'risk_score': 'Medium',
  'doctor_id': 178,
  'bill_id': 7308,
  'billed_amount': 3369.28,
  'approved_amount': 3369.28,
  'claim_status': 'Paid',
  'payment_days': 13.0,
  'billing_date': '2025-12-28'},
 {'patient_id': 3919,
  'age': 62,
  'gender': 'M',
  'city': 'Pune',
  'insurance_provider': 'MediCareX',
  'chronic_flag': 0,
  'registration_date': '2025-09-04',
  'visit_id': 7471,
  'visit_date': '2025-01-20',
  'department': 'ER',
  'visit_type': 'ER',
  'length_of_stay_hours': 11.46,
  'risk_score': 'Low',
  'doctor_id': 181,
  'bill_id': 7471,
  'billed_amount': 7980.21,
  'approved_amount': 7980.21,
  'claim_status': 'Paid',
  'payment_days': 13.0,
  'billing_date': '2025-12-24'},
 {'patient_id': 93,
  'age': 32,
  'gender': 'F',
  'city': 'Delhi',
  'insurance_provider': 'CareOne',
  'chronic_flag': 1,
  'registration_date': '2025-12-31',
  'visit_id': 7472,
  'visit_date': '2025-01-20',
  'department': 'Neurology',
  'visit_type': 'OPD',
  'length_of_stay_hours': 35.83,
  'risk_score': 'Medium',
  'doctor_id': 182,
  'bill_id': 7472,
  'billed_amount': 28415.72,
  'approved_amount': 28415.72,
  'claim_status': 'Paid',
  'payment_days': 7.0,
  'billing_date': '2025-10-26'},
 {'patient_id': 1079,
  'age': 72,
  'gender': 'M',
  'city': 'Chennai',
  'insurance_provider': 'CareOne',
  'chronic_flag': 0,
  'registration_date': '2025-02-09',
  'visit_id': 8790,
  'visit_date': '2025-01-20',
  'department': 'General',
  'visit_type': 'ICU',
  'length_of_stay_hours': 1.07,
  'risk_score': 'Medium',
  'doctor_id': 122,
  'bill_id': 8790,
  'billed_amount': 7348.37,
  'approved_amount': 4877.41,
  'claim_status': 'Pending',
  'payment_days': 16.0,
  'billing_date': '2025-06-25'},
 {'patient_id': 2294,
  'age': 30,
  'gender': 'F',
  'city': 'Mumbai',
  'insurance_provider': 'MediCareX',
  'chronic_flag': 0,
  'registration_date': '2025-02-17',
  'visit_id': 9687,
  'visit_date': '2025-01-20',
  'department': 'General',
  'visit_type': 'OPD',
  'length_of_stay_hours': 23.75,
  'risk_score': 'High',
  'doctor_id': 118,
  'bill_id': 9687,
  'billed_amount': 19760.98,
  'approved_amount': 19760.98,
  'claim_status': 'Paid',
  'payment_days': 2.0,
  'billing_date': '2025-08-06'},
 {'patient_id': 4887,
  'age': 31,
  'gender': 'M',
  'city': 'Pune',
  'insurance_provider': 'HealthPlus',
  'chronic_flag': 1,
  'registration_date': '2025-10-01',
  'visit_id': 9727,
  'visit_date': '2025-01-20',
  'department': 'ER',
  'visit_type': 'ICU',
  'length_of_stay_hours': 3.47,
  'risk_score': 'Low',
  'doctor_id': 160,
  'bill_id': 9727,
  'billed_amount': 15948.64,
  'approved_amount': 0.0,
  'claim_status': 'Rejected',
  'payment_days': 2.0,
  'billing_date': '2025-12-21'},
 {'patient_id': 3854,
  'age': 25,
  'gender': 'F',
  'city': 'Chennai',
  'insurance_provider': 'HealthPlus',
  'chronic_flag': 0,
  'registration_date': '2025-02-25',
  'visit_id': 10392,
  'visit_date': '2025-01-20',
  'department': 'Neurology',
  'visit_type': 'OPD',
  'length_of_stay_hours': 11.37,
  'risk_score': 'Medium',
  'doctor_id': 170,
  'bill_id': 10392,
  'billed_amount': 21477.41,
  'approved_amount': 21477.41,
  'claim_status': 'Paid',
  'payment_days': 14.0,
  'billing_date': '2025-06-02'},
 {'patient_id': 737,
  'age': 49,
  'gender': 'M',
  'city': 'Delhi',
  'insurance_provider': 'HealthPlus',
  'chronic_flag': 1,
  'registration_date': '2025-06-10',
  'visit_id': 10517,
  'visit_date': '2025-01-20',
  'department': 'Orthopedics',
  'visit_type': 'ICU',
  'length_of_stay_hours': 32.4,
  'risk_score': 'Low',
  'doctor_id': 171,
  'bill_id': 10517,
  'billed_amount': 18237.68,
  'approved_amount': 0.0,
  'claim_status': 'Rejected',
  'payment_days': 29.0,
  'billing_date': '2025-08-08'},
 {'patient_id': 90,
  'age': 54,
  'gender': 'M',
  'city': 'Bangalore',
  'insurance_provider': 'CareOne',
  'chronic_flag': 1,
  'registration_date': '2026-01-01',
  'visit_id': 10582,
  'visit_date': '2025-01-20',
  'department': 'Cardiology',
  'visit_type': 'ICU',
  'length_of_stay_hours': 15.48,
  'risk_score': 'Low',
  'doctor_id': 165,
  'bill_id': 10582,
  'billed_amount': 20042.27,
  'approved_amount': 20042.27,
  'claim_status': 'Paid',
  'payment_days': 12.0,
  'billing_date': '2025-04-21'},
 {'patient_id': 2046,
  'age': 65,
  'gender': 'M',
  'city': 'Pune',
  'insurance_provider': 'HealthPlus',
  'chronic_flag': 1,
  'registration_date': '2025-09-21',
  'visit_id': 12232,
  'visit_date': '2025-01-20',
  'department': 'ICU',
  'visit_type': 'ER',
  'length_of_stay_hours': 38.42,
  'risk_score': 'High',
  'doctor_id': 115,
  'bill_id': 12232,
  'billed_amount': 19729.38,
  'approved_amount': 19729.38,
  'claim_status': 'Paid',
  'payment_days': 4.0,
  'billing_date': '2025-04-26'},
 {'patient_id': 1266,
  'age': 19,
  'gender': 'M',
  'city': 'Delhi',
  'insurance_provider': 'MediCareX',
  'chronic_flag': 0,
  'registration_date': '2025-03-15',
  'visit_id': 12551,
  'visit_date': '2025-01-20',
  'department': 'ICU',
  'visit_type': 'ICU',
  'length_of_stay_hours': 36.39,
  'risk_score': 'High',
  'doctor_id': 158,
  'bill_id': 12551,
  'billed_amount': 6774.33,
  'approved_amount': 6774.33,
  'claim_status': 'Paid',
  'payment_days': 13.0,
  'billing_date': '2025-02-25'},
 {'patient_id': 2744,
  'age': 55,
  'gender': 'F',
  'city': 'Chennai',
  'insurance_provider': 'CareOne',
  'chronic_flag': 1,
  'registration_date': '2025-02-10',
  'visit_id': 13142,
  'visit_date': '2025-01-20',
  'department': 'Neurology',
  'visit_type': 'ICU',
  'length_of_stay_hours': 2.2,
  'risk_score': 'Medium',
  'doctor_id': 159,
  'bill_id': 13142,
  'billed_amount': 23394.16,
  'approved_amount': 13061.8,
  'claim_status': 'Pending',
  'payment_days': 4.0,
  'billing_date': '2025-04-05'},
 {'patient_id': 2071,
  'age': 62,
  'gender': 'F',
  'city': 'Chennai',
  'insurance_provider': 'MediCareX',
  'chronic_flag': 1,
  'registration_date': '2025-07-26',
  'visit_id': 13251,
  'visit_date': '2025-01-20',
  'department': 'Cardiology',
  'visit_type': 'ER',
  'length_of_stay_hours': 24.71,
  'risk_score': 'Low',
  'doctor_id': 135,
  'bill_id': 13251,
  'billed_amount': 6907.14,
  'approved_amount': 6907.14,
  'claim_status': 'Paid',
  'payment_days': 20.0,
  'billing_date': '2025-05-11'},
 {'patient_id': 2433,
  'age': 44,
  'gender': 'M',
  'city': 'Delhi',
  'insurance_provider': 'MediCareX',
  'chronic_flag': 0,
  'registration_date': '2025-04-12',
  'visit_id': 13472,
  'visit_date': '2025-01-20',
  'department': 'Cardiology',

In [ ]:
import pymongo
import pandas as pd
DB_NAME="hospital_miops"
COLLECTION_MODEL_TABLE="model_table_df"
CONNECTION_URL="my_url"

client=pymongo.MongoClient(CONNECTION_URL)
db=client[DB_NAME]
model_table_collection=db[COLLECTION_MODEL_TABLE]


model_table=model_table_collection.insert_many(model_table_df)

In [42]:
model_table_df=pd.DataFrame(list(model_table_collection.find()))
model_table_df.head()

,_id,patient_id,age,gender,city,insurance_provider,chronic_flag,registration_date,visit_id,visit_date,...,visit_type,length_of_stay_hours,risk_score,doctor_id,bill_id,billed_amount,approved_amount,claim_status,payment_days,billing_date
0,6a32926c02c411335d6fa49e,3993,9,M,Hyderabad,HealthPlus,1,2025-10-18,684,2025-01-20,...,ICU,5.79,Low,137,684,36721.68,36721.68,Paid,19.0,2025-08-15
1,6a32926c02c411335d6fa49f,76,59,M,Delhi,HealthPlus,0,2025-07-09,1412,2025-01-20,...,ER,34.80,Medium,109,1412,8365.47,4189.20,Pending,26.0,2025-11-14
2,6a32926c02c411335d6fa4a0,3393,43,M,Hyderabad,HealthPlus,0,2025-07-10,1510,2025-01-20,...,ICU,31.37,Medium,135,1510,16529.35,0.00,Rejected,7.0,2025-04-24
3,6a32926c02c411335d6fa4a1,1998,29,M,Bangalore,MediCareX,1,2025-04-22,1549,2025-01-20,...,ER,20.88,Medium,179,1549,61827.63,61827.63,Paid,1.0,2025-10-17
4,6a32926c02c411335d6fa4a2,3500,38,M,Hyderabad,CareOne,1,2025-08-02,2275,2025-01-20,...,ICU,4.97,Low,107,2275,5860.51,4897.65,Pending,28.0,2025-08-05

In [44]:
if"_id" in model_table_df.columns:
    model_table_df.drop("_id",axis=1,inplace=True)
    
model_table_df.head()

,patient_id,age,gender,city,insurance_provider,chronic_flag,registration_date,visit_id,visit_date,department,visit_type,length_of_stay_hours,risk_score,doctor_id,bill_id,billed_amount,approved_amount,claim_status,payment_days,billing_date
0,3993,9,M,Hyderabad,HealthPlus,1,2025-10-18,684,2025-01-20,General,ICU,5.79,Low,137,684,36721.68,36721.68,Paid,19.0,2025-08-15
1,76,59,M,Delhi,HealthPlus,0,2025-07-09,1412,2025-01-20,General,ER,34.80,Medium,109,1412,8365.47,4189.20,Pending,26.0,2025-11-14
2,3393,43,M,Hyderabad,HealthPlus,0,2025-07-10,1510,2025-01-20,ICU,ICU,31.37,Medium,135,1510,16529.35,0.00,Rejected,7.0,2025-04-24
3,1998,29,M,Bangalore,MediCareX,1,2025-04-22,1549,2025-01-20,Cardiology,ER,20.88,Medium,179,1549,61827.63,61827.63,Paid,1.0,2025-10-17
4,3500,38,M,Hyderabad,CareOne,1,2025-08-02,2275,2025-01-20,Orthopedics,ICU,4.97,Low,107,2275,5860.51,4897.65,Pending,28.0,2025-08-05

In [45]:
conn.close()
print("Database connection closed successfully")

Database connection closed successfully